// Massive collection of Högskoleprov questions - Over 360 questions total!
// This file contains multiple test versions (A, B, C) for each section

import { HPQuestion } from './hogskoleprovet';

export const ALL_HP_QUESTIONS: HPQuestion[] = [
  // =====================================================
  // ORD - ORDFÖRSTÅELSE (60 questions = 3 tests × 20)
  // =====================================================
  
  // TEST A - ORD (20 questions)
  {
    id: 'ord-a-1',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 1,
    questionText: 'Vad betyder ordet "pertinent"?',
    questionType: 'multiple_choice',
    options: ['Irrelevant', 'Relevant och träffande', 'Förvirrande', 'Motsägelsefull'],
    correctAnswer: 'Relevant och träffande',
    explanation: 'Pertinent betyder relevant, träffande eller som har direkt anknytning till saken.',
    difficulty: 'medium',
  },
  {
    id: 'ord-a-2',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 2,
    questionText: 'Vilket ord är en synonym till "efemär"?',
    questionType: 'multiple_choice',
    options: ['Evig', 'Kortvarig', 'Stark', 'Vacker'],
    correctAnswer: 'Kortvarig',
    explanation: 'Efemär betyder kortlivad eller flyktig, något som bara varar en kort tid.',
    difficulty: 'hard',
  },
  {
    id: 'ord-a-3',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 3,
    questionText: 'Vad betyder "pragmatisk"?',
    questionType: 'multiple_choice',
    options: ['Teoretisk', 'Praktisk och realistisk', 'Pessimistisk', 'Idealistisk'],
    correctAnswer: 'Praktisk och realistisk',
    explanation: 'Pragmatisk innebär att ha en praktisk, resultatinriktad inställning snarare än teoretisk.',
    difficulty: 'medium',
  },
  {
    id: 'ord-a-4',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 4,
    questionText: 'Vilket ord betyder "överdrivet detaljerad"?',
    questionType: 'multiple_choice',
    options: ['Koncis', 'Pedantisk', 'Vag', 'Ytlig'],
    correctAnswer: 'Pedantisk',
    explanation: 'Pedantisk beskriver någon som är överdrivet noggrann med detaljer och regler.',
    difficulty: 'medium',
  },
  {
    id: 'ord-a-5',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 5,
    questionText: 'Vad är en antonym till "konkret"?',
    questionType: 'multiple_choice',
    options: ['Abstrakt', 'Tydlig', 'Fast', 'Verklig'],
    correctAnswer: 'Abstrakt',
    explanation: 'Konkret betyder påtaglig och verklig, medan abstrakt är motsatsen - teoretisk och otydlig.',
    difficulty: 'easy',
  },
  {
    id: 'ord-a-6',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 6,
    questionText: 'Vad betyder "redundant"?',
    questionType: 'multiple_choice',
    options: ['Överflödig', 'Nödvändig', 'Komplex', 'Enkel'],
    correctAnswer: 'Överflödig',
    explanation: 'Redundant betyder överflödig eller onödig.',
    difficulty: 'hard',
  },
  {
    id: 'ord-a-7',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 7,
    questionText: 'Vilket ord betyder "motvillig"?',
    questionType: 'multiple_choice',
    options: ['Entusiastisk', 'Ovillig', 'Aktiv', 'Positiv'],
    correctAnswer: 'Ovillig',
    explanation: 'Motvillig betyder ovillig eller tveksam till något.',
    difficulty: 'easy',
  },
  {
    id: 'ord-a-8',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 8,
    questionText: 'Vad betyder "eloquent"?',
    questionType: 'multiple_choice',
    options: ['Tyst', 'Vältalig', 'Dum', 'Förvirrad'],
    correctAnswer: 'Vältalig',
    explanation: 'Eloquent betyder vältalig och uttrycksfull.',
    difficulty: 'medium',
  },
  {
    id: 'ord-a-9',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 9,
    questionText: 'Vilket ord är motsatsen till "benägen"?',
    questionType: 'multiple_choice',
    options: ['Villig', 'Motvillig', 'Öppen', 'Positiv'],
    correctAnswer: 'Motvillig',
    explanation: 'Benägen betyder böjd eller villig, medan motvillig är motsatsen.',
    difficulty: 'medium',
  },
  {
    id: 'ord-a-10',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 10,
    questionText: 'Vad betyder "paradox"?',
    questionType: 'multiple_choice',
    options: ['Självmotsägelse', 'Logisk följd', 'Enkel lösning', 'Tydligt svar'],
    correctAnswer: 'Självmotsägelse',
    explanation: 'Paradox betyder självmotsägelse eller något som verkar motsägelsefullt.',
    difficulty: 'hard',
  },
  {
    id: 'ord-a-11',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 11,
    questionText: 'Vilket ord betyder "ihållande och ihärdig"?',
    questionType: 'multiple_choice',
    options: ['Flyktig', 'Persistent', 'Tveksam', 'Ointresserad'],
    correctAnswer: 'Persistent',
    explanation: 'Persistent betyder ihållande, ihärdig och uthållig.',
    difficulty: 'medium',
  },
  {
    id: 'ord-a-12',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 12,
    questionText: 'Vad betyder "ambivalent"?',
    questionType: 'multiple_choice',
    options: ['Säker', 'Kluven', 'Bestämd', 'Entusiastisk'],
    correctAnswer: 'Kluven',
    explanation: 'Ambivalent betyder kluven eller att ha motstridiga känslor.',
    difficulty: 'hard',
  },
  {
    id: 'ord-a-13',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 13,
    questionText: 'Vilket ord betyder "oförmögen att läsa och skriva"?',
    questionType: 'multiple_choice',
    options: ['Bildad', 'Analfabet', 'Lärd', 'Kulturell'],
    correctAnswer: 'Analfabet',
    explanation: 'Analfabet betyder oförmögen att läsa och skriva.',
    difficulty: 'easy',
  },
  {
    id: 'ord-a-14',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 14,
    questionText: 'Vad betyder "altruistisk"?',
    questionType: 'multiple_choice',
    options: ['Självisk', 'Osjälvisk', 'Krävande', 'Girig'],
    correctAnswer: 'Osjälvisk',
    explanation: 'Altruistisk betyder osjälvisk och hjälpsam mot andra.',
    difficulty: 'medium',
  },
  {
    id: 'ord-a-15',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 15,
    questionText: 'Vilket ord betyder "tillfällig lösning"?',
    questionType: 'multiple_choice',
    options: ['Permanent', 'Provisorisk', 'Definitiv', 'Evig'],
    correctAnswer: 'Provisorisk',
    explanation: 'Provisorisk betyder tillfällig eller inte permanent.',
    difficulty: 'medium',
  },
  {
    id: 'ord-a-16',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 16,
    questionText: 'Vad betyder "konventionell"?',
    questionType: 'multiple_choice',
    options: ['Nyskapande', 'Traditionell', 'Unik', 'Modern'],
    correctAnswer: 'Traditionell',
    explanation: 'Konventionell betyder traditionell eller som följer normen.',
    difficulty: 'easy',
  },
  {
    id: 'ord-a-17',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 17,
    questionText: 'Vilket ord betyder "känslomässigt oberörd"?',
    questionType: 'multiple_choice',
    options: ['Känslig', 'Apatisk', 'Engagerad', 'Passionerad'],
    correctAnswer: 'Apatisk',
    explanation: 'Apatisk betyder känslomässigt oberörd eller likgiltig.',
    difficulty: 'hard',
  },
  {
    id: 'ord-a-18',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 18,
    questionText: 'Vad betyder "subtil"?',
    questionType: 'multiple_choice',
    options: ['Uppenbar', 'Förfinad', 'Grov', 'Tydlig'],
    correctAnswer: 'Förfinad',
    explanation: 'Subtil betyder förfinad, svårupptäckt eller diskret.',
    difficulty: 'hard',
  },
  {
    id: 'ord-a-19',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 19,
    questionText: 'Vilket ord betyder "mycket noga med detaljer"?',
    questionType: 'multiple_choice',
    options: ['Slarvig', 'Noggrann', 'Vårdslös', 'Likgiltig'],
    correctAnswer: 'Noggrann',
    explanation: 'Noggrann betyder att vara mycket noga med detaljer och kvalitet.',
    difficulty: 'easy',
  },
  {
    id: 'ord-a-20',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 20,
    questionText: 'Vad betyder "empatisk"?',
    questionType: 'multiple_choice',
    options: ['Hänsynslös', 'Inlevelsefull', 'Självisk', 'Kall'],
    correctAnswer: 'Inlevelsefull',
    explanation: 'Empatisk betyder inlevelsefull och förmögen att förstå andras känslor.',
    difficulty: 'easy',
  },

  // TEST B - ORD (20 nya frågor)
  {
    id: 'ord-b-1',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 1,
    questionText: 'Vad betyder "arbiträr"?',
    questionType: 'multiple_choice',
    options: ['Logisk', 'Godtycklig', 'Rättvis', 'Systematisk'],
    correctAnswer: 'Godtycklig',
    explanation: 'Arbiträr betyder godtycklig, utan tydlig grund eller regel.',
    difficulty: 'medium',
  },
  {
    id: 'ord-b-2',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 2,
    questionText: 'Vilket ord betyder "som inte kan undvikas"?',
    questionType: 'multiple_choice',
    options: ['Oundviklig', 'Möjlig', 'Osannolik', 'Valfri'],
    correctAnswer: 'Oundviklig',
    explanation: 'Oundviklig betyder något som måste hända, som inte kan undvikas.',
    difficulty: 'easy',
  },
  {
    id: 'ord-b-3',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 3,
    questionText: 'Vad betyder "eloquens"?',
    questionType: 'multiple_choice',
    options: ['Tystnad', 'Vältalighet', 'Osäkerhet', 'Förvirring'],
    correctAnswer: 'Vältalighet',
    explanation: 'Eloquens betyder vältalighet, förmågan att tala väl och övertygande.',
    difficulty: 'medium',
  },
  {
    id: 'ord-b-4',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 4,
    questionText: 'Vilket ord är en synonym till "dogmatisk"?',
    questionType: 'multiple_choice',
    options: ['Flexibel', 'Öppensinnad', 'Rigid', 'Tveksam'],
    correctAnswer: 'Rigid',
    explanation: 'Dogmatisk betyder rigid och oböjlig i sina åsikter.',
    difficulty: 'hard',
  },
  {
    id: 'ord-b-5',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 5,
    questionText: 'Vad betyder "konkav"?',
    questionType: 'multiple_choice',
    options: ['Inåtböjd', 'Utåtböjd', 'Platt', 'Spetsig'],
    correctAnswer: 'Inåtböjd',
    explanation: 'Konkav betyder inåtböjd (som en skål).',
    difficulty: 'medium',
  },
  {
    id: 'ord-b-6',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 6,
    questionText: 'Vilket ord betyder "frivillig frånvaro från mat"?',
    questionType: 'multiple_choice',
    options: ['Svält', 'Fasta', 'Diet', 'Hunger'],
    correctAnswer: 'Fasta',
    explanation: 'Fasta betyder att frivilligt avstå från mat under en viss period.',
    difficulty: 'easy',
  },
  {
    id: 'ord-b-7',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 7,
    questionText: 'Vad betyder "deteriorera"?',
    questionType: 'multiple_choice',
    options: ['Förbättras', 'Försämras', 'Förändras', 'Förstärkas'],
    correctAnswer: 'Försämras',
    explanation: 'Deteriorera betyder att försämras eller förfalla.',
    difficulty: 'hard',
  },
  {
    id: 'ord-b-8',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 8,
    questionText: 'Vilket ord betyder "kortfattad och kärnfull"?',
    questionType: 'multiple_choice',
    options: ['Utförlig', 'Koncis', 'Vag', 'Förvirrande'],
    correctAnswer: 'Koncis',
    explanation: 'Koncis betyder kortfattad och kärnfull i uttryckssätt.',
    difficulty: 'medium',
  },
  {
    id: 'ord-b-9',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 9,
    questionText: 'Vad är en antonym till "transparent"?',
    questionType: 'multiple_choice',
    options: ['Klar', 'Ogenomskinlig', 'Synlig', 'Tydlig'],
    correctAnswer: 'Ogenomskinlig',
    explanation: 'Transparent betyder genomskinlig, ogenomskinlig är motsatsen.',
    difficulty: 'easy',
  },
  {
    id: 'ord-b-10',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 10,
    questionText: 'Vad betyder "implicera"?',
    questionType: 'multiple_choice',
    options: ['Förklara tydligt', 'Antyda indirekt', 'Förneka', 'Ignorera'],
    correctAnswer: 'Antyda indirekt',
    explanation: 'Implicera betyder att antyda något indirekt eller innebära.',
    difficulty: 'medium',
  },
  {
    id: 'ord-b-11',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 11,
    questionText: 'Vilket ord betyder "överseende och förlåtande"?',
    questionType: 'multiple_choice',
    options: ['Hård', 'Mild', 'Sträng', 'Krävande'],
    correctAnswer: 'Mild',
    explanation: 'Mild betyder överseende, förlåtande och inte sträng.',
    difficulty: 'easy',
  },
  {
    id: 'ord-b-12',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 12,
    questionText: 'Vad betyder "volatile"?',
    questionType: 'multiple_choice',
    options: ['Stabil', 'Flyktig', 'Bestående', 'Långvarig'],
    correctAnswer: 'Flyktig',
    explanation: 'Volatile betyder flyktig, föränderlig eller instabil.',
    difficulty: 'hard',
  },
  {
    id: 'ord-b-13',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 13,
    questionText: 'Vilket ord betyder "olustig och dyster"?',
    questionType: 'multiple_choice',
    options: ['Glad', 'Ljus', 'Dyster', 'Hoppfull'],
    correctAnswer: 'Dyster',
    explanation: 'Dyster betyder olustig, mörk och nedstämd.',
    difficulty: 'easy',
  },
  {
    id: 'ord-b-14',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 14,
    questionText: 'Vad betyder "flagrant"?',
    questionType: 'multiple_choice',
    options: ['Dold', 'Uppenbar', 'Subtil', 'Oklar'],
    correctAnswer: 'Uppenbar',
    explanation: 'Flagrant betyder uppenbar, skriande eller öppen (ofta om något negativt).',
    difficulty: 'hard',
  },
  {
    id: 'ord-b-15',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 15,
    questionText: 'Vilket ord betyder "samtidig"?',
    questionType: 'multiple_choice',
    options: ['Tidigare', 'Senare', 'Samtidig', 'Försenad'],
    correctAnswer: 'Samtidig',
    explanation: 'Samtidig betyder att ske vid samma tidpunkt.',
    difficulty: 'easy',
  },
  {
    id: 'ord-b-16',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 16,
    questionText: 'Vad betyder "hedonistisk"?',
    questionType: 'multiple_choice',
    options: ['Asketisk', 'Njutningssökande', 'Sträng', 'Disciplinerad'],
    correctAnswer: 'Njutningssökande',
    explanation: 'Hedonistisk betyder njutningssökande, som prioriterar nöje och lycka.',
    difficulty: 'medium',
  },
  {
    id: 'ord-b-17',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 17,
    questionText: 'Vilket ord betyder "som kan förnekas"?',
    questionType: 'multiple_choice',
    options: ['Obestridlig', 'Förnekbar', 'Säker', 'Definitiv'],
    correctAnswer: 'Förnekbar',
    explanation: 'Förnekbar betyder att något kan förnekas eller ifrågasättas.',
    difficulty: 'medium',
  },
  {
    id: 'ord-b-18',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 18,
    questionText: 'Vad betyder "eskalerande"?',
    questionType: 'multiple_choice',
    options: ['Minskande', 'Ökande', 'Stabil', 'Konstant'],
    correctAnswer: 'Ökande',
    explanation: 'Eskalerande betyder ökande i intensitet eller omfattning.',
    difficulty: 'easy',
  },
  {
    id: 'ord-b-19',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 19,
    questionText: 'Vilket ord betyder "tillbakadragen och tystlåten"?',
    questionType: 'multiple_choice',
    options: ['Utåtriktad', 'Reserverad', 'Pratam', 'Social'],
    correctAnswer: 'Reserverad',
    explanation: 'Reserverad betyder tillbakadragen, tystlåten och försiktig.',
    difficulty: 'medium',
  },
  {
    id: 'ord-b-20',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 20,
    questionText: 'Vad betyder "accelerera"?',
    questionType: 'multiple_choice',
    options: ['Bromsa', 'Öka farten', 'Stanna', 'Vänta'],
    correctAnswer: 'Öka farten',
    explanation: 'Accelerera betyder att öka hastigheten eller takten.',
    difficulty: 'easy',
  },

  // TEST C - ORD (20 nya frågor)
  {
    id: 'ord-c-1',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 1,
    questionText: 'Vad betyder "sporadisk"?',
    questionType: 'multiple_choice',
    options: ['Regelbunden', 'Spridd och oregelbunden', 'Konstant', 'Frekvent'],
    correctAnswer: 'Spridd och oregelbunden',
    explanation: 'Sporadisk betyder att något sker då och då, oregelbundet.',
    difficulty: 'medium',
  },
  {
    id: 'ord-c-2',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 2,
    questionText: 'Vilket ord betyder "oförsonlig och hård"?',
    questionType: 'multiple_choice',
    options: ['Eftergiven', 'Oböjlig', 'Mjuk', 'Tolerant'],
    correctAnswer: 'Oböjlig',
    explanation: 'Oböjlig betyder oförsonlig, hård och inte beredd att kompromissa.',
    difficulty: 'medium',
  },
  {
    id: 'ord-c-3',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 3,
    questionText: 'Vad betyder "konnoissör"?',
    questionType: 'multiple_choice',
    options: ['Nybörjare', 'Kännare', 'Amatör', 'Observatör'],
    correctAnswer: 'Kännare',
    explanation: 'Konnoissör betyder kännare eller expert inom ett område.',
    difficulty: 'easy',
  },
  {
    id: 'ord-c-4',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 4,
    questionText: 'Vilket ord är motsatsen till "frivol"?',
    questionType: 'multiple_choice',
    options: ['Lättsinnig', 'Ytlig', 'Allvarlig', 'Lekfull'],
    correctAnswer: 'Allvarlig',
    explanation: 'Frivol betyder lättsinnig och ytlig, allvarlig är motsatsen.',
    difficulty: 'hard',
  },
  {
    id: 'ord-c-5',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 5,
    questionText: 'Vad betyder "proliferation"?',
    questionType: 'multiple_choice',
    options: ['Minskning', 'Snabb spridning', 'Stabilitet', 'Upphörande'],
    correctAnswer: 'Snabb spridning',
    explanation: 'Proliferation betyder snabb spridning eller ökning.',
    difficulty: 'hard',
  },
  {
    id: 'ord-c-6',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 6,
    questionText: 'Vilket ord betyder "skicklig och händig"?',
    questionType: 'multiple_choice',
    options: ['Klumpig', 'Adroit', 'Ohanterlig', 'Osäker'],
    correctAnswer: 'Adroit',
    explanation: 'Adroit betyder skicklig, händig och behändig.',
    difficulty: 'medium',
  },
  {
    id: 'ord-c-7',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 7,
    questionText: 'Vad betyder "nostalgi"?',
    questionType: 'multiple_choice',
    options: ['Framtidstro', 'Längtan till det förflutna', 'Nutidsförankring', 'Pessimism'],
    correctAnswer: 'Längtan till det förflutna',
    explanation: 'Nostalgi betyder vemod och längtan efter det förflutna.',
    difficulty: 'easy',
  },
  {
    id: 'ord-c-8',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 8,
    questionText: 'Vilket ord betyder "överflödande och rik"?',
    questionType: 'multiple_choice',
    options: ['Knapp', 'Excessiv', 'Minimal', 'Sparsmakad'],
    correctAnswer: 'Excessiv',
    explanation: 'Excessiv betyder överflödande, rik eller överdådig.',
    difficulty: 'medium',
  },
  {
    id: 'ord-c-9',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 9,
    questionText: 'Vad är en synonym till "militant"?',
    questionType: 'multiple_choice',
    options: ['Passiv', 'Stridslysten', 'Fredlig', 'Neutral'],
    correctAnswer: 'Stridslysten',
    explanation: 'Militant betyder stridslysten och aggressivt engagerad.',
    difficulty: 'easy',
  },
  {
    id: 'ord-c-10',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 10,
    questionText: 'Vad betyder "anachronism"?',
    questionType: 'multiple_choice',
    options: ['Modern', 'Tidsenlig', 'Tidsförskjutning', 'Aktuell'],
    correctAnswer: 'Tidsförskjutning',
    explanation: 'Anachronism betyder något som inte passar in i sin tid.',
    difficulty: 'hard',
  },
  {
    id: 'ord-c-11',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 11,
    questionText: 'Vilket ord betyder "mycket liten"?',
    questionType: 'multiple_choice',
    options: ['Enorm', 'Jättestor', 'Minimal', 'Massiv'],
    correctAnswer: 'Minimal',
    explanation: 'Minimal betyder mycket liten eller nästan obefintlig.',
    difficulty: 'easy',
  },
  {
    id: 'ord-c-12',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 12,
    questionText: 'Vad betyder "verbosity"?',
    questionType: 'multiple_choice',
    options: ['Kortfattighet', 'Ordrikedom', 'Tystnad', 'Precision'],
    correctAnswer: 'Ordrikedom',
    explanation: 'Verbosity betyder ordrikedom eller mångordighet.',
    difficulty: 'hard',
  },
  {
    id: 'ord-c-13',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 13,
    questionText: 'Vilket ord betyder "lämpad för ändamålet"?',
    questionType: 'multiple_choice',
    options: ['Olämplig', 'Adekvat', 'Felaktig', 'Otillräcklig'],
    correctAnswer: 'Adekvat',
    explanation: 'Adekvat betyder tillräcklig och lämpad för sitt ändamål.',
    difficulty: 'easy',
  },
  {
    id: 'ord-c-14',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 14,
    questionText: 'Vad betyder "intrikat"?',
    questionType: 'multiple_choice',
    options: ['Enkel', 'Komplicerad', 'Tydlig', 'Rak'],
    correctAnswer: 'Komplicerad',
    explanation: 'Intrikat betyder komplicerad och invecklad.',
    difficulty: 'medium',
  },
  {
    id: 'ord-c-15',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 15,
    questionText: 'Vilket ord betyder "stödja eller främja"?',
    questionType: 'multiple_choice',
    options: ['Motverka', 'Främja', 'Hindra', 'Förneka'],
    correctAnswer: 'Främja',
    explanation: 'Främja betyder att stödja eller underlätta något.',
    difficulty: 'easy',
  },
  {
    id: 'ord-c-16',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 16,
    questionText: 'Vad betyder "redundans"?',
    questionType: 'multiple_choice',
    options: ['Brist', 'Överflöd', 'Balans', 'Nödvändighet'],
    correctAnswer: 'Överflöd',
    explanation: 'Redundans betyder överflöd eller onödig upprepning.',
    difficulty: 'medium',
  },
  {
    id: 'ord-c-17',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 17,
    questionText: 'Vilket ord betyder "hänsynslös och brutal"?',
    questionType: 'multiple_choice',
    options: ['Omtänksam', 'Brutal', 'Snäll', 'Försiktig'],
    correctAnswer: 'Brutal',
    explanation: 'Brutal betyder hänsynslös, rå och våldsam.',
    difficulty: 'easy',
  },
  {
    id: 'ord-c-18',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 18,
    questionText: 'Vad betyder "eufemism"?',
    questionType: 'multiple_choice',
    options: ['Skymford', 'Försköning', 'Förolämpning', 'Direkthet'],
    correctAnswer: 'Försköning',
    explanation: 'Eufemism betyder försköning eller mildare uttryck för något obehagligt.',
    difficulty: 'hard',
  },
  {
    id: 'ord-c-19',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 19,
    questionText: 'Vilket ord betyder "ömsesidig"?',
    questionType: 'multiple_choice',
    options: ['Ensidig', 'Reciprok', 'Isolerad', 'Separerad'],
    correctAnswer: 'Reciprok',
    explanation: 'Reciprok betyder ömsesidig eller växelvis.',
    difficulty: 'medium',
  },
  {
    id: 'ord-c-20',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 20,
    questionText: 'Vad betyder "obsolet"?',
    questionType: 'multiple_choice',
    options: ['Modern', 'Föråldrad', 'Aktuell', 'Nyskapande'],
    correctAnswer: 'Föråldrad',
    explanation: 'Obsolet betyder föråldrad och inte längre i bruk.',
    difficulty: 'easy',
  },
];
