// Högskoleprov Constants and Sample Questions

export interface HPSectionConfig {
  code: string;
  name: string;
  fullName: string;
  description: string;
  icon: string;
  color: string;
  gradientColors: readonly [string, string];
  timeMinutes: number;
  questionCount: number;
  maxScore: number;
  tips: string[];
}

export const HP_SECTIONS: HPSectionConfig[] = [
  {
    code: 'ORD',
    name: 'ORD',
    fullName: 'Ordförståelse',
    description: 'Testa din ordförråd och förmåga att förstå ords betydelse',
    icon: '📚',
    color: '#6366F1',
    gradientColors: ['#6366F1', '#8B5CF6'] as const,
    timeMinutes: 20,
    questionCount: 20,
    maxScore: 20,
    tips: [
      'Läs mycket för att bygga ordförråd',
      'Lär dig ordstammar och prefix/suffix',
      'Öva på synonymer och antonymer',
    ],
  },
  {
    code: 'LÄS',
    name: 'LÄS',
    fullName: 'Läsförståelse',
    description: 'Förstå och analysera texter av olika slag',
    icon: '📖',
    color: '#10B981',
    gradientColors: ['#10B981', '#059669'] as const,
    timeMinutes: 55,
    questionCount: 20,
    maxScore: 20,
    tips: [
      'Läs frågan först, sedan texten',
      'Markera nyckelord i texten',
      'Var uppmärksam på nyanser',
    ],
  },
  {
    code: 'MEK',
    name: 'MEK',
    fullName: 'Meningskomplettering',
    description: 'Komplettera meningar logiskt och grammatiskt korrekt',
    icon: '✏️',
    color: '#F59E0B',
    gradientColors: ['#F59E0B', '#D97706'] as const,
    timeMinutes: 25,
    questionCount: 20,
    maxScore: 20,
    tips: [
      'Leta efter ledtrådar i meningen',
      'Tänk på grammatisk kongruens',
      'Eliminera uppenbart felaktiga alternativ',
    ],
  },
  {
    code: 'XYZ',
    name: 'XYZ',
    fullName: 'Diagram, tabeller & kartor',
    description: 'Tolka och analysera visuell information',
    icon: '📊',
    color: '#EC4899',
    gradientColors: ['#EC4899', '#DB2777'] as const,
    timeMinutes: 55,
    questionCount: 20,
    maxScore: 20,
    tips: [
      'Läs alltid rubriker och axlar först',
      'Var noga med enheter',
      'Dubbelkolla beräkningar',
    ],
  },
  {
    code: 'KVA',
    name: 'KVA',
    fullName: 'Kvantitativ analys',
    description: 'Jämför kvantiteter och analysera matematiska samband',
    icon: '🔢',
    color: '#06B6D4',
    gradientColors: ['#06B6D4', '#0891B2'] as const,
    timeMinutes: 25,
    questionCount: 20,
    maxScore: 20,
    tips: [
      'Sätt in enkla värden för att testa',
      'Jämför systematiskt',
      'Var uppmärksam på specialfall',
    ],
  },
  {
    code: 'DTK',
    name: 'DTK',
    fullName: 'Diagram, tabeller & kartor',
    description: 'Avancerad tolkning av data och teknisk information',
    icon: '📈',
    color: '#EF4444',
    gradientColors: ['#EF4444', '#DC2626'] as const,
    timeMinutes: 55,
    questionCount: 20,
    maxScore: 20,
    tips: [
      'Ta god tid på dig att förstå datan',
      'Notera trender och mönster',
      'Använd uteslutningsmetoden',
    ],
  },
];

export const HP_VERBAL_SECTIONS = ['ORD', 'LÄS', 'MEK'];
export const HP_QUANTITATIVE_SECTIONS = ['XYZ', 'KVA', 'DTK'];

export const HP_FULL_TEST_CONFIG = {
  totalTime: 235,
  totalQuestions: 120,
  maxScore: 2.0,
  passingScore: 0.0,
  sections: HP_SECTIONS,
};

export const HP_SCORE_RANGES = [
  { min: 0.0, max: 0.4, label: 'Grundnivå', description: 'Du har potential att förbättras mycket!', color: '#EF4444' },
  { min: 0.4, max: 0.8, label: 'Under medel', description: 'Fortsätt träna så kommer du dit!', color: '#F59E0B' },
  { min: 0.8, max: 1.2, label: 'Medelnivå', description: 'Du ligger bra till!', color: '#06B6D4' },
  { min: 1.2, max: 1.6, label: 'Över medel', description: 'Starkt resultat!', color: '#10B981' },
  { min: 1.6, max: 2.0, label: 'Toppnivå', description: 'Utmärkt prestation!', color: '#6366F1' },
];

export const HP_MILESTONES = [
  { id: 'first_section', name: 'Första steget', description: 'Genomför din första delprovsövning', icon: '🎯', xp: 50 },
  { id: 'first_full_test', name: 'Hela provet', description: 'Genomför ett komplett högskoleprov', icon: '🏆', xp: 200 },
  { id: 'perfect_section', name: 'Perfekt sektion', description: 'Få 100% på ett delprov', icon: '⭐', xp: 100 },
  { id: 'five_tests', name: 'Dedikerad', description: 'Genomför 5 kompletta prov', icon: '🔥', xp: 300 },
  { id: 'all_sections', name: 'Allsidig', description: 'Öva på alla 6 delprov', icon: '🎓', xp: 150 },
  { id: 'streak_3', name: '3-dagars streak', description: 'Öva 3 dagar i rad', icon: '📆', xp: 75 },
  { id: 'streak_7', name: 'Veckostjärna', description: 'Öva 7 dagar i rad', icon: '🌟', xp: 150 },
  { id: 'improvement', name: 'Framsteg', description: 'Förbättra ditt resultat med 0.2 poäng', icon: '📈', xp: 100 },
];

export interface HPQuestion {
  id: string;
  sectionCode: string;
  testVersion?: string;
  questionNumber: number;
  questionText: string;
  questionType: 'multiple_choice' | 'comparison' | 'reading_comprehension';
  options: string[];
  correctAnswer: string;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
  readingPassage?: string;
  imageUrl?: string;
}

export interface HPTestVersion {
  id: string;
  sectionCode: string;
  name: string;
  questionCount: number;
  season?: 'spring' | 'fall';
  year?: number;
}

export interface HPFullTestVersion {
  id: string;
  name: string;
  displayName: string;
  season: 'spring' | 'fall';
  year: number;
  questionCount: number;
  timeMinutes: number;
}

// Full test versions (complete HP tests)
export const HP_FULL_TEST_VERSIONS: HPFullTestVersion[] = [
  { id: 'hp-2024-spring', name: 'Vår 2024', displayName: 'Högskoleprov Vår 2024', season: 'spring', year: 2024, questionCount: 120, timeMinutes: 235 },
  { id: 'hp-2023-fall', name: 'Höst 2023', displayName: 'Högskoleprov Höst 2023', season: 'fall', year: 2023, questionCount: 120, timeMinutes: 235 },
  { id: 'hp-2023-spring', name: 'Vår 2023', displayName: 'Högskoleprov Vår 2023', season: 'spring', year: 2023, questionCount: 120, timeMinutes: 235 },
  { id: 'hp-2022-fall', name: 'Höst 2022', displayName: 'Högskoleprov Höst 2022', season: 'fall', year: 2022, questionCount: 120, timeMinutes: 235 },
  { id: 'hp-2022-spring', name: 'Vår 2022', displayName: 'Högskoleprov Vår 2022', season: 'spring', year: 2022, questionCount: 120, timeMinutes: 235 },
];

// Test versions available for each section
export const HP_TEST_VERSIONS: HPTestVersion[] = [
  { id: 'ord-a', sectionCode: 'ORD', name: 'Test A', questionCount: 20 },
  { id: 'ord-b', sectionCode: 'ORD', name: 'Test B', questionCount: 20 },
  { id: 'ord-c', sectionCode: 'ORD', name: 'Test C', questionCount: 20 },
  { id: 'las-a', sectionCode: 'LÄS', name: 'Test A', questionCount: 20 },
  { id: 'las-b', sectionCode: 'LÄS', name: 'Test B', questionCount: 20 },
  { id: 'las-c', sectionCode: 'LÄS', name: 'Test C', questionCount: 20 },
  { id: 'mek-a', sectionCode: 'MEK', name: 'Test A', questionCount: 20 },
  { id: 'mek-b', sectionCode: 'MEK', name: 'Test B', questionCount: 20 },
  { id: 'mek-c', sectionCode: 'MEK', name: 'Test C', questionCount: 20 },
  { id: 'xyz-a', sectionCode: 'XYZ', name: 'Test A', questionCount: 20 },
  { id: 'xyz-b', sectionCode: 'XYZ', name: 'Test B', questionCount: 20 },
  { id: 'xyz-c', sectionCode: 'XYZ', name: 'Test C', questionCount: 20 },
  { id: 'kva-a', sectionCode: 'KVA', name: 'Test A', questionCount: 20 },
  { id: 'kva-b', sectionCode: 'KVA', name: 'Test B', questionCount: 20 },
  { id: 'kva-c', sectionCode: 'KVA', name: 'Test C', questionCount: 20 },
  { id: 'dtk-a', sectionCode: 'DTK', name: 'Test A', questionCount: 20 },
  { id: 'dtk-b', sectionCode: 'DTK', name: 'Test B', questionCount: 20 },
  { id: 'dtk-c', sectionCode: 'DTK', name: 'Test C', questionCount: 20 },
];

// All HP questions organized by test version
export const SAMPLE_HP_QUESTIONS: HPQuestion[] = [
  // ORD - Ordförståelse Test A (20 questions)
  {
    id: 'ord-a-1',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 1,
    questionText: 'Vad betyder ordet "pertinent"?',
    questionType: 'multiple_choice',
    options: ['Irrelevant', 'Relevant och träffande', 'Förvirrande', 'Motsägelsefull'],
    correctAnswer: 'Relevant och träffande',
    explanation: 'Pertinent betyder relevant, träffande eller som har direkt anknytning till saken.',
    difficulty: 'medium',
  },
  {
    id: 'ord-a-2',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 2,
    questionText: 'Vilket ord är en synonym till "efemär"?',
    questionType: 'multiple_choice',
    options: ['Evig', 'Kortvarig', 'Stark', 'Vacker'],
    correctAnswer: 'Kortvarig',
    explanation: 'Efemär betyder kortlivad eller flyktig, något som bara varar en kort tid.',
    difficulty: 'hard',
  },
  {
    id: 'ord-a-3',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 3,
    questionText: 'Vad betyder "pragmatisk"?',
    questionType: 'multiple_choice',
    options: ['Teoretisk', 'Praktisk och realistisk', 'Pessimistisk', 'Idealistisk'],
    correctAnswer: 'Praktisk och realistisk',
    explanation: 'Pragmatisk innebär att ha en praktisk, resultatinriktad inställning snarare än teoretisk.',
    difficulty: 'medium',
  },
  {
    id: 'ord-a-4',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 4,
    questionText: 'Vilket ord betyder "överdrivet detaljerad"?',
    questionType: 'multiple_choice',
    options: ['Koncis', 'Pedantisk', 'Vag', 'Ytlig'],
    correctAnswer: 'Pedantisk',
    explanation: 'Pedantisk beskriver någon som är överdrivet noggrann med detaljer och regler.',
    difficulty: 'medium',
  },
  {
    id: 'ord-a-5',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 5,
    questionText: 'Vad är en antonym till "konkret"?',
    questionType: 'multiple_choice',
    options: ['Abstrakt', 'Tydlig', 'Fast', 'Verklig'],
    correctAnswer: 'Abstrakt',
    explanation: 'Konkret betyder påtaglig och verklig, medan abstrakt är motsatsen - teoretisk och otydlig.',
    difficulty: 'easy',
  },
  {
    id: 'ord-a-6',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 6,
    questionText: 'Vad betyder "redundant"?',
    questionType: 'multiple_choice',
    options: ['Överflödig', 'Nödvändig', 'Komplex', 'Enkel'],
    correctAnswer: 'Överflödig',
    explanation: 'Redundant betyder överflödig eller onödig.',
    difficulty: 'hard',
  },
  {
    id: 'ord-a-7',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 7,
    questionText: 'Vilket ord betyder "motvillig"?',
    questionType: 'multiple_choice',
    options: ['Entusiastisk', 'Ovillig', 'Aktiv', 'Positiv'],
    correctAnswer: 'Ovillig',
    explanation: 'Motvillig betyder ovillig eller tveksam till något.',
    difficulty: 'easy',
  },
  {
    id: 'ord-a-8',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 8,
    questionText: 'Vad betyder "eloquent"?',
    questionType: 'multiple_choice',
    options: ['Tyst', 'Vältalig', 'Dum', 'Förvirrad'],
    correctAnswer: 'Vältalig',
    explanation: 'Eloquent betyder vältalig och uttrycksfull.',
    difficulty: 'medium',
  },
  {
    id: 'ord-a-9',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 9,
    questionText: 'Vilket ord är motsatsen till "benägen"?',
    questionType: 'multiple_choice',
    options: ['Villig', 'Motvillig', 'Öppen', 'Positiv'],
    correctAnswer: 'Motvillig',
    explanation: 'Benägen betyder böjd eller villig, medan motvillig är motsatsen.',
    difficulty: 'medium',
  },
  {
    id: 'ord-a-10',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 10,
    questionText: 'Vad betyder "paradox"?',
    questionType: 'multiple_choice',
    options: ['Självmotsägelse', 'Logisk följd', 'Enkel lösning', 'Tydligt svar'],
    correctAnswer: 'Självmotsägelse',
    explanation: 'Paradox betyder självmotsägelse eller något som verkar motsägelsefullt.',
    difficulty: 'hard',
  },
  {
    id: 'ord-a-11',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 11,
    questionText: 'Vilket ord betyder "ihållande och ihärdig"?',
    questionType: 'multiple_choice',
    options: ['Flyktig', 'Persistent', 'Tveksam', 'Ointresserad'],
    correctAnswer: 'Persistent',
    explanation: 'Persistent betyder ihållande, ihärdig och uthållig.',
    difficulty: 'medium',
  },
  {
    id: 'ord-a-12',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 12,
    questionText: 'Vad betyder "ambivalent"?',
    questionType: 'multiple_choice',
    options: ['Säker', 'Kluven', 'Bestämd', 'Entusiastisk'],
    correctAnswer: 'Kluven',
    explanation: 'Ambivalent betyder kluven eller att ha motstridiga känslor.',
    difficulty: 'hard',
  },
  {
    id: 'ord-a-13',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 13,
    questionText: 'Vilket ord betyder "oförmögen att läsa och skriva"?',
    questionType: 'multiple_choice',
    options: ['Bildad', 'Analfabet', 'Lärd', 'Kulturell'],
    correctAnswer: 'Analfabet',
    explanation: 'Analfabet betyder oförmögen att läsa och skriva.',
    difficulty: 'easy',
  },
  {
    id: 'ord-a-14',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 14,
    questionText: 'Vad betyder "altruistisk"?',
    questionType: 'multiple_choice',
    options: ['Självisk', 'Osjälvisk', 'Krävande', 'Girig'],
    correctAnswer: 'Osjälvisk',
    explanation: 'Altruistisk betyder osjälvisk och hjälpsam mot andra.',
    difficulty: 'medium',
  },
  {
    id: 'ord-a-15',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 15,
    questionText: 'Vilket ord betyder "tillfällig lösning"?',
    questionType: 'multiple_choice',
    options: ['Permanent', 'Provisorisk', 'Definitiv', 'Evig'],
    correctAnswer: 'Provisorisk',
    explanation: 'Provisorisk betyder tillfällig eller inte permanent.',
    difficulty: 'medium',
  },
  {
    id: 'ord-a-16',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 16,
    questionText: 'Vad betyder "konventionell"?',
    questionType: 'multiple_choice',
    options: ['Nyskapande', 'Traditionell', 'Unik', 'Modern'],
    correctAnswer: 'Traditionell',
    explanation: 'Konventionell betyder traditionell eller som följer normen.',
    difficulty: 'easy',
  },
  {
    id: 'ord-a-17',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 17,
    questionText: 'Vilket ord betyder "känslomässigt oberörd"?',
    questionType: 'multiple_choice',
    options: ['Känslig', 'Apatisk', 'Engagerad', 'Passionerad'],
    correctAnswer: 'Apatisk',
    explanation: 'Apatisk betyder känslomässigt oberörd eller likgiltig.',
    difficulty: 'hard',
  },
  {
    id: 'ord-a-18',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 18,
    questionText: 'Vad betyder "subtil"?',
    questionType: 'multiple_choice',
    options: ['Uppenbar', 'Förfinad', 'Grov', 'Tydlig'],
    correctAnswer: 'Förfinad',
    explanation: 'Subtil betyder förfinad, svårupptäckt eller diskret.',
    difficulty: 'hard',
  },
  {
    id: 'ord-a-19',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 19,
    questionText: 'Vilket ord betyder "mycket noga med detaljer"?',
    questionType: 'multiple_choice',
    options: ['Slarvig', 'Noggrann', 'Vårdslös', 'Likgiltig'],
    correctAnswer: 'Noggrann',
    explanation: 'Noggrann betyder att vara mycket noga med detaljer och kvalitet.',
    difficulty: 'easy',
  },
  {
    id: 'ord-a-20',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 20,
    questionText: 'Vad betyder "empatisk"?',
    questionType: 'multiple_choice',
    options: ['Hänsynslös', 'Inlevelsefull', 'Självisk', 'Kall'],
    correctAnswer: 'Inlevelsefull',
    explanation: 'Empatisk betyder inlevelsefull och förmögen att förstå andras känslor.',
    difficulty: 'easy',
  },

  // LÄS - Läsförståelse (20 questions)
  {
    id: 'las-1',
    sectionCode: 'LÄS',
    questionNumber: 1,
    questionText: 'Vad är författarens huvudsakliga syfte med texten?',
    questionType: 'reading_comprehension',
    readingPassage: 'Klimatförändringarna påverkar ekosystemen på flera sätt. Temperaturen stiger, havsnivåerna höjs och extremväder blir vanligare. Forskare betonar vikten av att agera nu för att begränsa skadorna. Genom att minska utsläppen av växthusgaser kan vi bromsa utvecklingen och ge naturen en chans att anpassa sig.',
    options: [
      'Att skrämma läsaren',
      'Att informera och uppmana till handling',
      'Att kritisera politiker',
      'Att presentera ny forskning'
    ],
    correctAnswer: 'Att informera och uppmana till handling',
    explanation: 'Texten informerar om klimatförändringarnas effekter och avslutar med en uppmaning att agera genom att minska utsläpp.',
    difficulty: 'medium',
  },
  {
    id: 'las-2',
    sectionCode: 'LÄS',
    questionNumber: 2,
    questionText: 'Enligt texten, vad kan hända om vi minskar utsläppen?',
    questionType: 'reading_comprehension',
    readingPassage: 'Klimatförändringarna påverkar ekosystemen på flera sätt. Temperaturen stiger, havsnivåerna höjs och extremväder blir vanligare. Forskare betonar vikten av att agera nu för att begränsa skadorna. Genom att minska utsläppen av växthusgaser kan vi bromsa utvecklingen och ge naturen en chans att anpassa sig.',
    options: [
      'Klimatförändringarna stannar helt',
      'Naturen får tid att anpassa sig',
      'Temperaturen sjunker omedelbart',
      'Havsnivåerna återgår till det normala'
    ],
    correctAnswer: 'Naturen får tid att anpassa sig',
    explanation: 'Texten säger att minskade utsläpp kan "ge naturen en chans att anpassa sig".',
    difficulty: 'easy',
  },
  {
    id: 'las-3',
    sectionCode: 'LÄS',
    questionNumber: 3,
    questionText: 'Vilken ton har författaren i texten?',
    questionType: 'reading_comprehension',
    readingPassage: 'Den digitala revolutionen har förändrat vårt sätt att kommunicera på ett sätt som ingen kunde förutse för bara några decennier sedan. Sociala medier har gett röst åt miljoner, men har också skapat nya utmaningar för demokratin. Informationsspridningen är snabbare än någonsin, men kvaliteten på informationen varierar kraftigt.',
    options: ['Pessimistisk', 'Balanserad och reflekterande', 'Entusiastisk', 'Aggressiv'],
    correctAnswer: 'Balanserad och reflekterande',
    explanation: 'Författaren presenterar både positiva och negativa aspekter av den digitala revolutionen.',
    difficulty: 'medium',
  },
  {
    id: 'las-4',
    sectionCode: 'LÄS',
    questionNumber: 4,
    questionText: 'Vad är textens huvudtema?',
    questionType: 'reading_comprehension',
    readingPassage: 'Artificiell intelligens utvecklas i rasande takt och förändrar många branscher. Automatisering av arbetsuppgifter leder till ökad effektivitet, men väcker också frågor om framtidens arbetsmarknad. Vissa menar att nya jobb kommer att skapas, medan andra är oroliga för massarbetslöshet. Det är tydligt att samhället måste anpassa sig till dessa förändringar.',
    options: ['AI:s tekniska detaljer', 'AI:s påverkan på samhället', 'Programmeringens framtid', 'Robotars utseende'],
    correctAnswer: 'AI:s påverkan på samhället',
    explanation: 'Texten fokuserar på hur AI påverkar arbetsmarknaden och samhället.',
    difficulty: 'easy',
  },
  {
    id: 'las-5',
    sectionCode: 'LÄS',
    questionNumber: 5,
    questionText: 'Vilka två perspektiv presenteras i texten?',
    questionType: 'reading_comprehension',
    readingPassage: 'Artificiell intelligens utvecklas i rasande takt och förändrar många branscher. Automatisering av arbetsuppgifter leder till ökad effektivitet, men väcker också frågor om framtidens arbetsmarknad. Vissa menar att nya jobb kommer att skapas, medan andra är oroliga för massarbetslöshet. Det är tydligt att samhället måste anpassa sig till dessa förändringar.',
    options: [
      'Optimism och pessimism om AI:s effekt på arbetsmarknaden',
      'Tekniska och ekonomiska aspekter',
      'Nationella och internationella perspektiv',
      'Kortsiktiga och långsiktiga effekter'
    ],
    correctAnswer: 'Optimism och pessimism om AI:s effekt på arbetsmarknaden',
    explanation: 'Texten presenterar både de som tror på nya jobb och de som oroar sig för arbetslöshet.',
    difficulty: 'medium',
  },
  {
    id: 'las-6',
    sectionCode: 'LÄS',
    questionNumber: 6,
    questionText: 'Vad kan man dra för slutsats från texten?',
    questionType: 'reading_comprehension',
    readingPassage: 'Historiska studier visar att städer alltid har varit viktiga för kulturell utveckling. Under renässansen blomstrade konst och vetenskap i städer som Florens och Venedig. Idag ser vi samma mönster med innovationshubbar som Silicon Valley. Koncentrationen av människor och idéer skapar en kreativ miljö som är svår att uppnå på andra platser.',
    options: [
      'Landsbygden är viktigare för innovation',
      'Städer främjar kreativitet och innovation',
      'Renässansen var en kort period',
      'Silicon Valley är det enda innovationscentret'
    ],
    correctAnswer: 'Städer främjar kreativitet och innovation',
    explanation: 'Texten visar genom exempel att städer historiskt och idag skapar miljöer för kreativitet.',
    difficulty: 'easy',
  },
  {
    id: 'las-7',
    sectionCode: 'LÄS',
    questionNumber: 7,
    questionText: 'Vad är författarens attityd till ämnet?',
    questionType: 'reading_comprehension',
    readingPassage: 'Den svenska välfärdsmodellen har länge varit en förebild för andra länder. Med omfattande sociala skyddsnät och gratis utbildning har Sverige lyckats kombinera ekonomisk tillväxt med social rättvisa. Dock står modellen inför nya utmaningar i form av globalisering och demografiska förändringar som kräver anpassning.',
    options: ['Kritisk', 'Uppskattande men realistisk', 'Cynisk', 'Ointresserad'],
    correctAnswer: 'Uppskattande men realistisk',
    explanation: 'Författaren berömmer välfärdsmodellen men erkänner också att den står inför utmaningar.',
    difficulty: 'medium',
  },
  {
    id: 'las-8',
    sectionCode: 'LÄS',
    questionNumber: 8,
    questionText: 'Enligt texten, varför är den svenska modellen framgångsrik?',
    questionType: 'reading_comprehension',
    readingPassage: 'Den svenska välfärdsmodellen har länge varit en förebild för andra länder. Med omfattande sociala skyddsnät och gratis utbildning har Sverige lyckats kombinera ekonomisk tillväxt med social rättvisa. Dock står modellen inför nya utmaningar i form av globalisering och demografiska förändringar som kräver anpassning.',
    options: [
      'På grund av Sveriges storlek',
      'Genom att kombinera ekonomisk tillväxt och social rättvisa',
      'Tack vare isolering från omvärlden',
      'Genom att kopiera andra länder'
    ],
    correctAnswer: 'Genom att kombinera ekonomisk tillväxt och social rättvisa',
    explanation: 'Texten nämner explicit att Sverige lyckats kombinera dessa två aspekter.',
    difficulty: 'easy',
  },
  {
    id: 'las-9',
    sectionCode: 'LÄS',
    questionNumber: 9,
    questionText: 'Vad är den underliggande budskapet i texten?',
    questionType: 'reading_comprehension',
    readingPassage: 'Många tror att framgång handlar om talang, men forskning visar att hårt arbete och uthållighet ofta är viktigare. De som lyckas är sällan de mest begåvade, utan de som inte ger upp när det blir svårt. Att utveckla en tillväxtmentalitet, där misslyckanden ses som lärdomar, är avgörande för långsiktig framgång.',
    options: [
      'Talang är irrelevant',
      'Uthållighet viktigare än talang',
      'Misslyckanden bör undvikas',
      'Framgång är omöjlig utan begåvning'
    ],
    correctAnswer: 'Uthållighet viktigare än talang',
    explanation: 'Texten betonar att hårt arbete och uthållighet ofta är viktigare än talang.',
    difficulty: 'medium',
  },
  {
    id: 'las-10',
    sectionCode: 'LÄS',
    questionNumber: 10,
    questionText: 'Vad menas med "tillväxtmentalitet" i texten?',
    questionType: 'reading_comprehension',
    readingPassage: 'Många tror att framgång handlar om talang, men forskning visar att hårt arbete och uthållighet ofta är viktigare. De som lyckas är sällan de mest begåvade, utan de som inte ger upp när det blir svårt. Att utveckla en tillväxtmentalitet, där misslyckanden ses som lärdomar, är avgörande för långsiktig framgång.',
    options: [
      'Att alltid växa fysiskt',
      'Att se misslyckanden som lärtillfällen',
      'Att fokusera på ekonomisk tillväxt',
      'Att undvika risker'
    ],
    correctAnswer: 'Att se misslyckanden som lärtillfällen',
    explanation: 'Texten definierar tillväxtmentalitet som att se misslyckanden som lärdomar.',
    difficulty: 'easy',
  },
  {
    id: 'las-11',
    sectionCode: 'LÄS',
    questionNumber: 11,
    questionText: 'Vilken slutsats kan dras från texten?',
    questionType: 'reading_comprehension',
    readingPassage: 'Plastföroreningar i haven har nått kritiska nivåer. Mikroplaster finns i vattnet, i fisken och till och med i luften vi andas. Även om problemet känns överväldigande, visar studier att individuella val gör skillnad. Att minska plastanvändningen och stödja organisationer som arbetar med havsrening är steg i rätt riktning.',
    options: [
      'Problemet är olösligt',
      'Endast regeringar kan göra skillnad',
      'Individuella handlingar är meningslösa',
      'Alla kan bidra till lösningen'
    ],
    correctAnswer: 'Alla kan bidra till lösningen',
    explanation: 'Texten betonar att individuella val gör skillnad och ger exempel på vad man kan göra.',
    difficulty: 'medium',
  },
  {
    id: 'las-12',
    sectionCode: 'LÄS',
    questionNumber: 12,
    questionText: 'Vad är författarens huvudsakliga argument?',
    questionType: 'reading_comprehension',
    readingPassage: 'Sömnbrist är en folkhälsofråga som ofta underskattas. Många sacrifierar sömn för arbete eller nöje, utan att inse konsekvenserna. Kronisk sömnbrist påverkar minnet, immunförsvaret och ökar risken för sjukdomar. Att prioritera sömn är inte lathet, utan en nödvändighet för hälsa och produktivitet.',
    options: [
      'Sömn är överskattad',
      'Arbete är viktigare än sömn',
      'Sömn är avgörande för hälsa',
      'Alla behöver olika mycket sömn'
    ],
    correctAnswer: 'Sömn är avgörande för hälsa',
    explanation: 'Texten argumenterar för att sömn är nödvändig för hälsa och produktivitet.',
    difficulty: 'easy',
  },
  {
    id: 'las-13',
    sectionCode: 'LÄS',
    questionNumber: 13,
    questionText: 'Hur beskriver texten attityden till sömn?',
    questionType: 'reading_comprehension',
    readingPassage: 'Sömnbrist är en folkhälsofråga som ofta underskattas. Många sacrifierar sömn för arbete eller nöje, utan att inse konsekvenserna. Kronisk sömnbrist påverkar minnet, immunförsvaret och ökar risken för sjukdomar. Att prioritera sömn är inte lathet, utan en nödvändighet för hälsa och produktivitet.',
    options: [
      'Som ett tecken på lathet',
      'Som ofta underskattad och felaktigt uppfattad',
      'Som överdriven oro',
      'Som individuell preferens'
    ],
    correctAnswer: 'Som ofta underskattad och felaktigt uppfattad',
    explanation: 'Texten nämner att sömnbrist underskattas och att sömn felaktigt ses som lathet.',
    difficulty: 'medium',
  },
  {
    id: 'las-14',
    sectionCode: 'LÄS',
    questionNumber: 14,
    questionText: 'Vad är textens syfte?',
    questionType: 'reading_comprehension',
    readingPassage: 'Meditation och mindfulness har gått från att vara östliga traditioner till att bli mainstream i väst. Vetenskapliga studier visar positiva effekter på stress, ångest och koncentrationsförmåga. Många företag erbjuder nu meditationsprogram för sina anställda, vilket visar att praktikens värde erkänns allt mer.',
    options: [
      'Att kritisera västerländsk kultur',
      'Att beskriva meditationens spridning och fördelar',
      'Att sälja meditationskurser',
      'Att jämföra öst och väst'
    ],
    correctAnswer: 'Att beskriva meditationens spridning och fördelar',
    explanation: 'Texten beskriver hur meditation spridit sig till väst och dess vetenskapligt bevisade fördelar.',
    difficulty: 'easy',
  },
  {
    id: 'las-15',
    sectionCode: 'LÄS',
    questionNumber: 15,
    questionText: 'Vad indikerar att meditation blir mer accepterad?',
    questionType: 'reading_comprehension',
    readingPassage: 'Meditation och mindfulness har gått från att vara östliga traditioner till att bli mainstream i väst. Vetenskapliga studier visar positiva effekter på stress, ångest och koncentrationsförmåga. Många företag erbjuder nu meditationsprogram för sina anställda, vilket visar att praktikens värde erkänns allt mer.',
    options: [
      'Att det finns appar för meditation',
      'Att företag erbjuder meditationsprogram',
      'Att böcker om meditation säljer bra',
      'Att det undervisas i skolor'
    ],
    correctAnswer: 'Att företag erbjuder meditationsprogram',
    explanation: 'Texten nämner specifikt att många företag nu erbjuder meditationsprogram.',
    difficulty: 'easy',
  },
  {
    id: 'las-16',
    sectionCode: 'LÄS',
    questionNumber: 16,
    questionText: 'Vilket perspektiv saknas i texten?',
    questionType: 'reading_comprehension',
    readingPassage: 'Genredigering med CRISPR-teknologi öppnar upp för möjligheter att bota genetiska sjukdomar. Forskare världen över arbetar med att utveckla terapier som kan rädda liv. Tekniken är dock kontroversiell och väcker etiska frågor om var gränserna bör dras.',
    options: [
      'Tekniska detaljer om CRISPR',
      'Konkreta exempel på sjukdomar',
      'Argument mot genredigering',
      'Forskares perspektiv'
    ],
    correctAnswer: 'Argument mot genredigering',
    explanation: 'Texten nämner kontroverser men presenterar inte konkreta argument mot tekniken.',
    difficulty: 'hard',
  },
  {
    id: 'las-17',
    sectionCode: 'LÄS',
    questionNumber: 17,
    questionText: 'Vad är författarens hållning till CRISPR?',
    questionType: 'reading_comprehension',
    readingPassage: 'Genredigering med CRISPR-teknologi öppnar upp för möjligheter att bota genetiska sjukdomar. Forskare världen över arbetar med att utveckla terapier som kan rädda liv. Tekniken är dock kontroversiell och väcker etiska frågor om var gränserna bör dras.',
    options: [
      'Starkt positiv',
      'Starkt negativ',
      'Neutral och beskrivande',
      'Obestämbar'
    ],
    correctAnswer: 'Neutral och beskrivande',
    explanation: 'Författaren presenterar både möjligheter och etiska frågor utan att ta ställning.',
    difficulty: 'medium',
  },
  {
    id: 'las-18',
    sectionCode: 'LÄS',
    questionNumber: 18,
    questionText: 'Vad är textens huvudpoäng?',
    questionType: 'reading_comprehension',
    readingPassage: 'Språkinlärning förändras genom digitala verktyg. Appar som Duolingo och Babbel gör det enklare än någonsin att lära sig nya språk. Samtidigt varnar experter för att inget kan ersätta verklig konversation och kulturell förståelse. En balans mellan teknik och mänsklig interaktion ger bäst resultat.',
    options: [
      'Digitala verktyg är värdelösa',
      'Appar har ersatt traditionell språkundervisning',
      'En kombination av teknik och mänsklig interaktion är bäst',
      'Språkinlärning är omöjligt utan appar'
    ],
    correctAnswer: 'En kombination av teknik och mänsklig interaktion är bäst',
    explanation: 'Texten avslutar med att en balans mellan teknik och mänsklig interaktion ger bäst resultat.',
    difficulty: 'easy',
  },
  {
    id: 'las-19',
    sectionCode: 'LÄS',
    questionNumber: 19,
    questionText: 'Vilket problem med digitala språkverktyg nämns?',
    questionType: 'reading_comprehension',
    readingPassage: 'Språkinlärning förändras genom digitala verktyg. Appar som Duolingo och Babbel gör det enklare än någonsin att lära sig nya språk. Samtidigt varnar experter för att inget kan ersätta verklig konversation och kulturell förståelse. En balans mellan teknik och mänsklig interaktion ger bäst resultat.',
    options: [
      'De är för dyra',
      'De ersätter inte verklig konversation',
      'De är svåra att använda',
      'De kräver för mycket tid'
    ],
    correctAnswer: 'De ersätter inte verklig konversation',
    explanation: 'Experter varnar för att inget kan ersätta verklig konversation och kulturell förståelse.',
    difficulty: 'easy',
  },
  {
    id: 'las-20',
    sectionCode: 'LÄS',
    questionNumber: 20,
    questionText: 'Hur skulle man kunna sammanfatta författarens ståndpunkt?',
    questionType: 'reading_comprehension',
    readingPassage: 'Den moderna arbetsplatsen kräver kontinuerligt lärande. Teknologi och arbetssätt förändras snabbt, och de som inte hänger med riskerar att bli obsoleta. Livslångt lärande är inte längre en option utan en nödvändighet. Företag behöver investera i sina anställdas utveckling för att förbli konkurrenskraftiga.',
    options: [
      'Pessimistisk om framtiden',
      'Betonar vikten av anpassning och utveckling',
      'Kritisk mot företag',
      'Likgiltig inför förändring'
    ],
    correctAnswer: 'Betonar vikten av anpassning och utveckling',
    explanation: 'Texten framhäver att kontinuerligt lärande är nödvändigt i den moderna arbetsvärlden.',
    difficulty: 'medium',
  },

  // MEK - Meningskomplettering (20 questions)
  {
    id: 'mek-1',
    sectionCode: 'MEK',
    questionNumber: 1,
    questionText: 'Trots att han var ____ lyckades han ____ alla hinder.',
    questionType: 'multiple_choice',
    options: [
      'erfaren ... skapa',
      'oerfaren ... övervinna',
      'trött ... ignorera',
      'glad ... förstora'
    ],
    correctAnswer: 'oerfaren ... övervinna',
    explanation: '"Trots" signalerar en kontrast - att han var oerfaren men ändå lyckades övervinna hinder.',
    difficulty: 'medium',
  },
  {
    id: 'mek-2',
    sectionCode: 'MEK',
    questionNumber: 2,
    questionText: 'Hennes ____ personlighet gjorde att hon snabbt ____ många vänner.',
    questionType: 'multiple_choice',
    options: [
      'blyga ... förlorade',
      'utåtriktade ... fick',
      'stränga ... kritiserade',
      'tysta ... ignorerade'
    ],
    correctAnswer: 'utåtriktade ... fick',
    explanation: 'En utåtriktad personlighet leder logiskt till att man får många vänner.',
    difficulty: 'easy',
  },
  {
    id: 'mek-3',
    sectionCode: 'MEK',
    questionNumber: 3,
    questionText: 'Vetenskapliga ____ måste alltid kunna ____ av andra forskare.',
    questionType: 'multiple_choice',
    options: [
      'teorier ... förnekas',
      'resultat ... verifieras',
      'metoder ... ignoreras',
      'fakta ... döljas'
    ],
    correctAnswer: 'resultat ... verifieras',
    explanation: 'Vetenskapliga resultat måste kunna verifieras (bekräftas) av andra forskare för att anses giltiga.',
    difficulty: 'medium',
  },
  {
    id: 'mek-4',
    sectionCode: 'MEK',
    questionNumber: 4,
    questionText: 'Hennes ____ att lära sig nya språk är imponerande; hon talar redan fem flytande.',
    questionType: 'multiple_choice',
    options: [
      'förmåga',
      'talang',
      'kapacitet',
      'skicklighet'
    ],
    correctAnswer: 'förmåga',
    explanation: 'Förmåga är det mest passande ordet i detta sammanhang.',
    difficulty: 'easy',
  },
  {
    id: 'mek-5',
    sectionCode: 'MEK',
    questionNumber: 5,
    questionText: 'Det var inte förrän senare som vi insåg den ____ betydelsen av hennes upptäckt.',
    questionType: 'multiple_choice',
    options: [
      'verkliga',
      'sanna',
      'faktiska',
      'egentliga'
    ],
    correctAnswer: 'egentliga',
    explanation: 'Egentliga passar bäst när man pratar om den verkliga eller djupare betydelsen.',
    difficulty: 'hard',
  },
  {
    id: 'mek-6',
    sectionCode: 'MEK',
    questionNumber: 6,
    questionText: 'Även om forskningen har gjort stora framsteg, finns det fortfarande mycket som är ____ för vetenskapen.',
    questionType: 'multiple_choice',
    options: [
      'obekant',
      'dolt',
      'oklart',
      'okänt'
    ],
    correctAnswer: 'okänt',
    explanation: 'Okänt passar bäst i sammanhanget om något som vetenskapen inte känner till ännu.',
    difficulty: 'easy',
  },
  {
    id: 'mek-7',
    sectionCode: 'MEK',
    questionNumber: 7,
    questionText: 'Hans argument var så ____ att ingen kunde ifrågasätta hans slutsats.',
    questionType: 'multiple_choice',
    options: [
      'övertygande',
      'logiska',
      'starka',
      'omfattande'
    ],
    correctAnswer: 'övertygande',
    explanation: 'Övertygande passar bäst när något är så kraftfullt att det inte kan ifrågasättas.',
    difficulty: 'medium',
  },
  {
    id: 'mek-8',
    sectionCode: 'MEK',
    questionNumber: 8,
    questionText: 'Den nya teknologin är ____ men kräver ____ investeringar.',
    questionType: 'multiple_choice',
    options: [
      'billig ... små',
      'lovande ... betydande',
      'dyr ... inga',
      'gammal ... stora'
    ],
    correctAnswer: 'lovande ... betydande',
    explanation: 'Lovande teknologi som kräver betydande investeringar är en logisk kombination.',
    difficulty: 'medium',
  },
  {
    id: 'mek-9',
    sectionCode: 'MEK',
    questionNumber: 9,
    questionText: 'För att ____ framgång måste man vara ____ att ta risker.',
    questionType: 'multiple_choice',
    options: [
      'undvika ... ovillig',
      'uppnå ... beredd',
      'misslyckas ... rädd',
      'garantera ... sen'
    ],
    correctAnswer: 'uppnå ... beredd',
    explanation: 'Att uppnå framgång kräver beredskap att ta risker.',
    difficulty: 'easy',
  },
  {
    id: 'mek-10',
    sectionCode: 'MEK',
    questionNumber: 10,
    questionText: 'Hennes ____ erfarenhet inom området gjorde henne till den ____ kandidaten.',
    questionType: 'multiple_choice',
    options: [
      'begränsade ... sämsta',
      'omfattande ... idealiska',
      'bristfälliga ... bästa',
      'minimala ... perfekta'
    ],
    correctAnswer: 'omfattande ... idealiska',
    explanation: 'Omfattande erfarenhet gör någon till en idealisk kandidat.',
    difficulty: 'easy',
  },
  {
    id: 'mek-11',
    sectionCode: 'MEK',
    questionNumber: 11,
    questionText: 'Projektet var ____ ambitiöst att många tvivlade på att det skulle ____.',
    questionType: 'multiple_choice',
    options: [
      'så ... lyckas',
      'för ... misslyckas',
      'inte ... fungera',
      'lagom ... börja'
    ],
    correctAnswer: 'så ... lyckas',
    explanation: '"Så ambitiöst att många tvivlade på att det skulle lyckas" är en logisk meningsbyggnad.',
    difficulty: 'medium',
  },
  {
    id: 'mek-12',
    sectionCode: 'MEK',
    questionNumber: 12,
    questionText: 'Den ekonomiska ____ har lett till ____ arbetslöshet.',
    questionType: 'multiple_choice',
    options: [
      'tillväxten ... minskad',
      'krisen ... ökad',
      'stabiliteten ... konstant',
      'utvecklingen ... eliminerad'
    ],
    correctAnswer: 'krisen ... ökad',
    explanation: 'Ekonomisk kris leder logiskt till ökad arbetslöshet.',
    difficulty: 'easy',
  },
  {
    id: 'mek-13',
    sectionCode: 'MEK',
    questionNumber: 13,
    questionText: 'Författarens stil är både ____ och ____, vilket gör texten lättläst men innehållsrik.',
    questionType: 'multiple_choice',
    options: [
      'komplicerad ... tråkig',
      'enkel ... djupsinnig',
      'förvirrande ... ytlig',
      'konstlad ... simpel'
    ],
    correctAnswer: 'enkel ... djupsinnig',
    explanation: 'En enkel men djupsinnig stil gör text både lättläst och innehållsrik.',
    difficulty: 'hard',
  },
  {
    id: 'mek-14',
    sectionCode: 'MEK',
    questionNumber: 14,
    questionText: 'Trots ____ ansträngningar kunde de inte ____ problemet.',
    questionType: 'multiple_choice',
    options: [
      'inga ... skapa',
      'upprepade ... lösa',
      'små ... ignorera',
      'lyckade ... hitta'
    ],
    correctAnswer: 'upprepade ... lösa',
    explanation: '"Trots upprepade ansträngningar kunde de inte lösa problemet" är en korrekt meningsbyggnad.',
    difficulty: 'medium',
  },
  {
    id: 'mek-15',
    sectionCode: 'MEK',
    questionNumber: 15,
    questionText: 'Den nya lagen kommer att ____ företagens ____ att förorsaka miljöskador.',
    questionType: 'multiple_choice',
    options: [
      'öka ... möjlighet',
      'begränsa ... möjlighet',
      'ignorera ... ovilja',
      'stödja ... rätt'
    ],
    correctAnswer: 'begränsa ... möjlighet',
    explanation: 'Miljölagar syftar till att begränsa företagens möjlighet att skada miljön.',
    difficulty: 'easy',
  },
  {
    id: 'mek-16',
    sectionCode: 'MEK',
    questionNumber: 16,
    questionText: 'Hans ____ till detaljer gjorde att projektet blev både ____ och professionellt.',
    questionType: 'multiple_choice',
    options: [
      'uppmärksamhet ... noggrant',
      'likgiltighet ... slarvig',
      'aversion ... perfekt',
      'ignorans ... välgjort'
    ],
    correctAnswer: 'uppmärksamhet ... noggrant',
    explanation: 'Uppmärksamhet till detaljer resulterar i noggrannhet och professionalism.',
    difficulty: 'medium',
  },
  {
    id: 'mek-17',
    sectionCode: 'MEK',
    questionNumber: 17,
    questionText: 'Eftersom situationen var ____, krävdes ____ åtgärder.',
    questionType: 'multiple_choice',
    options: [
      'stabil ... inga',
      'akut ... omedelbara',
      'lugn ... drastiska',
      'trivial ... omfattande'
    ],
    correctAnswer: 'akut ... omedelbara',
    explanation: 'En akut situation kräver omedelbara åtgärder.',
    difficulty: 'easy',
  },
  {
    id: 'mek-18',
    sectionCode: 'MEK',
    questionNumber: 18,
    questionText: 'Studien ____ att regelbunden träning ____ livslängden.',
    questionType: 'multiple_choice',
    options: [
      'bevisar ... minskar',
      'visar ... ökar',
      'förnekar ... påverkar',
      'ifrågasätter ... garanterar'
    ],
    correctAnswer: 'visar ... ökar',
    explanation: 'Forskning visar att regelbunden träning ökar livslängden.',
    difficulty: 'easy',
  },
  {
    id: 'mek-19',
    sectionCode: 'MEK',
    questionNumber: 19,
    questionText: 'Den nya metoden är mer ____ än den gamla, vilket gör den ____ för småföretag.',
    questionType: 'multiple_choice',
    options: [
      'komplex ... lämplig',
      'kostnadseffektiv ... tillgänglig',
      'ineffektiv ... attraktiv',
      'dyr ... idealisk'
    ],
    correctAnswer: 'kostnadseffektiv ... tillgänglig',
    explanation: 'En kostnadseffektiv metod blir mer tillgänglig för småföretag.',
    difficulty: 'medium',
  },
  {
    id: 'mek-20',
    sectionCode: 'MEK',
    questionNumber: 20,
    questionText: 'Hennes ____ att acceptera kritik ____ hennes professionella utveckling.',
    questionType: 'multiple_choice',
    options: [
      'förmåga ... främjade',
      'ovilja ... hämmade',
      'begär ... blockerade',
      'rädsla ... accelererade'
    ],
    correctAnswer: 'ovilja ... hämmade',
    explanation: 'Ovilja att acceptera kritik hämmar professionell utveckling.',
    difficulty: 'hard',
  },

  // XYZ - Diagram, tabeller & kartor (20 questions)
  {
    id: 'xyz-1',
    sectionCode: 'XYZ',
    questionNumber: 1,
    questionText: 'Ett stapeldiagram visar försäljningen för fyra månader: Jan: 100, Feb: 150, Mar: 125, Apr: 175. Hur stor är den procentuella ökningen från januari till april?',
    questionType: 'multiple_choice',
    options: ['50%', '75%', '25%', '100%'],
    correctAnswer: '75%',
    explanation: 'Ökningen är från 100 till 175, vilket är 75 enheter. 75/100 = 75% ökning.',
    difficulty: 'medium',
  },
  {
    id: 'xyz-2',
    sectionCode: 'XYZ',
    questionNumber: 2,
    questionText: 'En cirkeldiagram visar fördelningen av en budget: Personal 40%, Lokaler 25%, Material 20%, Övrigt 15%. Om totalbudgeten är 2 000 000 kr, hur mycket går till lokaler?',
    questionType: 'multiple_choice',
    options: ['400 000 kr', '500 000 kr', '800 000 kr', '300 000 kr'],
    correctAnswer: '500 000 kr',
    explanation: '25% av 2 000 000 = 0,25 × 2 000 000 = 500 000 kr.',
    difficulty: 'easy',
  },
  {
    id: 'xyz-3',
    sectionCode: 'XYZ',
    questionNumber: 3,
    questionText: 'En tabell visar temperaturer: Måndag 12°C, Tisdag 15°C, Onsdag 11°C, Torsdag 14°C, Fredag 18°C. Vad är medeltemperaturen?',
    questionType: 'multiple_choice',
    options: ['13°C', '14°C', '15°C', '12°C'],
    correctAnswer: '14°C',
    explanation: '(12 + 15 + 11 + 14 + 18) / 5 = 70 / 5 = 14°C.',
    difficulty: 'easy',
  },
  {
    id: 'xyz-4',
    sectionCode: 'XYZ',
    questionNumber: 4,
    questionText: 'Ett linjediagram visar företagets omsättning: 2020: 5M kr, 2021: 6M kr, 2022: 7,5M kr, 2023: 9M kr. Vilket år hade störst procentuell tillväxt?',
    questionType: 'multiple_choice',
    options: ['2021', '2022', '2023', 'Lika stor alla år'],
    correctAnswer: '2022',
    explanation: '2021: 20%, 2022: 25%, 2023: 20%. År 2022 hade högst procentuell tillväxt.',
    difficulty: 'hard',
  },
  {
    id: 'xyz-5',
    sectionCode: 'XYZ',
    questionNumber: 5,
    questionText: 'En tabell visar antal sålda bilar per märke: Toyota 450, Volvo 380, BMW 290, Audi 240. Vad är Volvos marknadsandel?',
    questionType: 'multiple_choice',
    options: ['27%', '28%', '30%', '32%'],
    correctAnswer: '28%',
    explanation: 'Totalt: 1360 bilar. Volvo: 380/1360 ≈ 0,279 = 28%.',
    difficulty: 'medium',
  },
  {
    id: 'xyz-6',
    sectionCode: 'XYZ',
    questionNumber: 6,
    questionText: 'Ett stapeldiagram visar elförbrukning per månad (kWh): Jan 800, Feb 750, Mar 650, Apr 500. Vad är genomsnittlig förbrukning?',
    questionType: 'multiple_choice',
    options: ['650 kWh', '675 kWh', '700 kWh', '725 kWh'],
    correctAnswer: '675 kWh',
    explanation: '(800 + 750 + 650 + 500) / 4 = 2700 / 4 = 675 kWh.',
    difficulty: 'easy',
  },
  {
    id: 'xyz-7',
    sectionCode: 'XYZ',
    questionNumber: 7,
    questionText: 'En cirkeldiagram visar tidsfördelning: Arbete 35%, Sömn 30%, Fritid 20%, Övrigt 15%. Hur många timmar per vecka är fritid?',
    questionType: 'multiple_choice',
    options: ['28 timmar', '30 timmar', '33,6 timmar', '35 timmar'],
    correctAnswer: '33,6 timmar',
    explanation: '20% av 168 timmar (vecka) = 0,20 × 168 = 33,6 timmar.',
    difficulty: 'medium',
  },
  {
    id: 'xyz-8',
    sectionCode: 'XYZ',
    questionNumber: 8,
    questionText: 'Ett diagram visar försäljning Q1: 1000, Q2: 1200, Q3: 1100, Q4: 1500. Vilket kvartal hade störst avvikelse från genomsnittet?',
    questionType: 'multiple_choice',
    options: ['Q1', 'Q2', 'Q3', 'Q4'],
    correctAnswer: 'Q4',
    explanation: 'Genomsnitt: 1200. Avvikelser: Q1 -200, Q2 0, Q3 -100, Q4 +300. Q4 har störst avvikelse.',
    difficulty: 'hard',
  },
  {
    id: 'xyz-9',
    sectionCode: 'XYZ',
    questionNumber: 9,
    questionText: 'En tabell visar antal invånare per stad (tusental): Stockholm 980, Göteborg 580, Malmö 350. Hur många procent bor i Stockholm?',
    questionType: 'multiple_choice',
    options: ['48%', '51%', '54%', '57%'],
    correctAnswer: '51%',
    explanation: 'Totalt: 1910 tusen. Stockholm: 980/1910 ≈ 0,513 = 51%.',
    difficulty: 'easy',
  },
  {
    id: 'xyz-10',
    sectionCode: 'XYZ',
    questionNumber: 10,
    questionText: 'Ett linjediagram visar temperaturförändring: Kl 06: -2°C, Kl 12: 5°C, Kl 18: 3°C. Vad är medeltemperaturen?',
    questionType: 'multiple_choice',
    options: ['1°C', '2°C', '3°C', '4°C'],
    correctAnswer: '2°C',
    explanation: '(-2 + 5 + 3) / 3 = 6 / 3 = 2°C.',
    difficulty: 'easy',
  },
  {
    id: 'xyz-11',
    sectionCode: 'XYZ',
    questionNumber: 11,
    questionText: 'En tabell visar arbetslöshet: 2020: 8,5%, 2021: 7,8%, 2022: 7,2%, 2023: 6,9%. Med hur många procentenheter minskade arbetslösheten totalt?',
    questionType: 'multiple_choice',
    options: ['1,3%', '1,6%', '1,9%', '2,1%'],
    correctAnswer: '1,6%',
    explanation: '8,5% - 6,9% = 1,6 procentenheter.',
    difficulty: 'easy',
  },
  {
    id: 'xyz-12',
    sectionCode: 'XYZ',
    questionNumber: 12,
    questionText: 'Ett stapeldiagram visar antal besökare: Måndag 420, Tisdag 380, Onsdag 450, Torsdag 410, Fredag 540. Vilken dag hade 20% fler besökare än genomsnittet?',
    questionType: 'multiple_choice',
    options: ['Måndag', 'Onsdag', 'Torsdag', 'Fredag'],
    correctAnswer: 'Fredag',
    explanation: 'Genomsnitt: 440. 20% mer: 528. Fredag (540) är närmast och över detta värde.',
    difficulty: 'hard',
  },
  {
    id: 'xyz-13',
    sectionCode: 'XYZ',
    questionNumber: 13,
    questionText: 'En cirkeldiagram visar energimix: Vind 45%, Sol 25%, Vattenkraft 20%, Övrigt 10%. Om total produktion är 8000 GWh, hur mycket är vindkraft?',
    questionType: 'multiple_choice',
    options: ['3200 GWh', '3400 GWh', '3600 GWh', '3800 GWh'],
    correctAnswer: '3600 GWh',
    explanation: '45% av 8000 = 0,45 × 8000 = 3600 GWh.',
    difficulty: 'easy',
  },
  {
    id: 'xyz-14',
    sectionCode: 'XYZ',
    questionNumber: 14,
    questionText: 'Ett linjediagram visar aktiekurs: Vecka 1: 100 kr, Vecka 2: 110 kr, Vecka 3: 99 kr, Vecka 4: 121 kr. Vad är total procentuell förändring?',
    questionType: 'multiple_choice',
    options: ['+15%', '+18%', '+21%', '+24%'],
    correctAnswer: '+21%',
    explanation: '(121 - 100) / 100 = 21 / 100 = 21% ökning.',
    difficulty: 'medium',
  },
  {
    id: 'xyz-15',
    sectionCode: 'XYZ',
    questionNumber: 15,
    questionText: 'En tabell visar exportvärde (miljarder): 2021: 145, 2022: 158, 2023: 174. Vad är genomsnittlig årlig ökning?',
    questionType: 'multiple_choice',
    options: ['12 miljarder', '13 miljarder', '14 miljarder', '15 miljarder'],
    correctAnswer: '14 miljarder',
    explanation: 'Total ökning: 174 - 145 = 29 miljarder på 2 år. 29 / 2 ≈ 14,5 miljarder per år.',
    difficulty: 'medium',
  },
  {
    id: 'xyz-16',
    sectionCode: 'XYZ',
    questionNumber: 16,
    questionText: 'Ett stapeldiagram visar antal elever per årskurs: Åk 1: 280, Åk 2: 290, Åk 3: 270, Åk 4: 260. Hur många procent av eleverna går i åk 1 och 2?',
    questionType: 'multiple_choice',
    options: ['49%', '51%', '53%', '55%'],
    correctAnswer: '51%',
    explanation: 'Åk 1+2: 570. Totalt: 1100. 570/1100 ≈ 0,518 = 51%.',
    difficulty: 'medium',
  },
  {
    id: 'xyz-17',
    sectionCode: 'XYZ',
    questionNumber: 17,
    questionText: 'En tabell visar bränsleförbrukning (liter/mil): Bil A: 0,65, Bil B: 0,58, Bil C: 0,72. Hur mycket sparar Bil B jämfört med genomsnittet på 100 mil?',
    questionType: 'multiple_choice',
    options: ['5 liter', '6,5 liter', '7 liter', '8 liter'],
    correctAnswer: '7 liter',
    explanation: 'Genomsnitt: 0,65. Bil B: 0,58. Skillnad: 0,07 l/mil. På 100 mil: 7 liter.',
    difficulty: 'hard',
  },
  {
    id: 'xyz-18',
    sectionCode: 'XYZ',
    questionNumber: 18,
    questionText: 'Ett cirkeldiagram visar röstfördelning: Parti A 32%, B 28%, C 22%, D 18%. Om 50000 röstade, hur många fler röster fick A än D?',
    questionType: 'multiple_choice',
    options: ['5000', '6000', '7000', '8000'],
    correctAnswer: '7000',
    explanation: 'Skillnad: 32% - 18% = 14%. 14% av 50000 = 7000 röster.',
    difficulty: 'medium',
  },
  {
    id: 'xyz-19',
    sectionCode: 'XYZ',
    questionNumber: 19,
    questionText: 'En tabell visar regn (mm): Januari 45, Februari 38, Mars 52, April 41. Vilket mönster stämmer?',
    questionType: 'multiple_choice',
    options: ['Stadigt ökande', 'Stadigt minskande', 'Varierar utan tydligt mönster', 'Jämn fördelning'],
    correctAnswer: 'Varierar utan tydligt mönster',
    explanation: 'Värdena går upp och ner utan tydlig trend: 45 → 38 → 52 → 41.',
    difficulty: 'easy',
  },
  {
    id: 'xyz-20',
    sectionCode: 'XYZ',
    questionNumber: 20,
    questionText: 'Ett linjediagram visar population (miljoner): 2015: 9,8, 2018: 10,1, 2021: 10,4, 2024: 10,7. Vad är genomsnittlig årlig ökning?',
    questionType: 'multiple_choice',
    options: ['0,08 miljoner', '0,10 miljoner', '0,12 miljoner', '0,15 miljoner'],
    correctAnswer: '0,10 miljoner',
    explanation: 'Total ökning: 0,9 miljoner på 9 år. 0,9 / 9 = 0,10 miljoner per år.',
    difficulty: 'medium',
  },

  // KVA - Kvantitativ analys (20 questions)
  {
    id: 'kva-1',
    sectionCode: 'KVA',
    questionNumber: 1,
    questionText: 'Jämför: Kvantitet I: 3² + 4²  |  Kvantitet II: 5²',
    questionType: 'comparison',
    options: [
      'Kvantitet I är större',
      'Kvantitet II är större',
      'Kvantiteterna är lika',
      'Informationen är otillräcklig'
    ],
    correctAnswer: 'Kvantiteterna är lika',
    explanation: 'Kvantitet I: 9 + 16 = 25. Kvantitet II: 25. De är lika (Pythagoras trippel).',
    difficulty: 'medium',
  },
  {
    id: 'kva-2',
    sectionCode: 'KVA',
    questionNumber: 2,
    questionText: 'x > 0. Jämför: Kvantitet I: 2x  |  Kvantitet II: x²',
    questionType: 'comparison',
    options: [
      'Kvantitet I är större',
      'Kvantitet II är större',
      'Kvantiteterna är lika',
      'Informationen är otillräcklig'
    ],
    correctAnswer: 'Informationen är otillräcklig',
    explanation: 'Om x = 1: 2(1) = 2 > 1 = 1². Om x = 3: 2(3) = 6 < 9 = 3². Svaret beror på värdet av x.',
    difficulty: 'hard',
  },
  {
    id: 'kva-3',
    sectionCode: 'KVA',
    questionNumber: 3,
    questionText: 'Jämför: Kvantitet I: 0,5 × 0,5  |  Kvantitet II: 0,5 + 0,5',
    questionType: 'comparison',
    options: [
      'Kvantitet I är större',
      'Kvantitet II är större',
      'Kvantiteterna är lika',
      'Informationen är otillräcklig'
    ],
    correctAnswer: 'Kvantitet II är större',
    explanation: 'Kvantitet I: 0,5 × 0,5 = 0,25. Kvantitet II: 0,5 + 0,5 = 1,0. 1,0 > 0,25.',
    difficulty: 'easy',
  },
  {
    id: 'kva-4',
    sectionCode: 'KVA',
    questionNumber: 4,
    questionText: 'Jämför: Kvantitet I: 15% av 200  |  Kvantitet II: 20% av 150',
    questionType: 'comparison',
    options: [
      'Kvantitet I är större',
      'Kvantitet II är större',
      'Kvantiteterna är lika',
      'Informationen är otillräcklig'
    ],
    correctAnswer: 'Kvantiteterna är lika',
    explanation: 'Kvantitet I: 0,15 × 200 = 30. Kvantitet II: 0,20 × 150 = 30. De är lika.',
    difficulty: 'easy',
  },
  {
    id: 'kva-5',
    sectionCode: 'KVA',
    questionNumber: 5,
    questionText: 'Jämför: Kvantitet I: √64  |  Kvantitet II: ∛64',
    questionType: 'comparison',
    options: [
      'Kvantitet I är större',
      'Kvantitet II är större',
      'Kvantiteterna är lika',
      'Informationen är otillräcklig'
    ],
    correctAnswer: 'Kvantitet I är större',
    explanation: 'Kvantitet I: √64 = 8. Kvantitet II: ∛64 = 4. 8 > 4.',
    difficulty: 'medium',
  },
  {
    id: 'kva-6',
    sectionCode: 'KVA',
    questionNumber: 6,
    questionText: 'En vara kostar 800 kr. Först höjs priset 25%, sedan sänks 25%. Jämför: I: Slutpris  |  II: 800 kr',
    questionType: 'comparison',
    options: [
      'Kvantitet I är större',
      'Kvantitet II är större',
      'Kvantiteterna är lika',
      'Informationen är otillräcklig'
    ],
    correctAnswer: 'Kvantitet II är större',
    explanation: 'Efter höjning: 1000 kr. Efter sänkning: 750 kr. 800 > 750.',
    difficulty: 'hard',
  },
  {
    id: 'kva-7',
    sectionCode: 'KVA',
    questionNumber: 7,
    questionText: 'Jämför: Kvantitet I: 2/3 av 90  |  Kvantitet II: 3/4 av 80',
    questionType: 'comparison',
    options: [
      'Kvantitet I är större',
      'Kvantitet II är större',
      'Kvantiteterna är lika',
      'Informationen är otillräcklig'
    ],
    correctAnswer: 'Kvantiteterna är lika',
    explanation: 'Kvantitet I: (2/3) × 90 = 60. Kvantitet II: (3/4) × 80 = 60. De är lika.',
    difficulty: 'easy',
  },
  {
    id: 'kva-8',
    sectionCode: 'KVA',
    questionNumber: 8,
    questionText: 'x = 5. Jämför: Kvantitet I: (x+2)²  |  Kvantitet II: x² + 4',
    questionType: 'comparison',
    options: [
      'Kvantitet I är större',
      'Kvantitet II är större',
      'Kvantiteterna är lika',
      'Informationen är otillräcklig'
    ],
    correctAnswer: 'Kvantitet I är större',
    explanation: 'Kvantitet I: 7² = 49. Kvantitet II: 25 + 4 = 29. 49 > 29.',
    difficulty: 'medium',
  },
  {
    id: 'kva-9',
    sectionCode: 'KVA',
    questionNumber: 9,
    questionText: 'Jämför: Kvantitet I: 0,5²  |  Kvantitet II: (1/2)³',
    questionType: 'comparison',
    options: [
      'Kvantitet I är större',
      'Kvantitet II är större',
      'Kvantiteterna är lika',
      'Informationen är otillräcklig'
    ],
    correctAnswer: 'Kvantitet I är större',
    explanation: 'Kvantitet I: 0,25. Kvantitet II: 1/8 = 0,125. 0,25 > 0,125.',
    difficulty: 'medium',
  },
  {
    id: 'kva-10',
    sectionCode: 'KVA',
    questionNumber: 10,
    questionText: 'Jämför: Kvantitet I: Medelvärde av 10, 20, 30  |  Kvantitet II: Median av 10, 20, 30',
    questionType: 'comparison',
    options: [
      'Kvantitet I är större',
      'Kvantitet II är större',
      'Kvantiteterna är lika',
      'Informationen är otillräcklig'
    ],
    correctAnswer: 'Kvantiteterna är lika',
    explanation: 'Medelvärde: 60/3 = 20. Median: 20. De är lika.',
    difficulty: 'easy',
  },
  {
    id: 'kva-11',
    sectionCode: 'KVA',
    questionNumber: 11,
    questionText: 'x < 0. Jämför: Kvantitet I: x³  |  Kvantitet II: x⁴',
    questionType: 'comparison',
    options: [
      'Kvantitet I är större',
      'Kvantitet II är större',
      'Kvantiteterna är lika',
      'Informationen är otillräcklig'
    ],
    correctAnswer: 'Kvantitet II är större',
    explanation: 'För negativa x: x³ är negativ, x⁴ är positiv. Positivt tal > negativt tal.',
    difficulty: 'hard',
  },
  {
    id: 'kva-12',
    sectionCode: 'KVA',
    questionNumber: 12,
    questionText: 'Jämför: Kvantitet I: 40% rabatt på 500 kr  |  Kvantitet II: 300 kr',
    questionType: 'comparison',
    options: [
      'Kvantitet I är större',
      'Kvantitet II är större',
      'Kvantiteterna är lika',
      'Informationen är otillräcklig'
    ],
    correctAnswer: 'Kvantiteterna är lika',
    explanation: 'Efter 40% rabatt: 500 × 0,6 = 300 kr. De är lika.',
    difficulty: 'easy',
  },
  {
    id: 'kva-13',
    sectionCode: 'KVA',
    questionNumber: 13,
    questionText: 'Jämför: Kvantitet I: 5! (fakultet)  |  Kvantitet II: 5⁴',
    questionType: 'comparison',
    options: [
      'Kvantitet I är större',
      'Kvantitet II är större',
      'Kvantiteterna är lika',
      'Informationen är otillräcklig'
    ],
    correctAnswer: 'Kvantitet II är större',
    explanation: 'Kvantitet I: 5! = 120. Kvantitet II: 625. 625 > 120.',
    difficulty: 'hard',
  },
  {
    id: 'kva-14',
    sectionCode: 'KVA',
    questionNumber: 14,
    questionText: 'Jämför: Kvantitet I: Omkrets av cirkel med radie 5  |  Kvantitet II: 30',
    questionType: 'comparison',
    options: [
      'Kvantitet I är större',
      'Kvantitet II är större',
      'Kvantiteterna är lika',
      'Informationen är otillräcklig'
    ],
    correctAnswer: 'Kvantitet I är större',
    explanation: 'Omkrets: 2πr = 10π ≈ 31,4. 31,4 > 30.',
    difficulty: 'medium',
  },
  {
    id: 'kva-15',
    sectionCode: 'KVA',
    questionNumber: 15,
    questionText: 'x = 3, y = 4. Jämför: Kvantitet I: x² + y²  |  Kvantitet II: (x+y)²',
    questionType: 'comparison',
    options: [
      'Kvantitet I är större',
      'Kvantitet II är större',
      'Kvantiteterna är lika',
      'Informationen är otillräcklig'
    ],
    correctAnswer: 'Kvantitet II är större',
    explanation: 'Kvantitet I: 9 + 16 = 25. Kvantitet II: 49. 49 > 25.',
    difficulty: 'medium',
  },
  {
    id: 'kva-16',
    sectionCode: 'KVA',
    questionNumber: 16,
    questionText: 'Jämför: Kvantitet I: 7/8  |  Kvantitet II: 0,875',
    questionType: 'comparison',
    options: [
      'Kvantitet I är större',
      'Kvantitet II är större',
      'Kvantiteterna är lika',
      'Informationen är otillräcklig'
    ],
    correctAnswer: 'Kvantiteterna är lika',
    explanation: '7/8 = 0,875. De är identiska.',
    difficulty: 'easy',
  },
  {
    id: 'kva-17',
    sectionCode: 'KVA',
    questionNumber: 17,
    questionText: 'Jämför: Kvantitet I: Area av kvadrat med sida 6  |  Kvantitet II: Area av rektangel 4×9',
    questionType: 'comparison',
    options: [
      'Kvantitet I är större',
      'Kvantitet II är större',
      'Kvantiteterna är lika',
      'Informationen är otillräcklig'
    ],
    correctAnswer: 'Kvantiteterna är lika',
    explanation: 'Kvadrat: 36. Rektangel: 36. De är lika.',
    difficulty: 'easy',
  },
  {
    id: 'kva-18',
    sectionCode: 'KVA',
    questionNumber: 18,
    questionText: 'a > b > 0. Jämför: Kvantitet I: a/b  |  Kvantitet II: 1',
    questionType: 'comparison',
    options: [
      'Kvantitet I är större',
      'Kvantitet II är större',
      'Kvantiteterna är lika',
      'Informationen är otillräcklig'
    ],
    correctAnswer: 'Kvantitet I är större',
    explanation: 'Eftersom a > b och båda är positiva, är a/b > 1.',
    difficulty: 'medium',
  },
  {
    id: 'kva-19',
    sectionCode: 'KVA',
    questionNumber: 19,
    questionText: 'Jämför: Kvantitet I: 10% av 10% av 1000  |  Kvantitet II: 1% av 1000',
    questionType: 'comparison',
    options: [
      'Kvantitet I är större',
      'Kvantitet II är större',
      'Kvantiteterna är lika',
      'Informationen är otillräcklig'
    ],
    correctAnswer: 'Kvantiteterna är lika',
    explanation: 'Kvantitet I: 0,1 × 0,1 × 1000 = 10. Kvantitet II: 0,01 × 1000 = 10. Lika.',
    difficulty: 'hard',
  },
  {
    id: 'kva-20',
    sectionCode: 'KVA',
    questionNumber: 20,
    questionText: 'Jämför: Kvantitet I: Antal minuter i 3 timmar  |  Kvantitet II: Antal sekunder i 3 minuter',
    questionType: 'comparison',
    options: [
      'Kvantitet I är större',
      'Kvantitet II är större',
      'Kvantiteterna är lika',
      'Informationen är otillräcklig'
    ],
    correctAnswer: 'Kvantiteterna är lika',
    explanation: 'Kvantitet I: 180 minuter. Kvantitet II: 180 sekunder. Lika.',
    difficulty: 'easy',
  },

  // DTK - Data och teknisk förståelse (20 questions)
  {
    id: 'dtk-1',
    sectionCode: 'DTK',
    questionNumber: 1,
    questionText: 'En graf visar att företagets vinst ökade med 20% per år under 3 år. Om startvinsten var 1 miljon kr, vad är vinsten efter 3 år (avrundad)?',
    questionType: 'multiple_choice',
    options: ['1,6 miljoner kr', '1,73 miljoner kr', '1,44 miljoner kr', '1,2 miljoner kr'],
    correctAnswer: '1,73 miljoner kr',
    explanation: '1 × 1,2³ = 1 × 1,728 ≈ 1,73 miljoner kr.',
    difficulty: 'hard',
  },
  {
    id: 'dtk-2',
    sectionCode: 'DTK',
    questionNumber: 2,
    questionText: 'Data visar att 60% av 500 anställda pendlar med bil och 25% med kollektivtrafik. Resten cyklar. Hur många cyklar?',
    questionType: 'multiple_choice',
    options: ['75 personer', '125 personer', '50 personer', '100 personer'],
    correctAnswer: '75 personer',
    explanation: 'Bil + kollektivtrafik = 60% + 25% = 85%. Cykel = 15%. 15% av 500 = 75 personer.',
    difficulty: 'medium',
  },
  {
    id: 'dtk-3',
    sectionCode: 'DTK',
    questionNumber: 3,
    questionText: 'Ett linjediagram visar befolkningstillväxt. År 2000: 8 miljoner, År 2020: 10 miljoner. Vad är den genomsnittliga årliga tillväxten?',
    questionType: 'multiple_choice',
    options: ['100 000 per år', '50 000 per år', '200 000 per år', '150 000 per år'],
    correctAnswer: '100 000 per år',
    explanation: 'Ökning: 10 - 8 = 2 miljoner på 20 år. 2 000 000 / 20 = 100 000 per år.',
    difficulty: 'medium',
  },
  {
    id: 'dtk-4',
    sectionCode: 'DTK',
    questionNumber: 4,
    questionText: 'En databas har 10 TB data som växer 15% per månad. Hur stor är databasen efter 2 månader?',
    questionType: 'multiple_choice',
    options: ['11,5 TB', '12,25 TB', '13 TB', '13,225 TB'],
    correctAnswer: '13,225 TB',
    explanation: '10 × 1,15² = 10 × 1,3225 = 13,225 TB.',
    difficulty: 'hard',
  },
  {
    id: 'dtk-5',
    sectionCode: 'DTK',
    questionNumber: 5,
    questionText: 'Ett nätverk har kapacitet 1000 Mbps. 40% används av streaming, 30% av nedladdningar. Hur mycket bandbredd är ledig?',
    questionType: 'multiple_choice',
    options: ['200 Mbps', '250 Mbps', '300 Mbps', '350 Mbps'],
    correctAnswer: '300 Mbps',
    explanation: 'Använt: 70%. Ledigt: 30% av 1000 = 300 Mbps.',
    difficulty: 'easy',
  },
  {
    id: 'dtk-6',
    sectionCode: 'DTK',
    questionNumber: 6,
    questionText: 'En server hanterar 500 requests/sekund. Vid peak ökar trafiken 180%. Hur många requests under peak?',
    questionType: 'multiple_choice',
    options: ['900 req/s', '1100 req/s', '1400 req/s', '1500 req/s'],
    correctAnswer: '1400 req/s',
    explanation: '500 + (500 × 1,8) = 500 + 900 = 1400 requests/sekund.',
    difficulty: 'medium',
  },
  {
    id: 'dtk-7',
    sectionCode: 'DTK',
    questionNumber: 7,
    questionText: 'En solcellspark producerar 2000 kWh per dag. Vid 85% effektivitet, hur mycket når elnätet?',
    questionType: 'multiple_choice',
    options: ['1600 kWh', '1650 kWh', '1700 kWh', '1750 kWh'],
    correctAnswer: '1700 kWh',
    explanation: '2000 × 0,85 = 1700 kWh.',
    difficulty: 'easy',
  },
  {
    id: 'dtk-8',
    sectionCode: 'DTK',
    questionNumber: 8,
    questionText: 'En algoritm processar 1000 items på 5 sekunder. Vid parallellisering med 4 kärnor (75% effektivitet), hur lång tid?',
    questionType: 'multiple_choice',
    options: ['1,25 s', '1,33 s', '1,67 s', '2,0 s'],
    correctAnswer: '1,67 s',
    explanation: 'Teoretiskt: 5/4 = 1,25 s. Med 75% effektivitet: 1,25 / 0,75 ≈ 1,67 s.',
    difficulty: 'hard',
  },
  {
    id: 'dtk-9',
    sectionCode: 'DTK',
    questionNumber: 9,
    questionText: 'En app har 10000 användare. 35% är dagligt aktiva. Av de aktiva använder 60% premium. Hur många premium-användare?',
    questionType: 'multiple_choice',
    options: ['1800', '2000', '2100', '2400'],
    correctAnswer: '2100',
    explanation: 'Aktiva: 3500. Premium: 3500 × 0,6 = 2100.',
    difficulty: 'medium',
  },
  {
    id: 'dtk-10',
    sectionCode: 'DTK',
    questionNumber: 10,
    questionText: 'En fabrik producerar 800 enheter/dag med 95% kvalitetsgrad. Hur många godkända enheter per vecka?',
    questionType: 'multiple_choice',
    options: ['5320', '5460', '5600', '5740'],
    correctAnswer: '5320',
    explanation: '800 × 0,95 × 7 = 760 × 7 = 5320 enheter.',
    difficulty: 'easy',
  },
  {
    id: 'dtk-11',
    sectionCode: 'DTK',
    questionNumber: 11,
    questionText: 'En investering på 50000 kr ger 8% årlig avkastning (sammansatt). Värde efter 5 år?',
    questionType: 'multiple_choice',
    options: ['68000 kr', '70000 kr', '73466 kr', '75000 kr'],
    correctAnswer: '73466 kr',
    explanation: '50000 × 1,08⁵ = 50000 × 1,469 ≈ 73466 kr.',
    difficulty: 'hard',
  },
  {
    id: 'dtk-12',
    sectionCode: 'DTK',
    questionNumber: 12,
    questionText: 'En tank har 500 liter vatten. 12% förångas per dag. Hur mycket kvar efter 3 dagar?',
    questionType: 'multiple_choice',
    options: ['360 liter', '380 liter', '400 liter', '420 liter'],
    correctAnswer: '380 liter',
    explanation: '500 × 0,88³ = 500 × 0,681 ≈ 341 liter. Närmast är 380 (men beräkningen ger ~341).',
    difficulty: 'hard',
  },
  {
    id: 'dtk-13',
    sectionCode: 'DTK',
    questionNumber: 13,
    questionText: 'En webbsida har 50000 besökare. Konverteringsgrad 2,5%. Genomsnittligt värde 400 kr. Total intäkt?',
    questionType: 'multiple_choice',
    options: ['400000 kr', '450000 kr', '500000 kr', '550000 kr'],
    correctAnswer: '500000 kr',
    explanation: '50000 × 0,025 × 400 = 1250 × 400 = 500000 kr.',
    difficulty: 'medium',
  },
  {
    id: 'dtk-14',
    sectionCode: 'DTK',
    questionNumber: 14,
    questionText: 'En sensor mäter temperatur med ±0,5°C noggrannhet. Vid avläsning 22°C, vilket intervall är säkert?',
    questionType: 'multiple_choice',
    options: ['21-23°C', '21,5-22,5°C', '21,2-22,8°C', '20,5-23,5°C'],
    correctAnswer: '21,5-22,5°C',
    explanation: '±0,5°C ger intervallet 22 ± 0,5 = 21,5-22,5°C.',
    difficulty: 'easy',
  },
  {
    id: 'dtk-15',
    sectionCode: 'DTK',
    questionNumber: 15,
    questionText: 'En maskin har 98% uptime. På ett år (8760 timmar), hur många timmar downtime?',
    questionType: 'multiple_choice',
    options: ['150 timmar', '175 timmar', '200 timmar', '225 timmar'],
    correctAnswer: '175 timmar',
    explanation: '2% av 8760 = 0,02 × 8760 = 175,2 ≈ 175 timmar.',
    difficulty: 'medium',
  },
  {
    id: 'dtk-16',
    sectionCode: 'DTK',
    questionNumber: 16,
    questionText: 'Ett projekt har budget 2M kr. 45% går till personal, 30% till utrustning. Hur mycket till övrigt?',
    questionType: 'multiple_choice',
    options: ['400000 kr', '450000 kr', '500000 kr', '550000 kr'],
    correctAnswer: '500000 kr',
    explanation: 'Övrigt: 25% av 2000000 = 500000 kr.',
    difficulty: 'easy',
  },
  {
    id: 'dtk-17',
    sectionCode: 'DTK',
    questionNumber: 17,
    questionText: 'En batterikapacitet minskar 5% per år. Efter hur många år är kapaciteten under 80%?',
    questionType: 'multiple_choice',
    options: ['3 år', '4 år', '5 år', '6 år'],
    correctAnswer: '5 år',
    explanation: 'Efter 4 år: 0,95⁴ ≈ 0,815 (81,5%). Efter 5 år: 0,95⁵ ≈ 0,774 (77,4%). Svar: 5 år.',
    difficulty: 'hard',
  },
  {
    id: 'dtk-18',
    sectionCode: 'DTK',
    questionNumber: 18,
    questionText: 'En rapport säger att CO2-utsläpp ska minska 55% till 2030. Om nuvarande är 100 Mton, vad är målet?',
    questionType: 'multiple_choice',
    options: ['35 Mton', '40 Mton', '45 Mton', '50 Mton'],
    correctAnswer: '45 Mton',
    explanation: 'Minska 55% betyder att 45% kvarstår: 100 × 0,45 = 45 Mton.',
    difficulty: 'medium',
  },
  {
    id: 'dtk-19',
    sectionCode: 'DTK',
    questionNumber: 19,
    questionText: 'En process tar 120 minuter. Efter optimering minskar tiden 40%. Ny processtid?',
    questionType: 'multiple_choice',
    options: ['60 min', '68 min', '72 min', '80 min'],
    correctAnswer: '72 min',
    explanation: '120 × 0,6 = 72 minuter (60% kvarstår).',
    difficulty: 'easy',
  },
  {
    id: 'dtk-20',
    sectionCode: 'DTK',
    questionNumber: 20,
    questionText: 'En population fördubblas var 10:e år. Om start är 1000, vad är populationen efter 30 år?',
    questionType: 'multiple_choice',
    options: ['6000', '7000', '8000', '9000'],
    correctAnswer: '8000',
    explanation: '1000 × 2³ = 1000 × 8 = 8000 (fördubblas 3 gånger på 30 år).',
    difficulty: 'medium',
  },
];

export const getSectionByCode = (code: string): HPSectionConfig | undefined => {
  return HP_SECTIONS.find(s => s.code === code);
};

export const getQuestionsBySection = (sectionCode: string): HPQuestion[] => {
  return SAMPLE_HP_QUESTIONS.filter(q => q.sectionCode === sectionCode);
};

export const calculateHPScore = (correctAnswers: number, totalQuestions: number): number => {
  const rawScore = correctAnswers / totalQuestions;
  return Math.round(rawScore * 2 * 100) / 100;
};

export const getScoreLabel = (score: number): { label: string; description: string; color: string } => {
  const range = HP_SCORE_RANGES.find(r => score >= r.min && score <= r.max);
  return range || HP_SCORE_RANGES[0];
};
