// Massive collection of Högskoleprov questions - Over 360 questions total!
// This file contains multiple test versions (A, B, C) for each section

import { HPQuestion } from './hogskoleprovet';

export const ALL_HP_QUESTIONS: HPQuestion[] = [
  // =====================================================
  // ORD - ORDFÖRSTÅELSE (60 questions = 3 tests × 20)
  // =====================================================
  
  // TEST A - ORD (20 questions)
  {
    id: 'ord-a-1',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 1,
    questionText: 'Vad betyder ordet "pertinent"?',
    questionType: 'multiple_choice',
    options: ['Irrelevant', 'Relevant och träffande', 'Förvirrande', 'Motsägelsefull'],
    correctAnswer: 'Relevant och träffande',
    explanation: 'Pertinent betyder relevant, träffande eller som har direkt anknytning till saken.',
    difficulty: 'medium',
  },
  {
    id: 'ord-a-2',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 2,
    questionText: 'Vilket ord är en synonym till "efemär"?',
    questionType: 'multiple_choice',
    options: ['Evig', 'Kortvarig', 'Stark', 'Vacker'],
    correctAnswer: 'Kortvarig',
    explanation: 'Efemär betyder kortlivad eller flyktig, något som bara varar en kort tid.',
    difficulty: 'hard',
  },
  {
    id: 'ord-a-3',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 3,
    questionText: 'Vad betyder "pragmatisk"?',
    questionType: 'multiple_choice',
    options: ['Teoretisk', 'Praktisk och realistisk', 'Pessimistisk', 'Idealistisk'],
    correctAnswer: 'Praktisk och realistisk',
    explanation: 'Pragmatisk innebär att ha en praktisk, resultatinriktad inställning snarare än teoretisk.',
    difficulty: 'medium',
  },
  {
    id: 'ord-a-4',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 4,
    questionText: 'Vilket ord betyder "överdrivet detaljerad"?',
    questionType: 'multiple_choice',
    options: ['Koncis', 'Pedantisk', 'Vag', 'Ytlig'],
    correctAnswer: 'Pedantisk',
    explanation: 'Pedantisk beskriver någon som är överdrivet noggrann med detaljer och regler.',
    difficulty: 'medium',
  },
  {
    id: 'ord-a-5',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 5,
    questionText: 'Vad är en antonym till "konkret"?',
    questionType: 'multiple_choice',
    options: ['Abstrakt', 'Tydlig', 'Fast', 'Verklig'],
    correctAnswer: 'Abstrakt',
    explanation: 'Konkret betyder påtaglig och verklig, medan abstrakt är motsatsen - teoretisk och otydlig.',
    difficulty: 'easy',
  },
  {
    id: 'ord-a-6',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 6,
    questionText: 'Vad betyder "redundant"?',
    questionType: 'multiple_choice',
    options: ['Överflödig', 'Nödvändig', 'Komplex', 'Enkel'],
    correctAnswer: 'Överflödig',
    explanation: 'Redundant betyder överflödig eller onödig.',
    difficulty: 'hard',
  },
  {
    id: 'ord-a-7',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 7,
    questionText: 'Vilket ord betyder "motvillig"?',
    questionType: 'multiple_choice',
    options: ['Entusiastisk', 'Ovillig', 'Aktiv', 'Positiv'],
    correctAnswer: 'Ovillig',
    explanation: 'Motvillig betyder ovillig eller tveksam till något.',
    difficulty: 'easy',
  },
  {
    id: 'ord-a-8',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 8,
    questionText: 'Vad betyder "eloquent"?',
    questionType: 'multiple_choice',
    options: ['Tyst', 'Vältalig', 'Dum', 'Förvirrad'],
    correctAnswer: 'Vältalig',
    explanation: 'Eloquent betyder vältalig och uttrycksfull.',
    difficulty: 'medium',
  },
  {
    id: 'ord-a-9',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 9,
    questionText: 'Vilket ord är motsatsen till "benägen"?',
    questionType: 'multiple_choice',
    options: ['Villig', 'Motvillig', 'Öppen', 'Positiv'],
    correctAnswer: 'Motvillig',
    explanation: 'Benägen betyder böjd eller villig, medan motvillig är motsatsen.',
    difficulty: 'medium',
  },
  {
    id: 'ord-a-10',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 10,
    questionText: 'Vad betyder "paradox"?',
    questionType: 'multiple_choice',
    options: ['Självmotsägelse', 'Logisk följd', 'Enkel lösning', 'Tydligt svar'],
    correctAnswer: 'Självmotsägelse',
    explanation: 'Paradox betyder självmotsägelse eller något som verkar motsägelsefullt.',
    difficulty: 'hard',
  },
  {
    id: 'ord-a-11',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 11,
    questionText: 'Vilket ord betyder "ihållande och ihärdig"?',
    questionType: 'multiple_choice',
    options: ['Flyktig', 'Persistent', 'Tveksam', 'Ointresserad'],
    correctAnswer: 'Persistent',
    explanation: 'Persistent betyder ihållande, ihärdig och uthållig.',
    difficulty: 'medium',
  },
  {
    id: 'ord-a-12',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 12,
    questionText: 'Vad betyder "ambivalent"?',
    questionType: 'multiple_choice',
    options: ['Säker', 'Kluven', 'Bestämd', 'Entusiastisk'],
    correctAnswer: 'Kluven',
    explanation: 'Ambivalent betyder kluven eller att ha motstridiga känslor.',
    difficulty: 'hard',
  },
  {
    id: 'ord-a-13',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 13,
    questionText: 'Vilket ord betyder "oförmögen att läsa och skriva"?',
    questionType: 'multiple_choice',
    options: ['Bildad', 'Analfabet', 'Lärd', 'Kulturell'],
    correctAnswer: 'Analfabet',
    explanation: 'Analfabet betyder oförmögen att läsa och skriva.',
    difficulty: 'easy',
  },
  {
    id: 'ord-a-14',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 14,
    questionText: 'Vad betyder "altruistisk"?',
    questionType: 'multiple_choice',
    options: ['Självisk', 'Osjälvisk', 'Krävande', 'Girig'],
    correctAnswer: 'Osjälvisk',
    explanation: 'Altruistisk betyder osjälvisk och hjälpsam mot andra.',
    difficulty: 'medium',
  },
  {
    id: 'ord-a-15',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 15,
    questionText: 'Vilket ord betyder "tillfällig lösning"?',
    questionType: 'multiple_choice',
    options: ['Permanent', 'Provisorisk', 'Definitiv', 'Evig'],
    correctAnswer: 'Provisorisk',
    explanation: 'Provisorisk betyder tillfällig eller inte permanent.',
    difficulty: 'medium',
  },
  {
    id: 'ord-a-16',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 16,
    questionText: 'Vad betyder "konventionell"?',
    questionType: 'multiple_choice',
    options: ['Nyskapande', 'Traditionell', 'Unik', 'Modern'],
    correctAnswer: 'Traditionell',
    explanation: 'Konventionell betyder traditionell eller som följer normen.',
    difficulty: 'easy',
  },
  {
    id: 'ord-a-17',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 17,
    questionText: 'Vilket ord betyder "känslomässigt oberörd"?',
    questionType: 'multiple_choice',
    options: ['Känslig', 'Apatisk', 'Engagerad', 'Passionerad'],
    correctAnswer: 'Apatisk',
    explanation: 'Apatisk betyder känslomässigt oberörd eller likgiltig.',
    difficulty: 'hard',
  },
  {
    id: 'ord-a-18',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 18,
    questionText: 'Vad betyder "subtil"?',
    questionType: 'multiple_choice',
    options: ['Uppenbar', 'Förfinad', 'Grov', 'Tydlig'],
    correctAnswer: 'Förfinad',
    explanation: 'Subtil betyder förfinad, svårupptäckt eller diskret.',
    difficulty: 'hard',
  },
  {
    id: 'ord-a-19',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 19,
    questionText: 'Vilket ord betyder "mycket noga med detaljer"?',
    questionType: 'multiple_choice',
    options: ['Slarvig', 'Noggrann', 'Vårdslös', 'Likgiltig'],
    correctAnswer: 'Noggrann',
    explanation: 'Noggrann betyder att vara mycket noga med detaljer och kvalitet.',
    difficulty: 'easy',
  },
  {
    id: 'ord-a-20',
    sectionCode: 'ORD',
    testVersion: 'ord-a',
    questionNumber: 20,
    questionText: 'Vad betyder "empatisk"?',
    questionType: 'multiple_choice',
    options: ['Hänsynslös', 'Inlevelsefull', 'Självisk', 'Kall'],
    correctAnswer: 'Inlevelsefull',
    explanation: 'Empatisk betyder inlevelsefull och förmögen att förstå andras känslor.',
    difficulty: 'easy',
  },

  // TEST B - ORD (20 nya frågor)
  {
    id: 'ord-b-1',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 1,
    questionText: 'Vad betyder "arbiträr"?',
    questionType: 'multiple_choice',
    options: ['Logisk', 'Godtycklig', 'Rättvis', 'Systematisk'],
    correctAnswer: 'Godtycklig',
    explanation: 'Arbiträr betyder godtycklig, utan tydlig grund eller regel.',
    difficulty: 'medium',
  },
  {
    id: 'ord-b-2',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 2,
    questionText: 'Vilket ord betyder "som inte kan undvikas"?',
    questionType: 'multiple_choice',
    options: ['Oundviklig', 'Möjlig', 'Osannolik', 'Valfri'],
    correctAnswer: 'Oundviklig',
    explanation: 'Oundviklig betyder något som måste hända, som inte kan undvikas.',
    difficulty: 'easy',
  },
  {
    id: 'ord-b-3',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 3,
    questionText: 'Vad betyder "eloquens"?',
    questionType: 'multiple_choice',
    options: ['Tystnad', 'Vältalighet', 'Osäkerhet', 'Förvirring'],
    correctAnswer: 'Vältalighet',
    explanation: 'Eloquens betyder vältalighet, förmågan att tala väl och övertygande.',
    difficulty: 'medium',
  },
  {
    id: 'ord-b-4',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 4,
    questionText: 'Vilket ord är en synonym till "dogmatisk"?',
    questionType: 'multiple_choice',
    options: ['Flexibel', 'Öppensinnad', 'Rigid', 'Tveksam'],
    correctAnswer: 'Rigid',
    explanation: 'Dogmatisk betyder rigid och oböjlig i sina åsikter.',
    difficulty: 'hard',
  },
  {
    id: 'ord-b-5',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 5,
    questionText: 'Vad betyder "konkav"?',
    questionType: 'multiple_choice',
    options: ['Inåtböjd', 'Utåtböjd', 'Platt', 'Spetsig'],
    correctAnswer: 'Inåtböjd',
    explanation: 'Konkav betyder inåtböjd (som en skål).',
    difficulty: 'medium',
  },
  {
    id: 'ord-b-6',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 6,
    questionText: 'Vilket ord betyder "frivillig frånvaro från mat"?',
    questionType: 'multiple_choice',
    options: ['Svält', 'Fasta', 'Diet', 'Hunger'],
    correctAnswer: 'Fasta',
    explanation: 'Fasta betyder att frivilligt avstå från mat under en viss period.',
    difficulty: 'easy',
  },
  {
    id: 'ord-b-7',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 7,
    questionText: 'Vad betyder "deteriorera"?',
    questionType: 'multiple_choice',
    options: ['Förbättras', 'Försämras', 'Förändras', 'Förstärkas'],
    correctAnswer: 'Försämras',
    explanation: 'Deteriorera betyder att försämras eller förfalla.',
    difficulty: 'hard',
  },
  {
    id: 'ord-b-8',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 8,
    questionText: 'Vilket ord betyder "kortfattad och kärnfull"?',
    questionType: 'multiple_choice',
    options: ['Utförlig', 'Koncis', 'Vag', 'Förvirrande'],
    correctAnswer: 'Koncis',
    explanation: 'Koncis betyder kortfattad och kärnfull i uttryckssätt.',
    difficulty: 'medium',
  },
  {
    id: 'ord-b-9',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 9,
    questionText: 'Vad är en antonym till "transparent"?',
    questionType: 'multiple_choice',
    options: ['Klar', 'Ogenomskinlig', 'Synlig', 'Tydlig'],
    correctAnswer: 'Ogenomskinlig',
    explanation: 'Transparent betyder genomskinlig, ogenomskinlig är motsatsen.',
    difficulty: 'easy',
  },
  {
    id: 'ord-b-10',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 10,
    questionText: 'Vad betyder "implicera"?',
    questionType: 'multiple_choice',
    options: ['Förklara tydligt', 'Antyda indirekt', 'Förneka', 'Ignorera'],
    correctAnswer: 'Antyda indirekt',
    explanation: 'Implicera betyder att antyda något indirekt eller innebära.',
    difficulty: 'medium',
  },
  {
    id: 'ord-b-11',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 11,
    questionText: 'Vilket ord betyder "överseende och förlåtande"?',
    questionType: 'multiple_choice',
    options: ['Hård', 'Mild', 'Sträng', 'Krävande'],
    correctAnswer: 'Mild',
    explanation: 'Mild betyder överseende, förlåtande och inte sträng.',
    difficulty: 'easy',
  },
  {
    id: 'ord-b-12',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 12,
    questionText: 'Vad betyder "volatile"?',
    questionType: 'multiple_choice',
    options: ['Stabil', 'Flyktig', 'Bestående', 'Långvarig'],
    correctAnswer: 'Flyktig',
    explanation: 'Volatile betyder flyktig, föränderlig eller instabil.',
    difficulty: 'hard',
  },
  {
    id: 'ord-b-13',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 13,
    questionText: 'Vilket ord betyder "olustig och dyster"?',
    questionType: 'multiple_choice',
    options: ['Glad', 'Ljus', 'Dyster', 'Hoppfull'],
    correctAnswer: 'Dyster',
    explanation: 'Dyster betyder olustig, mörk och nedstämd.',
    difficulty: 'easy',
  },
  {
    id: 'ord-b-14',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 14,
    questionText: 'Vad betyder "flagrant"?',
    questionType: 'multiple_choice',
    options: ['Dold', 'Uppenbar', 'Subtil', 'Oklar'],
    correctAnswer: 'Uppenbar',
    explanation: 'Flagrant betyder uppenbar, skriande eller öppen (ofta om något negativt).',
    difficulty: 'hard',
  },
  {
    id: 'ord-b-15',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 15,
    questionText: 'Vilket ord betyder "samtidig"?',
    questionType: 'multiple_choice',
    options: ['Tidigare', 'Senare', 'Samtidig', 'Försenad'],
    correctAnswer: 'Samtidig',
    explanation: 'Samtidig betyder att ske vid samma tidpunkt.',
    difficulty: 'easy',
  },
  {
    id: 'ord-b-16',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 16,
    questionText: 'Vad betyder "hedonistisk"?',
    questionType: 'multiple_choice',
    options: ['Asketisk', 'Njutningssökande', 'Sträng', 'Disciplinerad'],
    correctAnswer: 'Njutningssökande',
    explanation: 'Hedonistisk betyder njutningssökande, som prioriterar nöje och lycka.',
    difficulty: 'medium',
  },
  {
    id: 'ord-b-17',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 17,
    questionText: 'Vilket ord betyder "som kan förnekas"?',
    questionType: 'multiple_choice',
    options: ['Obestridlig', 'Förnekbar', 'Säker', 'Definitiv'],
    correctAnswer: 'Förnekbar',
    explanation: 'Förnekbar betyder att något kan förnekas eller ifrågasättas.',
    difficulty: 'medium',
  },
  {
    id: 'ord-b-18',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 18,
    questionText: 'Vad betyder "eskalerande"?',
    questionType: 'multiple_choice',
    options: ['Minskande', 'Ökande', 'Stabil', 'Konstant'],
    correctAnswer: 'Ökande',
    explanation: 'Eskalerande betyder ökande i intensitet eller omfattning.',
    difficulty: 'easy',
  },
  {
    id: 'ord-b-19',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 19,
    questionText: 'Vilket ord betyder "tillbakadragen och tystlåten"?',
    questionType: 'multiple_choice',
    options: ['Utåtriktad', 'Reserverad', 'Pratam', 'Social'],
    correctAnswer: 'Reserverad',
    explanation: 'Reserverad betyder tillbakadragen, tystlåten och försiktig.',
    difficulty: 'medium',
  },
  {
    id: 'ord-b-20',
    sectionCode: 'ORD',
    testVersion: 'ord-b',
    questionNumber: 20,
    questionText: 'Vad betyder "accelerera"?',
    questionType: 'multiple_choice',
    options: ['Bromsa', 'Öka farten', 'Stanna', 'Vänta'],
    correctAnswer: 'Öka farten',
    explanation: 'Accelerera betyder att öka hastigheten eller takten.',
    difficulty: 'easy',
  },

  // TEST C - ORD (20 nya frågor)
  {
    id: 'ord-c-1',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 1,
    questionText: 'Vad betyder "sporadisk"?',
    questionType: 'multiple_choice',
    options: ['Regelbunden', 'Spridd och oregelbunden', 'Konstant', 'Frekvent'],
    correctAnswer: 'Spridd och oregelbunden',
    explanation: 'Sporadisk betyder att något sker då och då, oregelbundet.',
    difficulty: 'medium',
  },
  {
    id: 'ord-c-2',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 2,
    questionText: 'Vilket ord betyder "oförsonlig och hård"?',
    questionType: 'multiple_choice',
    options: ['Eftergiven', 'Oböjlig', 'Mjuk', 'Tolerant'],
    correctAnswer: 'Oböjlig',
    explanation: 'Oböjlig betyder oförsonlig, hård och inte beredd att kompromissa.',
    difficulty: 'medium',
  },
  {
    id: 'ord-c-3',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 3,
    questionText: 'Vad betyder "konnoissör"?',
    questionType: 'multiple_choice',
    options: ['Nybörjare', 'Kännare', 'Amatör', 'Observatör'],
    correctAnswer: 'Kännare',
    explanation: 'Konnoissör betyder kännare eller expert inom ett område.',
    difficulty: 'easy',
  },
  {
    id: 'ord-c-4',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 4,
    questionText: 'Vilket ord är motsatsen till "frivol"?',
    questionType: 'multiple_choice',
    options: ['Lättsinnig', 'Ytlig', 'Allvarlig', 'Lekfull'],
    correctAnswer: 'Allvarlig',
    explanation: 'Frivol betyder lättsinnig och ytlig, allvarlig är motsatsen.',
    difficulty: 'hard',
  },
  {
    id: 'ord-c-5',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 5,
    questionText: 'Vad betyder "proliferation"?',
    questionType: 'multiple_choice',
    options: ['Minskning', 'Snabb spridning', 'Stabilitet', 'Upphörande'],
    correctAnswer: 'Snabb spridning',
    explanation: 'Proliferation betyder snabb spridning eller ökning.',
    difficulty: 'hard',
  },
  {
    id: 'ord-c-6',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 6,
    questionText: 'Vilket ord betyder "skicklig och händig"?',
    questionType: 'multiple_choice',
    options: ['Klumpig', 'Adroit', 'Ohanterlig', 'Osäker'],
    correctAnswer: 'Adroit',
    explanation: 'Adroit betyder skicklig, händig och behändig.',
    difficulty: 'medium',
  },
  {
    id: 'ord-c-7',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 7,
    questionText: 'Vad betyder "nostalgi"?',
    questionType: 'multiple_choice',
    options: ['Framtidstro', 'Längtan till det förflutna', 'Nutidsförankring', 'Pessimism'],
    correctAnswer: 'Längtan till det förflutna',
    explanation: 'Nostalgi betyder vemod och längtan efter det förflutna.',
    difficulty: 'easy',
  },
  {
    id: 'ord-c-8',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 8,
    questionText: 'Vilket ord betyder "överflödande och rik"?',
    questionType: 'multiple_choice',
    options: ['Knapp', 'Excessiv', 'Minimal', 'Sparsmakad'],
    correctAnswer: 'Excessiv',
    explanation: 'Excessiv betyder överflödande, rik eller överdådig.',
    difficulty: 'medium',
  },
  {
    id: 'ord-c-9',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 9,
    questionText: 'Vad är en synonym till "militant"?',
    questionType: 'multiple_choice',
    options: ['Passiv', 'Stridslysten', 'Fredlig', 'Neutral'],
    correctAnswer: 'Stridslysten',
    explanation: 'Militant betyder stridslysten och aggressivt engagerad.',
    difficulty: 'easy',
  },
  {
    id: 'ord-c-10',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 10,
    questionText: 'Vad betyder "anachronism"?',
    questionType: 'multiple_choice',
    options: ['Modern', 'Tidsenlig', 'Tidsförskjutning', 'Aktuell'],
    correctAnswer: 'Tidsförskjutning',
    explanation: 'Anachronism betyder något som inte passar in i sin tid.',
    difficulty: 'hard',
  },
  {
    id: 'ord-c-11',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 11,
    questionText: 'Vilket ord betyder "mycket liten"?',
    questionType: 'multiple_choice',
    options: ['Enorm', 'Jättestor', 'Minimal', 'Massiv'],
    correctAnswer: 'Minimal',
    explanation: 'Minimal betyder mycket liten eller nästan obefintlig.',
    difficulty: 'easy',
  },
  {
    id: 'ord-c-12',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 12,
    questionText: 'Vad betyder "verbosity"?',
    questionType: 'multiple_choice',
    options: ['Kortfattighet', 'Ordrikedom', 'Tystnad', 'Precision'],
    correctAnswer: 'Ordrikedom',
    explanation: 'Verbosity betyder ordrikedom eller mångordighet.',
    difficulty: 'hard',
  },
  {
    id: 'ord-c-13',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 13,
    questionText: 'Vilket ord betyder "lämpad för ändamålet"?',
    questionType: 'multiple_choice',
    options: ['Olämplig', 'Adekvat', 'Felaktig', 'Otillräcklig'],
    correctAnswer: 'Adekvat',
    explanation: 'Adekvat betyder tillräcklig och lämpad för sitt ändamål.',
    difficulty: 'easy',
  },
  {
    id: 'ord-c-14',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 14,
    questionText: 'Vad betyder "intrikat"?',
    questionType: 'multiple_choice',
    options: ['Enkel', 'Komplicerad', 'Tydlig', 'Rak'],
    correctAnswer: 'Komplicerad',
    explanation: 'Intrikat betyder komplicerad och invecklad.',
    difficulty: 'medium',
  },
  {
    id: 'ord-c-15',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 15,
    questionText: 'Vilket ord betyder "stödja eller främja"?',
    questionType: 'multiple_choice',
    options: ['Motverka', 'Främja', 'Hindra', 'Förneka'],
    correctAnswer: 'Främja',
    explanation: 'Främja betyder att stödja eller underlätta något.',
    difficulty: 'easy',
  },
  {
    id: 'ord-c-16',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 16,
    questionText: 'Vad betyder "redundans"?',
    questionType: 'multiple_choice',
    options: ['Brist', 'Överflöd', 'Balans', 'Nödvändighet'],
    correctAnswer: 'Överflöd',
    explanation: 'Redundans betyder överflöd eller onödig upprepning.',
    difficulty: 'medium',
  },
  {
    id: 'ord-c-17',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 17,
    questionText: 'Vilket ord betyder "hänsynslös och brutal"?',
    questionType: 'multiple_choice',
    options: ['Omtänksam', 'Brutal', 'Snäll', 'Försiktig'],
    correctAnswer: 'Brutal',
    explanation: 'Brutal betyder hänsynslös, rå och våldsam.',
    difficulty: 'easy',
  },
  {
    id: 'ord-c-18',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 18,
    questionText: 'Vad betyder "eufemism"?',
    questionType: 'multiple_choice',
    options: ['Skymford', 'Försköning', 'Förolämpning', 'Direkthet'],
    correctAnswer: 'Försköning',
    explanation: 'Eufemism betyder försköning eller mildare uttryck för något obehagligt.',
    difficulty: 'hard',
  },
  {
    id: 'ord-c-19',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 19,
    questionText: 'Vilket ord betyder "ömsesidig"?',
    questionType: 'multiple_choice',
    options: ['Ensidig', 'Reciprok', 'Isolerad', 'Separerad'],
    correctAnswer: 'Reciprok',
    explanation: 'Reciprok betyder ömsesidig eller växelvis.',
    difficulty: 'medium',
  },
  {
    id: 'ord-c-20',
    sectionCode: 'ORD',
    testVersion: 'ord-c',
    questionNumber: 20,
    questionText: 'Vad betyder "obsolet"?',
    questionType: 'multiple_choice',
    options: ['Modern', 'Föråldrad', 'Aktuell', 'Nyskapande'],
    correctAnswer: 'Föråldrad',
    explanation: 'Obsolet betyder föråldrad och inte längre i bruk.',
    difficulty: 'easy',
  },

  // =====================================================
  // LÄS - LÄSFÖRSTÅELSE (60 questions = 3 tests × 20)
  // =====================================================
  
  // TEST B - LÄS (20 nya frågor)
  {
    id: 'las-b-1',
    sectionCode: 'LÄS',
    testVersion: 'las-b',
    questionNumber: 1,
    questionText: 'Vad är författarens huvudsakliga syfte med texten?',
    questionType: 'reading_comprehension',
    readingPassage: 'Den digitala klyftan mellan generationer växer. Medan yngre människor intuitivt navigerar i teknologiska landskap, kämpar många äldre med grundläggande digitala verktyg. Detta skapar ojämlikhet i tillgång till information, service och social kontakt. Samhället måste investera i digital utbildning för alla åldrar.',
    options: [
      'Att kritisera ungdomar',
      'Att lyfta fram ett samhällsproblem och föreslå lösning',
      'Att glorifiera teknologi',
      'Att skrämma äldre människor'
    ],
    correctAnswer: 'Att lyfta fram ett samhällsproblem och föreslå lösning',
    explanation: 'Texten beskriver problemet med digital klyfta och avslutar med en uppmaning om digital utbildning.',
    difficulty: 'medium',
  },
  {
    id: 'las-b-2',
    sectionCode: 'LÄS',
    testVersion: 'las-b',
    questionNumber: 2,
    questionText: 'Vilket problem beskrivs i texten?',
    questionType: 'reading_comprehension',
    readingPassage: 'Den digitala klyftan mellan generationer växer. Medan yngre människor intuitivt navigerar i teknologiska landskap, kämpar många äldre med grundläggande digitala verktyg. Detta skapar ojämlikhet i tillgång till information, service och social kontakt. Samhället måste investera i digital utbildning för alla åldrar.',
    options: [
      'Ungdomar använder för mycket teknik',
      'Digital ojämlikhet mellan generationer',
      'Teknik är för komplicerad',
      'Internet är för dyrt'
    ],
    correctAnswer: 'Digital ojämlikhet mellan generationer',
    explanation: 'Texten fokuserar på skillnader i digital kompetens mellan åldersgrupper.',
    difficulty: 'easy',
  },
  {
    id: 'las-b-3',
    sectionCode: 'LÄS',
    testVersion: 'las-b',
    questionNumber: 3,
    questionText: 'Vilken ton har författaren?',
    questionType: 'reading_comprehension',
    readingPassage: 'Konsten att argumentera är en färdighet som ofta underskattas. I en tid av polarisering och ekokamrar är förmågan att föra en respektfull dialog viktigare än någonsin. Det handlar inte om att vinna, utan om att förstå olika perspektiv och kanske till och med ändra åsikt när argumenten är övertygande.',
    options: ['Aggressiv', 'Uppmuntrande och reflekterande', 'Pessimistisk', 'Ironisk'],
    correctAnswer: 'Uppmuntrande och reflekterande',
    explanation: 'Författaren betonar vikten av dialog och förståelse på ett positivt sätt.',
    difficulty: 'medium',
  },
  {
    id: 'las-b-4',
    sectionCode: 'LÄS',
    testVersion: 'las-b',
    questionNumber: 4,
    questionText: 'Vad menar författaren är målet med argumentation?',
    questionType: 'reading_comprehension',
    readingPassage: 'Konsten att argumentera är en färdighet som ofta underskattas. I en tid av polarisering och ekokamrar är förmågan att föra en respektfull dialog viktigare än någonsin. Det handlar inte om att vinna, utan om att förstå olika perspektiv och kanske till och med ändra åsikt när argumenten är övertygande.',
    options: [
      'Att vinna diskussionen',
      'Att förstå olika perspektiv',
      'Att övertala andra',
      'Att bevisa att man har rätt'
    ],
    correctAnswer: 'Att förstå olika perspektiv',
    explanation: 'Texten säger explicit att det handlar om förståelse, inte om att vinna.',
    difficulty: 'easy',
  },
  {
    id: 'las-b-5',
    sectionCode: 'LÄS',
    testVersion: 'las-b',
    questionNumber: 5,
    questionText: 'Vad är textens huvudtema?',
    questionType: 'reading_comprehension',
    readingPassage: 'Hållbar konsumtion är inte bara ett miljöval, utan en ekonomisk nödvändighet. Resurser blir allt knappare och priset på råvaror stiger. Företag som satsar på cirkulär ekonomi och återvinning kommer att ha en konkurrensfördel. Konsumenter blir också allt mer medvetna och väljer bort företag med dålig miljöprofil.',
    options: [
      'Miljöförstöring',
      'Hållbar konsumtion som ekonomisk strategi',
      'Prisstegringar',
      'Konsumentbeteende'
    ],
    correctAnswer: 'Hållbar konsumtion som ekonomisk strategi',
    explanation: 'Texten kopplar samman hållbarhet med ekonomiska fördelar.',
    difficulty: 'medium',
  },
  {
    id: 'las-b-6',
    sectionCode: 'LÄS',
    testVersion: 'las-b',
    questionNumber: 6,
    questionText: 'Enligt texten, varför ska företag satsa på hållbarhet?',
    questionType: 'reading_comprehension',
    readingPassage: 'Hållbar konsumtion är inte bara ett miljöval, utan en ekonomisk nödvändighet. Resurser blir allt knappare och priset på råvaror stiger. Företag som satsar på cirkulär ekonomi och återvinning kommer att ha en konkurrensfördel. Konsumenter blir också allt mer medvetna och väljer bort företag med dålig miljöprofil.',
    options: [
      'För att det är lagkrav',
      'För konkurrensfördel och konsumentval',
      'För att få subventioner',
      'För att följa trender'
    ],
    correctAnswer: 'För konkurrensfördel och konsumentval',
    explanation: 'Texten nämner både konkurrensfördel och medvetna konsumenter.',
    difficulty: 'easy',
  },
  {
    id: 'las-b-7',
    sectionCode: 'LÄS',
    testVersion: 'las-b',
    questionNumber: 7,
    questionText: 'Vilken slutsats kan dras från texten?',
    questionType: 'reading_comprehension',
    readingPassage: 'Musikalisk träning i barndomen påverkar hjärnans utveckling på flera sätt. Studier visar förbättrad språkförmåga, matematik och koncentration. Det handlar inte bara om att bli en bra musiker, utan om kognitiv utveckling i stort. Musik borde vara en obligatorisk del av grundutbildningen.',
    options: [
      'Alla barn bör bli musiker',
      'Musik har bredare fördelar än bara musikförmåga',
      'Matematik är viktigare än musik',
      'Musikträning är bortkastade tiden'
    ],
    correctAnswer: 'Musik har bredare fördelar än bara musikförmåga',
    explanation: 'Texten betonar att musik påverkar kognitiv utveckling i stort.',
    difficulty: 'easy',
  },
  {
    id: 'las-b-8',
    sectionCode: 'LÄS',
    testVersion: 'las-b',
    questionNumber: 8,
    questionText: 'Vad är författarens hållning?',
    questionType: 'reading_comprehension',
    readingPassage: 'Musikalisk träning i barndomen påverkar hjärnans utveckling på flera sätt. Studier visar förbättrad språkförmåga, matematik och koncentration. Det handlar inte bara om att bli en bra musiker, utan om kognitiv utveckling i stort. Musik borde vara en obligatorisk del av grundutbildningen.',
    options: [
      'Neutral',
      'Starkt positiv till musikutbildning',
      'Kritisk',
      'Tveksam'
    ],
    correctAnswer: 'Starkt positiv till musikutbildning',
    explanation: 'Författaren argumenterar för obligatorisk musikundervisning.',
    difficulty: 'easy',
  },
  {
    id: 'las-b-9',
    sectionCode: 'LÄS',
    testVersion: 'las-b',
    questionNumber: 9,
    questionText: 'Vilket problem lyfts fram i texten?',
    questionType: 'reading_comprehension',
    readingPassage: 'Den moderna arbetsmarknaden kräver ständig omställning. Automatisering och AI tar över rutinmässiga arbetsuppgifter, vilket innebär att människor måste fokusera på kreativitet, problemlösning och mellanmänskliga färdigheter. Utbildningssystem måste anpassas för att förbereda för detta.',
    options: [
      'AI är farligt',
      'Behovet av nya kompetenser på arbetsmarknaden',
      'Arbetslöshet',
      'För mycket automatisering'
    ],
    correctAnswer: 'Behovet av nya kompetenser på arbetsmarknaden',
    explanation: 'Texten fokuserar på förändrade kompetenskrav på grund av automatisering.',
    difficulty: 'medium',
  },
  {
    id: 'las-b-10',
    sectionCode: 'LÄS',
    testVersion: 'las-b',
    questionNumber: 10,
    questionText: 'Vilka färdigheter blir viktigare enligt texten?',
    questionType: 'reading_comprehension',
    readingPassage: 'Den moderna arbetsmarknaden kräver ständig omställning. Automatisering och AI tar över rutinmässiga arbetsuppgifter, vilket innebär att människor måste fokusera på kreativitet, problemlösning och mellanmänskliga färdigheter. Utbildningssystem måste anpassas för att förbereda för detta.',
    options: [
      'Tekniska färdigheter',
      'Rutinmässiga uppgifter',
      'Kreativitet och problemlösning',
      'Specialisering'
    ],
    correctAnswer: 'Kreativitet och problemlösning',
    explanation: 'Texten nämner kreativitet, problemlösning och mellanmänskliga färdigheter.',
    difficulty: 'easy',
  },
  {
    id: 'las-b-11',
    sectionCode: 'LÄS',
    testVersion: 'las-b',
    questionNumber: 11,
    questionText: 'Vad är författarens huvudargument?',
    questionType: 'reading_comprehension',
    readingPassage: 'Läsning av skönlitteratur utvecklar empati på ett sätt som faktatexter inte gör. Genom att leva sig in i fiktiva karaktärers liv och perspektiv tränar vi vår förmåga att förstå andra människor. I en alltmer polariserad värld är denna förmåga ovärderlig.',
    options: [
      'Fakta är viktigare än fiktion',
      'Skönlitteratur utvecklar empati',
      'Läsning är tråkigt',
      'Polarisering är ett problem'
    ],
    correctAnswer: 'Skönlitteratur utvecklar empati',
    explanation: 'Textens huvudargument är att läsning av skönlitteratur tränar empati.',
    difficulty: 'easy',
  },
  {
    id: 'las-b-12',
    sectionCode: 'LÄS',
    testVersion: 'las-b',
    questionNumber: 12,
    questionText: 'Varför är empati viktig enligt författaren?',
    questionType: 'reading_comprehension',
    readingPassage: 'Läsning av skönlitteratur utvecklar empati på ett sätt som faktatexter inte gör. Genom att leva sig in i fiktiva karaktärers liv och perspektiv tränar vi vår förmåga att förstå andra människor. I en alltmer polariserad värld är denna förmåga ovärderlig.',
    options: [
      'För att lyckas i skolan',
      'För att motverka polarisering',
      'För att bli populär',
      'För att förstå böcker'
    ],
    correctAnswer: 'För att motverka polarisering',
    explanation: 'Texten kopplar empati till att hantera en polariserad värld.',
    difficulty: 'medium',
  },
  {
    id: 'las-b-13',
    sectionCode: 'LÄS',
    testVersion: 'las-b',
    questionNumber: 13,
    questionText: 'Vad är textens syfte?',
    questionType: 'reading_comprehension',
    readingPassage: 'Stress är inte alltid negativt. Kortvarig stress kan faktiskt förbättra prestation och fokus. Det är den kroniska stressen som är skadlig. Nyckeln är att lära sig skilja mellan utmanande situationer som sporrar oss och överbelastning som sliter ner.',
    options: [
      'Att skrämma läsaren',
      'Att nyansera synen på stress',
      'Att eliminera all stress',
      'Att kritisera stressade människor'
    ],
    correctAnswer: 'Att nyansera synen på stress',
    explanation: 'Texten visar att stress inte alltid är negativt.',
    difficulty: 'medium',
  },
  {
    id: 'las-b-14',
    sectionCode: 'LÄS',
    testVersion: 'las-b',
    questionNumber: 14,
    questionText: 'Enligt texten, vilken typ av stress är skadlig?',
    questionType: 'reading_comprehension',
    readingPassage: 'Stress är inte alltid negativt. Kortvarig stress kan faktiskt förbättra prestation och fokus. Det är den kroniska stressen som är skadlig. Nyckeln är att lära sig skilja mellan utmanande situationer som sporrar oss och överbelastning som sliter ner.',
    options: [
      'All stress',
      'Kronisk stress',
      'Kortvarig stress',
      'Prestationsstress'
    ],
    correctAnswer: 'Kronisk stress',
    explanation: 'Texten säger explicit att den kroniska stressen är skadlig.',
    difficulty: 'easy',
  },
  {
    id: 'las-b-15',
    sectionCode: 'LÄS',
    testVersion: 'las-b',
    questionNumber: 15,
    questionText: 'Vad saknas i texten?',
    questionType: 'reading_comprehension',
    readingPassage: 'Genterapi lovar att revolutionera medicinen. Sjukdomar som tidigare var obotliga kan nu potentiellt botas genom att ändra patientens genetiska kod. Tekniken är redan i kliniska prövningar för flera allvarliga sjukdomar.',
    options: [
      'Exempel på sjukdomar',
      'Diskussion om etiska problem',
      'Tekniska detaljer',
      'Forskares namn'
    ],
    correctAnswer: 'Diskussion om etiska problem',
    explanation: 'Texten är enbart positiv och tar inte upp etiska aspekter av genredigering.',
    difficulty: 'hard',
  },
  {
    id: 'las-b-16',
    sectionCode: 'LÄS',
    testVersion: 'las-b',
    questionNumber: 16,
    questionText: 'Vilken ton har författaren?',
    questionType: 'reading_comprehension',
    readingPassage: 'Genterapi lovar att revolutionera medicinen. Sjukdomar som tidigare var obotliga kan nu potentiellt botas genom att ändra patientens genetiska kod. Tekniken är redan i kliniska prövningar för flera allvarliga sjukdomar.',
    options: [
      'Kritisk',
      'Optimistisk',
      'Neutral',
      'Pessimistisk'
    ],
    correctAnswer: 'Optimistisk',
    explanation: 'Författaren presenterar genterapi som revolutionerande och lovande.',
    difficulty: 'easy',
  },
  {
    id: 'las-b-17',
    sectionCode: 'LÄS',
    testVersion: 'las-b',
    questionNumber: 17,
    questionText: 'Vad är huvudbudskapet?',
    questionType: 'reading_comprehension',
    readingPassage: 'Den svenska demokratin bygger på mer än bara val vart fjärde år. Engagemang i föreningar, fackföreningar och lokala initiativ skapar en levande civilsamhälle. Detta är navet i vad som kallas den nordiska modellen.',
    options: [
      'Val är oviktiga',
      'Civilsamhället är grunden för demokratin',
      'Sverige är perfekt',
      'Föreningar är obligatoriska'
    ],
    correctAnswer: 'Civilsamhället är grunden för demokratin',
    explanation: 'Texten betonar civilsamhällets betydelse för demokratin.',
    difficulty: 'easy',
  },
  {
    id: 'las-b-18',
    sectionCode: 'LÄS',
    testVersion: 'las-b',
    questionNumber: 18,
    questionText: 'Vad menas med "den nordiska modellen"?',
    questionType: 'reading_comprehension',
    readingPassage: 'Den svenska demokratin bygger på mer än bara val vart fjärde år. Engagemang i föreningar, fackföreningar och lokala initiativ skapar en levande civilsamhälle. Detta är navet i vad som kallas den nordiska modellen.',
    options: [
      'Ett valsystem',
      'Ett samhällssystem med starkt civilsamhälle',
      'En ekonomisk modell',
      'En geografisk region'
    ],
    correctAnswer: 'Ett samhällssystem med starkt civilsamhälle',
    explanation: 'Texten beskriver den nordiska modellen som byggd på ett aktivt civilsamhälle.',
    difficulty: 'medium',
  },
  {
    id: 'las-b-19',
    sectionCode: 'LÄS',
    testVersion: 'las-b',
    questionNumber: 19,
    questionText: 'Vilket perspektiv presenteras i texten?',
    questionType: 'reading_comprehension',
    readingPassage: 'Fjärdsarbete har förändrat arbetslivet permanent. Många uppskattar flexibiliteten, men gränsen mellan arbete och fritid suddas ut. Företag måste hitta nya sätt att skapa gemenskap och kultur när medarbetare inte träffas fysiskt.',
    options: [
      'Endast positiva aspekter',
      'Både fördelar och utmaningar',
      'Endast negativa aspekter',
      'Tekniska aspekter'
    ],
    correctAnswer: 'Både fördelar och utmaningar',
    explanation: 'Texten nämner både flexibilitet (positivt) och utmaningar med gränser och kultur.',
    difficulty: 'medium',
  },
  {
    id: 'las-b-20',
    sectionCode: 'LÄS',
    testVersion: 'las-b',
    questionNumber: 20,
    questionText: 'Vad är den huvudsakliga utmaningen med fjärrarbete enligt texten?',
    questionType: 'reading_comprehension',
    readingPassage: 'Fjärdsarbete har förändrat arbetslivet permanent. Många uppskattar flexibiliteten, men gränsen mellan arbete och fritid suddas ut. Företag måste hitta nya sätt att skapa gemenskap och kultur när medarbetare inte träffas fysiskt.',
    options: [
      'Tekniska problem',
      'Att skapa kultur och gemenskap på distans',
      'Produktivitet',
      'Kostnader'
    ],
    correctAnswer: 'Att skapa kultur och gemenskap på distans',
    explanation: 'Texten nämner att företag måste hitta nya sätt att skapa gemenskap och kultur.',
    difficulty: 'easy',
  },

  // TEST C - LÄS (20 nya frågor)
  {
    id: 'las-c-1',
    sectionCode: 'LÄS',
    testVersion: 'las-c',
    questionNumber: 1,
    questionText: 'Vad är författarens huvudpoäng?',
    questionType: 'reading_comprehension',
    readingPassage: 'Konstgjord intelligens kan skapa imponerande konstverk, musik och texter. Men frågan kvarstår: är det verkligen konst om det saknar mänsklig intention och upplevelse? Konst har alltid handlat om kommunikation mellan människor, om att dela erfarenheter och känslor.',
    options: [
      'AI är bättre än människor',
      'Konst kräver mänsklig intention',
      'AI bör inte användas',
      'Konst är oviktig'
    ],
    correctAnswer: 'Konst kräver mänsklig intention',
    explanation: 'Författaren ifrågasätter om AI-skapad konst är verklig konst utan mänsklig intention.',
    difficulty: 'medium',
  },
  {
    id: 'las-c-2',
    sectionCode: 'LÄS',
    testVersion: 'las-c',
    questionNumber: 2,
    questionText: 'Vad definierar konst enligt texten?',
    questionType: 'reading_comprehension',
    readingPassage: 'Konstgjord intelligens kan skapa imponerande konstverk, musik och texter. Men frågan kvarstår: är det verkligen konst om det saknar mänsklig intention och upplevelse? Konst har alltid handlat om kommunikation mellan människor, om att dela erfarenheter och känslor.',
    options: [
      'Teknisk skicklighet',
      'Dyrhet',
      'Kommunikation mellan människor',
      'Komplexitet'
    ],
    correctAnswer: 'Kommunikation mellan människor',
    explanation: 'Texten säger att konst handlar om att kommunicera och dela erfarenheter mellan människor.',
    difficulty: 'easy',
  },
  {
    id: 'las-c-3',
    sectionCode: 'LÄS',
    testVersion: 'las-c',
    questionNumber: 3,
    questionText: 'Vilken ton använder författaren?',
    questionType: 'reading_comprehension',
    readingPassage: 'Biodiversitet är inte bara vacker att titta på - den är avgörande för mänsklig överlevnad. Varje art spelar en roll i ekosystemet, och när en försvinner påverkas hela kedjan. Utrotningen av arter sker nu i en takt som liknar de stora massutdöendena i jordens historia.',
    options: ['Lättsam', 'Allvarlig och varningsam', 'Humoristisk', 'Likgiltig'],
    correctAnswer: 'Allvarlig och varningsam',
    explanation: 'Författaren jämför nuvarande situation med massutdöenden, vilket är en stark varning.',
    difficulty: 'easy',
  },
  {
    id: 'las-c-4',
    sectionCode: 'LÄS',
    testVersion: 'las-c',
    questionNumber: 4,
    questionText: 'Varför är biodiversitet viktig enligt texten?',
    questionType: 'reading_comprehension',
    readingPassage: 'Biodiversitet är inte bara vacker att titta på - den är avgörande för mänsklig överlevnad. Varje art spelar en roll i ekosystemet, och när en försvinner påverkas hela kedjan. Utrotningen av arter sker nu i en takt som liknar de stora massutdöendena i jordens historia.',
    options: [
      'För estetiska skäl',
      'För mänsklig överlevnad',
      'För turism',
      'För vetenskaplig forskning'
    ],
    correctAnswer: 'För mänsklig överlevnad',
    explanation: 'Texten säger explicit att biodiversitet är avgörande för mänsklig överlevnad.',
    difficulty: 'easy',
  },
  {
    id: 'las-c-5',
    sectionCode: 'LÄS',
    testVersion: 'las-c',
    questionNumber: 5,
    questionText: 'Vad är författarens hållning?',
    questionType: 'reading_comprehension',
    readingPassage: 'Social media har demokratiserat informationsspridningen, men samtidigt skapat nya problem. Fake news sprids snabbare än sanningen, algoritmer skapar ekokamrar, och polariseringen ökar. Vi behöver digital källkritik som en grundläggande färdighet i skolan.',
    options: [
      'Helt negativ till sociala medier',
      'Balanserad med betoning på källkritik',
      'Helt positiv',
      'Ointresserad'
    ],
    correctAnswer: 'Balanserad med betoning på källkritik',
    explanation: 'Författaren nämner både positiva och negativa aspekter och föreslår källkritik som lösning.',
    difficulty: 'medium',
  },
  {
    id: 'las-c-6',
    sectionCode: 'LÄS',
    testVersion: 'las-c',
    questionNumber: 6,
    questionText: 'Vilken lösning föreslås?',
    questionType: 'reading_comprehension',
    readingPassage: 'Social media har demokratiserat informationsspridningen, men samtidigt skapat nya problem. Fake news sprids snabbare än sanningen, algoritmer skapar ekokamrar, och polariseringen ökar. Vi behöver digital källkritik som en grundläggande färdighet i skolan.',
    options: [
      'Förbjuda sociala medier',
      'Undervisa i digital källkritik',
      'Censurera internet',
      'Ignorera problemet'
    ],
    correctAnswer: 'Undervisa i digital källkritik',
    explanation: 'Texten avslutar med att vi behöver digital källkritik i skolan.',
    difficulty: 'easy',
  },
  {
    id: 'las-c-7',
    sectionCode: 'LÄS',
    testVersion: 'las-c',
    questionNumber: 7,
    questionText: 'Vad är textens huvudtema?',
    questionType: 'reading_comprehension',
    readingPassage: 'Urban odling växer i popularitet. På hustak och i gemenskapsodlingar odlar stadsbor sina egna grönsaker. Det handlar om mer än bara mat - det skapar gemenskap, minskar koldioxidutsläpp från transport och ger människor kontakt med naturen mitt i staden.',
    options: [
      'Matproduktion',
      'Urban odling som mångfacetterad lösning',
      'Miljöproblem',
      'Stadsplanering'
    ],
    correctAnswer: 'Urban odling som mångfacetterad lösning',
    explanation: 'Texten beskriver flera fördelar med urban odling bortom bara matproduktion.',
    difficulty: 'medium',
  },
  {
    id: 'las-c-8',
    sectionCode: 'LÄS',
    testVersion: 'las-c',
    questionNumber: 8,
    questionText: 'Vilka fördelar nämns med urban odling?',
    questionType: 'reading_comprehension',
    readingPassage: 'Urban odling växer i popularitet. På hustak och i gemenskapsodlingar odlar stadsbor sina egna grönsaker. Det handlar om mer än bara mat - det skapar gemenskap, minskar koldioxidutsläpp från transport och ger människor kontakt med naturen mitt i staden.',
    options: [
      'Endast matproduktion',
      'Gemenskap, miljö och naturkontakt',
      'Endast ekonomiska',
      'Endast hälsofördelar'
    ],
    correctAnswer: 'Gemenskap, miljö och naturkontakt',
    explanation: 'Texten nämner gemenskap, minskade utsläpp och naturkontakt.',
    difficulty: 'easy',
  },
  {
    id: 'las-c-9',
    sectionCode: 'LÄS',
    testVersion: 'las-c',
    questionNumber: 9,
    questionText: 'Vilket antagande gör författaren?',
    questionType: 'reading_comprehension',
    readingPassage: 'Rymdforskning kritiseras ofta som bortkastade pengar när det finns problem på jorden. Men teknologi utvecklad för rymden har gett oss GPS, vädersatelliter och medicinska innovationer. Grundforskning ger ofta oväntade tillämpningar.',
    options: [
      'Rymdforskning är bortkastade pengar',
      'Grundforskning har praktiskt värde',
      'Alla problem på jorden är lösta',
      'Rymden är viktigare än jorden'
    ],
    correctAnswer: 'Grundforskning har praktiskt värde',
    explanation: 'Författaren argumenterar för att rymdforskning leder till praktiska innovationer.',
    difficulty: 'medium',
  },
  {
    id: 'las-c-10',
    sectionCode: 'LÄS',
    testVersion: 'las-c',
    questionNumber: 10,
    questionText: 'Hur bemöter författaren kritiken?',
    questionType: 'reading_comprehension',
    readingPassage: 'Rymdforskning kritiseras ofta som bortkastade pengar när det finns problem på jorden. Men teknologi utvecklad för rymden har gett oss GPS, vädersatelliter och medicinska innovationer. Grundforskning ger ofta oväntade tillämpningar.',
    options: [
      'Genom att ignorera den',
      'Genom att ge konkreta exempel på nytta',
      'Genom att attackera kritiker',
      'Genom att byta ämne'
    ],
    correctAnswer: 'Genom att ge konkreta exempel på nytta',
    explanation: 'Författaren ger exempel på praktisk teknik från rymdforskning.',
    difficulty: 'easy',
  },
  {
    id: 'las-c-11',
    sectionCode: 'LÄS',
    testVersion: 'las-c',
    questionNumber: 11,
    questionText: 'Vad är textens syfte?',
    questionType: 'reading_comprehension',
    readingPassage: 'Mental hälsa har länge varit ett tabubelagt ämne. Men attityderna förändras. Kända personer delar sina erfarenheter, företag inför stödprogram och sjukvården satsar mer resurser. Att söka hjälp ses inte längre som svaghet utan som ett tecken på styrka.',
    options: [
      'Att stigmatisera mental ohälsa',
      'Att beskriva positiv attitydförändring',
      'Att kritisera sjukvården',
      'Att ge medicinska råd'
    ],
    correctAnswer: 'Att beskriva positiv attitydförändring',
    explanation: 'Texten beskriver hur synen på mental hälsa förändras till det bättre.',
    difficulty: 'easy',
  },
  {
    id: 'las-c-12',
    sectionCode: 'LÄS',
    testVersion: 'las-c',
    questionNumber: 12,
    questionText: 'Vad ses som styrka enligt texten?',
    questionType: 'reading_comprehension',
    readingPassage: 'Mental hälsa har länge varit ett tabubelagt ämne. Men attityderna förändras. Kända personer delar sina erfarenheter, företag inför stödprogram och sjukvården satsar mer resurser. Att söka hjälp ses inte längre som svaghet utan som ett tecken på styrka.',
    options: [
      'Att dölja problem',
      'Att söka hjälp',
      'Att klara sig själv',
      'Att undvika diskussionen'
    ],
    correctAnswer: 'Att söka hjälp',
    explanation: 'Texten säger att att söka hjälp ses som ett tecken på styrka.',
    difficulty: 'easy',
  },
  {
    id: 'las-c-13',
    sectionCode: 'LÄS',
    testVersion: 'las-c',
    questionNumber: 13,
    questionText: 'Vilken slutsats kan dras?',
    questionType: 'reading_comprehension',
    readingPassage: 'Vetenskaplig metod bygger på att teorier ska kunna motbevisas. Det som inte kan testas är inte vetenskap. Detta skiljer vetenskap från tro och pseudovetenskap. Även etablerade teorier måste ständigt ifrågasättas och testas mot nya data.',
    options: [
      'Vetenskap är absolut sanning',
      'Vetenskap bygger på testbarhet och ifrågasättande',
      'Tro och vetenskap är samma sak',
      'Teorier förändras aldrig'
    ],
    correctAnswer: 'Vetenskap bygger på testbarhet och ifrågasättande',
    explanation: 'Texten betonar att vetenskap kräver testbarhet och ständigt ifrågasättande.',
    difficulty: 'medium',
  },
  {
    id: 'las-c-14',
    sectionCode: 'LÄS',
    testVersion: 'las-c',
    questionNumber: 14,
    questionText: 'Vad skiljer vetenskap från pseudovetenskap?',
    questionType: 'reading_comprehension',
    readingPassage: 'Vetenskaplig metod bygger på att teorier ska kunna motbevisas. Det som inte kan testas är inte vetenskap. Detta skiljer vetenskap från tro och pseudovetenskap. Även etablerade teorier måste ständigt ifrågasättas och testas mot nya data.',
    options: [
      'Komplexitet',
      'Testbarhet',
      'Popularitet',
      'Ålder'
    ],
    correctAnswer: 'Testbarhet',
    explanation: 'Texten säger att det som inte kan testas inte är vetenskap.',
    difficulty: 'easy',
  },
  {
    id: 'las-c-15',
    sectionCode: 'LÄS',
    testVersion: 'las-c',
    questionNumber: 15,
    questionText: 'Vad är författarens hållning?',
    questionType: 'reading_comprehension',
    readingPassage: 'Globalisering har lyftt miljoner ur fattigdom och skapat ekonomisk tillväxt. Men den har också ökat ojämlikheten och gjort världsekonomin sårbar för kriser. Lösningen är inte mindre globalisering, utan smartare globalisering med rättvisare regler.',
    options: [
      'Mot all globalisering',
      'Nyanserad och reforminriktad',
      'Okritiskt positiv',
      'Likgiltig'
    ],
    correctAnswer: 'Nyanserad och reforminriktad',
    explanation: 'Författaren ser både för- och nackdelar och förespråkar förbättring snarare än avskaffande.',
    difficulty: 'medium',
  },
  {
    id: 'las-c-16',
    sectionCode: 'LÄS',
    testVersion: 'las-c',
    questionNumber: 16,
    questionText: 'Vilken lösning föreslås?',
    questionType: 'reading_comprehension',
    readingPassage: 'Globalisering har lyfft miljoner ur fattigdom och skapat ekonomisk tillväxt. Men den har också ökat ojämlikheten och gjort världsekonomin sårbar för kriser. Lösningen är inte mindre globalisering, utan smartare globalisering med rättvisare regler.',
    options: [
      'Avskaffa globalisering',
      'Smartare globalisering med rättvisare regler',
      'Mer globalisering',
      'Protektionism'
    ],
    correctAnswer: 'Smartare globalisering med rättvisare regler',
    explanation: 'Texten avslutar med att lösningen är smartare globalisering med rättvisare regler.',
    difficulty: 'easy',
  },
  {
    id: 'las-c-17',
    sectionCode: 'LÄS',
    testVersion: 'las-c',
    questionNumber: 17,
    questionText: 'Vad är textens huvudpoäng?',
    questionType: 'reading_comprehension',
    readingPassage: 'Historia upprepar sig inte exakt, men den rimmar. Genom att studera historiska mönster kan vi förstå nutiden bättre och kanske undvika att upprepa gamla misstag. Historielöshet leder till att varje generation tror sig upptäcka världen på nytt.',
    options: [
      'Historia är meningslös',
      'Historia ger perspektiv och lärdomar',
      'Historia upprepar sig exakt',
      'Framtiden är omöjlig att förutse'
    ],
    correctAnswer: 'Historia ger perspektiv och lärdomar',
    explanation: 'Texten argumenterar för att historisk kunskap hjälper oss förstå nutiden och undvika misstag.',
    difficulty: 'medium',
  },
  {
    id: 'las-c-18',
    sectionCode: 'LÄS',
    testVersion: 'las-c',
    questionNumber: 18,
    questionText: 'Vad menas med att "historia rimmar"?',
    questionType: 'reading_comprehension',
    readingPassage: 'Historia upprepar sig inte exakt, men den rimmar. Genom att studera historiska mönster kan vi förstå nutiden bättre och kanske undvika att upprepa gamla misstag. Historielöshet leder till att varje generation tror sig upptäcka världen på nytt.',
    options: [
      'Historia är poesi',
      'Historiska mönster återkommer',
      'Historia är identisk',
      'Historia är slumpmässig'
    ],
    correctAnswer: 'Historiska mönster återkommer',
    explanation: 'Att historia "rimmar" betyder att liknande mönster återkommer, om än inte exakt.',
    difficulty: 'hard',
  },
  {
    id: 'las-c-19',
    sectionCode: 'LÄS',
    testVersion: 'las-c',
    questionNumber: 19,
    questionText: 'Vilken ton använder texten?',
    questionType: 'reading_comprehension',
    readingPassage: 'Den fjärde industriella revolutionen är här. Sammansmältningen av fysisk, digital och biologisk teknologi förändrar allt. Vi står inför både enorma möjligheter och allvarliga utmaningar. Hur vi hanterar denna transition kommer definiera framtiden.',
    options: [
      'Skrämmande',
      'Visionär men balanserad',
      'Pessimistisk',
      'Ointresserad'
    ],
    correctAnswer: 'Visionär men balanserad',
    explanation: 'Texten beskriver stora förändringar med både möjligheter och utmaningar.',
    difficulty: 'medium',
  },
  {
    id: 'las-c-20',
    sectionCode: 'LÄS',
    testVersion: 'las-c',
    questionNumber: 20,
    questionText: 'Vad betonas i slutet av texten?',
    questionType: 'reading_comprehension',
    readingPassage: 'Den fjärde industriella revolutionen är här. Sammansmältningen av fysisk, digital och biologisk teknologi förändrar allt. Vi står inför både enorma möjligheter och allvarliga utmaningar. Hur vi hanterar denna transition kommer definiera framtiden.',
    options: [
      'Teknologins överlägsenhet',
      'Vikten av hur vi hanterar förändringen',
      'Att motstå förändring',
      'Ekonomiska aspekter'
    ],
    correctAnswer: 'Vikten av hur vi hanterar förändringen',
    explanation: 'Texten avslutar med att belysa vikten av hur vi hanterar transitionen.',
    difficulty: 'easy',
  },

  // =====================================================
  // MEK - MENINGSKOMPLETTERING (60 questions = 3 tests × 20)
  // =====================================================

  // TEST B - MEK (20 nya frågor)
  {
    id: 'mek-b-1',
    sectionCode: 'MEK',
    testVersion: 'mek-b',
    questionNumber: 1,
    questionText: 'Även om forskningsresultaten var ____, vågade ingen ____ att dra för hastiga slutsatser.',
    questionType: 'multiple_choice',
    options: [
      'oklara ... vägra',
      'övertygande ... risk',
      'betydelselösa ... tvekan',
      'tydliga ... försök'
    ],
    correctAnswer: 'övertygande ... risk',
    explanation: 'Trots övertygande resultat vågade ingen riskera att dra för hastiga slutsatser.',
    difficulty: 'medium',
  },
  {
    id: 'mek-b-2',
    sectionCode: 'MEK',
    testVersion: 'mek-b',
    questionNumber: 2,
    questionText: 'Den nya lagen ____ för att ____ de svagas rättigheter.',
    questionType: 'multiple_choice',
    options: [
      'avskaffades ... försvaga',
      'infördes ... stärka',
      'ignorerades ... förbättra',
      'diskuterades ... radera'
    ],
    correctAnswer: 'infördes ... stärka',
    explanation: 'Lagar införs för att stärka rättigheter.',
    difficulty: 'easy',
  },
  {
    id: 'mek-b-3',
    sectionCode: 'MEK',
    testVersion: 'mek-b',
    questionNumber: 3,
    questionText: 'Hans ____ framträdande dolde hans ____ osäkerhet.',
    questionType: 'multiple_choice',
    options: [
      'blyga ... uppenbara',
      'självsäkra ... inre',
      'aggressiva ... externa',
      'trevande ... fullständiga'
    ],
    correctAnswer: 'självsäkra ... inre',
    explanation: 'Ett självsäkert framträdande kan dölja inre osäkerhet.',
    difficulty: 'medium',
  },
  {
    id: 'mek-b-4',
    sectionCode: 'MEK',
    testVersion: 'mek-b',
    questionNumber: 4,
    questionText: 'Ju mer komplicerad tekniken blir, desto ____ blir det för gemene man att ____ den.',
    questionType: 'multiple_choice',
    options: [
      'enklare ... avvisa',
      'svårare ... förstå',
      'viktigare ... ignorera',
      'onödigare ... använda'
    ],
    correctAnswer: 'svårare ... förstå',
    explanation: 'Komplicerad teknik är svårare att förstå för gemene man.',
    difficulty: 'easy',
  },
  {
    id: 'mek-b-5',
    sectionCode: 'MEK',
    testVersion: 'mek-b',
    questionNumber: 5,
    questionText: 'Kritikerna ____ att verket var alltför ____ för att tilltala en bred publik.',
    questionType: 'multiple_choice',
    options: [
      'hävdade ... esoteriskt',
      'förnekade ... populärt',
      'tvivlade ... tillgängligt',
      'beundrade ... simpelt'
    ],
    correctAnswer: 'hävdade ... esoteriskt',
    explanation: 'Kritiker kan hävda att något esoteriskt (svårtillgängligt) inte når bred publik.',
    difficulty: 'hard',
  },
  {
    id: 'mek-b-6',
    sectionCode: 'MEK',
    testVersion: 'mek-b',
    questionNumber: 6,
    questionText: 'Den ekonomiska ____ tvingade företaget att ____ antalet anställda.',
    questionType: 'multiple_choice',
    options: [
      'tillväxten ... öka',
      'nedgången ... minska',
      'stabiliteten ... behålla',
      'expansionen ... fördubbla'
    ],
    correctAnswer: 'nedgången ... minska',
    explanation: 'Ekonomisk nedgång leder ofta till minskat antal anställda.',
    difficulty: 'easy',
  },
  {
    id: 'mek-b-7',
    sectionCode: 'MEK',
    testVersion: 'mek-b',
    questionNumber: 7,
    questionText: 'Hennes ____ sätt att uttrycka sig gjorde att budskapet ____ förlorades.',
    questionType: 'multiple_choice',
    options: [
      'tydliga ... aldrig',
      'vaga ... ofta',
      'direkta ... sällan',
      'klara ... alltid'
    ],
    correctAnswer: 'vaga ... ofta',
    explanation: 'Vagt uttryck leder till att budskap ofta förloras.',
    difficulty: 'medium',
  },
  {
    id: 'mek-b-8',
    sectionCode: 'MEK',
    testVersion: 'mek-b',
    questionNumber: 8,
    questionText: 'I stället för att ____ problemet valde de att ____ en konstruktiv dialog.',
    questionType: 'multiple_choice',
    options: [
      'lösa ... undvika',
      'ignorera ... inleda',
      'skapa ... avbryta',
      'diskutera ... förkasta'
    ],
    correctAnswer: 'ignorera ... inleda',
    explanation: 'Man väljer att inleda dialog istället för att ignorera problem.',
    difficulty: 'easy',
  },
  {
    id: 'mek-b-9',
    sectionCode: 'MEK',
    testVersion: 'mek-b',
    questionNumber: 9,
    questionText: 'Hans ____ beteende gjorde det svårt för kollegorna att ____ hur han skulle reagera.',
    questionType: 'multiple_choice',
    options: [
      'förutsägbara ... undra',
      'oberäkneliga ... förutse',
      'stabila ... gissa',
      'konsekventa ... tvivla'
    ],
    correctAnswer: 'oberäkneliga ... förutse',
    explanation: 'Oberäkneligt beteende är svårt att förutse.',
    difficulty: 'medium',
  },
  {
    id: 'mek-b-10',
    sectionCode: 'MEK',
    testVersion: 'mek-b',
    questionNumber: 10,
    questionText: 'Den ____ informationen i rapporten gjorde att beslutsfattarna ____ dra korrekta slutsatser.',
    questionType: 'multiple_choice',
    options: [
      'detaljerade ... kunde',
      'bristfälliga ... inte kunde',
      'omfattande ... vägrade',
      'korrekta ... undvek'
    ],
    correctAnswer: 'bristfälliga ... inte kunde',
    explanation: 'Bristfällig information gör att man inte kan dra korrekta slutsatser.',
    difficulty: 'easy',
  },
  {
    id: 'mek-b-11',
    sectionCode: 'MEK',
    testVersion: 'mek-b',
    questionNumber: 11,
    questionText: 'Trots sin ____ ålder visade hon en ____ mognad i sitt sätt att resonera.',
    questionType: 'multiple_choice',
    options: [
      'höga ... bristande',
      'unga ... anmärkningsvärd',
      'avancerade ... minimal',
      'låga ... genomsnittlig'
    ],
    correctAnswer: 'unga ... anmärkningsvärd',
    explanation: 'Ung ålder kontrasteras med anmärkningsvärd mognad.',
    difficulty: 'medium',
  },
  {
    id: 'mek-b-12',
    sectionCode: 'MEK',
    testVersion: 'mek-b',
    questionNumber: 12,
    questionText: 'Vetenskapen har ____ vårt sätt att ____ världen.',
    questionType: 'multiple_choice',
    options: [
      'förändrat ... förstå',
      'förstört ... ignorera',
      'komplicerat ... undvika',
      'begränsat ... uppleva'
    ],
    correctAnswer: 'förändrat ... förstå',
    explanation: 'Vetenskap har förändrat hur vi förstår världen.',
    difficulty: 'easy',
  },
  {
    id: 'mek-b-13',
    sectionCode: 'MEK',
    testVersion: 'mek-b',
    questionNumber: 13,
    questionText: 'Den nya metoden var både ____ och ____, vilket gjorde den idealisk för storskalig tillämpning.',
    questionType: 'multiple_choice',
    options: [
      'komplicerad ... dyr',
      'effektiv ... kostnadseffektiv',
      'långsam ... ineffektiv',
      'otydlig ... osäker'
    ],
    correctAnswer: 'effektiv ... kostnadseffektiv',
    explanation: 'För storskalig tillämpning behövs både effektivitet och kostnadseffektivitet.',
    difficulty: 'easy',
  },
  {
    id: 'mek-b-14',
    sectionCode: 'MEK',
    testVersion: 'mek-b',
    questionNumber: 14,
    questionText: 'Hans ____ att ____ nya perspektiv gjorde honom till en värdefull teammedlem.',
    questionType: 'multiple_choice',
    options: [
      'ovilja ... acceptera',
      'förmåga ... integrera',
      'svårighet ... förkasta',
      'motvilja ... skapa'
    ],
    correctAnswer: 'förmåga ... integrera',
    explanation: 'Förmåga att integrera nya perspektiv är värdefullt i teamarbete.',
    difficulty: 'medium',
  },
  {
    id: 'mek-b-15',
    sectionCode: 'MEK',
    testVersion: 'mek-b',
    questionNumber: 15,
    questionText: 'Historien visar att stora ____ ofta följs av perioder av konsolidering och ____.',
    questionType: 'multiple_choice',
    options: [
      'framsteg ... stagnation',
      'omvälvningar ... stabilisering',
      'katastrofer ... expansion',
      'framgångar ... nedgång'
    ],
    correctAnswer: 'omvälvningar ... stabilisering',
    explanation: 'Stora omvälvningar följs ofta av stabiliseringsperioder.',
    difficulty: 'hard',
  },
  {
    id: 'mek-b-16',
    sectionCode: 'MEK',
    testVersion: 'mek-b',
    questionNumber: 16,
    questionText: 'Forskningens ____ gör det svårt att ____ de långsiktiga konsekvenserna.',
    questionType: 'multiple_choice',
    options: [
      'tydlighet ... missa',
      'komplexitet ... förutse',
      'enkelhet ... upptäcka',
      'bredd ... begränsa'
    ],
    correctAnswer: 'komplexitet ... förutse',
    explanation: 'Komplex forskning gör långsiktiga konsekvenser svåra att förutse.',
    difficulty: 'medium',
  },
  {
    id: 'mek-b-17',
    sectionCode: 'MEK',
    testVersion: 'mek-b',
    questionNumber: 17,
    questionText: 'Hennes ____ i förhandlingarna ledde till ett ____ resultat för båda parter.',
    questionType: 'multiple_choice',
    options: [
      'aggression ... destruktivt',
      'diplomati ... gynnsamt',
      'naivitet ... katastrofalt',
      'passivitet ... eländigt'
    ],
    correctAnswer: 'diplomati ... gynnsamt',
    explanation: 'Diplomati i förhandlingar leder till gynnsamma resultat.',
    difficulty: 'easy',
  },
  {
    id: 'mek-b-18',
    sectionCode: 'MEK',
    testVersion: 'mek-b',
    questionNumber: 18,
    questionText: 'Den ____ teknologin kommer att ____ hela industrin.',
    questionType: 'multiple_choice',
    options: [
      'föråldrade ... modernisera',
      'banbrytande ... revolutionera',
      'obsoleta ... förbättra',
      'primitiva ... utveckla'
    ],
    correctAnswer: 'banbrytande ... revolutionera',
    explanation: 'Banbrytande teknologi kan revolutionera en industri.',
    difficulty: 'easy',
  },
  {
    id: 'mek-b-19',
    sectionCode: 'MEK',
    testVersion: 'mek-b',
    questionNumber: 19,
    questionText: 'Den ____ debatten förde inte diskussionen framåt utan ____ den snarare.',
    questionType: 'multiple_choice',
    options: [
      'konstruktiva ... utvecklade',
      'polariserade ... låste fast',
      'nyanserade ... förbättrade',
      'objektiva ... klargjorde'
    ],
    correctAnswer: 'polariserade ... låste fast',
    explanation: 'En polariserad debatt låser fast diskussionen istället för att föra den framåt.',
    difficulty: 'hard',
  },
  {
    id: 'mek-b-20',
    sectionCode: 'MEK',
    testVersion: 'mek-b',
    questionNumber: 20,
    questionText: 'Att ____ tidigare misstag är avgörande för att ____ framtida framgång.',
    questionType: 'multiple_choice',
    options: [
      'upprepa ... förhindra',
      'glömma ... uppnå',
      'lära sig av ... säkerställa',
      'ignorera ... garantera'
    ],
    correctAnswer: 'lära sig av ... säkerställa',
    explanation: 'Att lära av misstag hjälper till att säkerställa framgång.',
    difficulty: 'easy',
  },

  // TEST C - MEK (20 nya frågor)
  {
    id: 'mek-c-1',
    sectionCode: 'MEK',
    testVersion: 'mek-c',
    questionNumber: 1,
    questionText: 'Den ____ statistiken fick forskarna att ____ sina ursprungliga hypoteser.',
    questionType: 'multiple_choice',
    options: [
      'förväntade ... bekräfta',
      'överraskande ... ompröva',
      'förutsägbara ... behålla',
      'entydiga ... förkasta'
    ],
    correctAnswer: 'överraskande ... ompröva',
    explanation: 'Överraskande statistik leder till omprövning av hypoteser.',
    difficulty: 'medium',
  },
  {
    id: 'mek-c-2',
    sectionCode: 'MEK',
    testVersion: 'mek-c',
    questionNumber: 2,
    questionText: 'För att ____ konkurrenskraften måste företaget ____ i ny teknologi.',
    questionType: 'multiple_choice',
    options: [
      'förlora ... spara',
      'behålla ... investera',
      'minska ... satsa',
      'stärka ... undvika'
    ],
    correctAnswer: 'behålla ... investera',
    explanation: 'För att behålla konkurrenskraft krävs investeringar i ny teknologi.',
    difficulty: 'easy',
  },
  {
    id: 'mek-c-3',
    sectionCode: 'MEK',
    testVersion: 'mek-c',
    questionNumber: 3,
    questionText: 'Hennes ____ framgång ____ många att följa hennes exempel.',
    questionType: 'multiple_choice',
    options: [
      'misslyckade ... avskräckte',
      'anspråkslösa ... ignorerades av',
      'exceptionella ... inspirerade',
      'tillfälliga ... förvirrade'
    ],
    correctAnswer: 'exceptionella ... inspirerade',
    explanation: 'Exceptionell framgång inspirerar andra att följa.',
    difficulty: 'easy',
  },
  {
    id: 'mek-c-4',
    sectionCode: 'MEK',
    testVersion: 'mek-c',
    questionNumber: 4,
    questionText: 'Den ____ bevisen till trots fortsatte skeptikerna att ____ teorin.',
    questionType: 'multiple_choice',
    options: [
      'svaga ... stödja',
      'övertygande ... ifrågasätta',
      'obefintliga ... acceptera',
      'tydliga ... bevisa'
    ],
    correctAnswer: 'övertygande ... ifrågasätta',
    explanation: 'Trots övertygande bevis fortsätter skeptiker att ifrågasätta.',
    difficulty: 'hard',
  },
  {
    id: 'mek-c-5',
    sectionCode: 'MEK',
    testVersion: 'mek-c',
    questionNumber: 5,
    questionText: 'Budgetens ____ struktur gjorde det svårt att ____ var pengarna skulle användas.',
    questionType: 'multiple_choice',
    options: [
      'tydliga ... missförstå',
      'komplexa ... avgöra',
      'enkla ... förstå',
      'genomskinliga ... gissa'
    ],
    correctAnswer: 'komplexa ... avgöra',
    explanation: 'En komplex budgetstruktur försvårar beslutsfattande.',
    difficulty: 'medium',
  },
  {
    id: 'mek-c-6',
    sectionCode: 'MEK',
    testVersion: 'mek-c',
    questionNumber: 6,
    questionText: 'Miljöproblemen ____ inte längre ____, utan kräver omedelbar handling.',
    questionType: 'multiple_choice',
    options: [
      'är ... brådskande',
      'kan ... ignoreras',
      'behöver ... diskuteras',
      'förblir ... lösta'
    ],
    correctAnswer: 'kan ... ignoreras',
    explanation: 'Miljöproblem kan inte längre ignoreras utan kräver handling.',
    difficulty: 'easy',
  },
  {
    id: 'mek-c-7',
    sectionCode: 'MEK',
    testVersion: 'mek-c',
    questionNumber: 7,
    questionText: 'Hans ____ kunskap inom området gjorde honom till en ____ expert.',
    questionType: 'multiple_choice',
    options: [
      'begränsade ... eftertraktad',
      'ytliga ... erkänd',
      'djupgående ... respekterad',
      'bristande ... ansedd'
    ],
    correctAnswer: 'djupgående ... respekterad',
    explanation: 'Djupgående kunskap leder till respekt som expert.',
    difficulty: 'easy',
  },
  {
    id: 'mek-c-8',
    sectionCode: 'MEK',
    testVersion: 'mek-c',
    questionNumber: 8,
    questionText: 'Den ____ kritiken ____ teamets moral avsevärt.',
    questionType: 'multiple_choice',
    options: [
      'konstruktiva ... stärkte',
      'hårda ... sänkte',
      'positiva ... förbättrade',
      'obefogade ... höjde'
    ],
    correctAnswer: 'hårda ... sänkte',
    explanation: 'Hård kritik sänker teamets moral.',
    difficulty: 'easy',
  },
  {
    id: 'mek-c-9',
    sectionCode: 'MEK',
    testVersion: 'mek-c',
    questionNumber: 9,
    questionText: 'Trots ____ resurser lyckades projektet ____ alla förväntningar.',
    questionType: 'multiple_choice',
    options: [
      'obegränsade ... underprestera',
      'begränsade ... överträffa',
      'rikliga ... misslyckas med',
      'omfattande ... falla under'
    ],
    correctAnswer: 'begränsade ... överträffa',
    explanation: 'Trots begränsade resurser kan man överträffa förväntningar.',
    difficulty: 'medium',
  },
  {
    id: 'mek-c-10',
    sectionCode: 'MEK',
    testVersion: 'mek-c',
    questionNumber: 10,
    questionText: 'Den nya policyn ____ för att ____ jämställdheten på arbetsplatsen.',
    questionType: 'multiple_choice',
    options: [
      'avvisades ... minska',
      'implementerades ... främja',
      'kritiserades ... förhindra',
      'förkastades ... öka'
    ],
    correctAnswer: 'implementerades ... främja',
    explanation: 'Policy implementeras för att främja jämställdhet.',
    difficulty: 'easy',
  },
  {
    id: 'mek-c-11',
    sectionCode: 'MEK',
    testVersion: 'mek-c',
    questionNumber: 11,
    questionText: 'Hennes ____ sätt att presentera komplicerade idéer gjorde dem ____ för alla.',
    questionType: 'multiple_choice',
    options: [
      'förvirrande ... otydliga',
      'pedagogiska ... begripliga',
      'komplicerade ... svåra',
      'långrandiga ... tråkiga'
    ],
    correctAnswer: 'pedagogiska ... begripliga',
    explanation: 'Pedagogisk presentation gör komplexa idéer begripliga.',
    difficulty: 'medium',
  },
  {
    id: 'mek-c-12',
    sectionCode: 'MEK',
    testVersion: 'mek-c',
    questionNumber: 12,
    questionText: 'Den ____ tillväxten under 2000-talet visade sig vara ____ och följdes av en kris.',
    questionType: 'multiple_choice',
    options: [
      'långsamma ... hållbar',
      'snabba ... ohållbar',
      'stabila ... tillfällig',
      'måttliga ... permanent'
    ],
    correctAnswer: 'snabba ... ohållbar',
    explanation: 'Snabb tillväxt kan vara ohållbar och följas av kris.',
    difficulty: 'hard',
  },
  {
    id: 'mek-c-13',
    sectionCode: 'MEK',
    testVersion: 'mek-c',
    questionNumber: 13,
    questionText: 'För att ____ sina mål måste man vara beredd att ____ tillfälliga motgångar.',
    questionType: 'multiple_choice',
    options: [
      'uppge ... glädjas åt',
      'uppnå ... överkomma',
      'undvika ... uppmuntra',
      'förändra ... ignorera'
    ],
    correctAnswer: 'uppnå ... överkomma',
    explanation: 'För att uppnå mål måste man överkomma motgångar.',
    difficulty: 'easy',
  },
  {
    id: 'mek-c-14',
    sectionCode: 'MEK',
    testVersion: 'mek-c',
    questionNumber: 14,
    questionText: 'Den ____ medicinen har revolutionerat behandlingen av tidigare ____ sjukdomar.',
    questionType: 'multiple_choice',
    options: [
      'traditionella ... botbara',
      'moderna ... obotliga',
      'alternativa ... lindriga',
      'föråldrade ... farliga'
    ],
    correctAnswer: 'moderna ... obotliga',
    explanation: 'Modern medicin har revolutionerat behandling av obotliga sjukdomar.',
    difficulty: 'easy',
  },
  {
    id: 'mek-c-15',
    sectionCode: 'MEK',
    testVersion: 'mek-c',
    questionNumber: 15,
    questionText: 'Hans ____ till projektet var ____ för dess framgång.',
    questionType: 'multiple_choice',
    options: [
      'likgiltighet ... avgörande',
      'bidrag ... essentiella',
      'motstånd ... positiva',
      'kritik ... onödiga'
    ],
    correctAnswer: 'bidrag ... essentiella',
    explanation: 'Bidrag kan vara essentiella för projekts framgång.',
    difficulty: 'easy',
  },
  {
    id: 'mek-c-16',
    sectionCode: 'MEK',
    testVersion: 'mek-c',
    questionNumber: 16,
    questionText: 'Den ____ marknaden gör det ____ för små företag att konkurrera.',
    questionType: 'multiple_choice',
    options: [
      'stabila ... lätt',
      'volatila ... utmanande',
      'förutsägbara ... omöjligt',
      'trygga ... svårt'
    ],
    correctAnswer: 'volatila ... utmanande',
    explanation: 'En volatil (föränderlig) marknad är utmanande för små företag.',
    difficulty: 'hard',
  },
  {
    id: 'mek-c-17',
    sectionCode: 'MEK',
    testVersion: 'mek-c',
    questionNumber: 17,
    questionText: 'Studiens ____ resultat ____ tidigare forsknings slutsatser.',
    questionType: 'multiple_choice',
    options: [
      'förväntade ... motsade',
      'överraskande ... bekräftade',
      'negativa ... stödde',
      'positiva ... förkastade'
    ],
    correctAnswer: 'överraskande ... bekräftade',
    explanation: 'Överraskande resultat som bekräftar tidigare forskning är anmärkningsvärt.',
    difficulty: 'medium',
  },
  {
    id: 'mek-c-18',
    sectionCode: 'MEK',
    testVersion: 'mek-c',
    questionNumber: 18,
    questionText: 'Genom att ____ olika perspektiv kan vi ____ en mer nyanserad förståelse.',
    questionType: 'multiple_choice',
    options: [
      'förkasta ... förlora',
      'integrera ... uppnå',
      'ignorera ... få',
      'avvisa ... utveckla'
    ],
    correctAnswer: 'integrera ... uppnå',
    explanation: 'Att integrera olika perspektiv leder till nyanserad förståelse.',
    difficulty: 'easy',
  },
  {
    id: 'mek-c-19',
    sectionCode: 'MEK',
    testVersion: 'mek-c',
    questionNumber: 19,
    questionText: 'Den ____ infrastrukturen ____ landets ekonomiska utveckling.',
    questionType: 'multiple_choice',
    options: [
      'moderna ... hämmar',
      'föråldrade ... bromsar',
      'avancerade ... stoppar',
      'primitiva ... påskyndar'
    ],
    correctAnswer: 'föråldrade ... bromsar',
    explanation: 'Föråldrad infrastruktur bromsar ekonomisk utveckling.',
    difficulty: 'easy',
  },
  {
    id: 'mek-c-20',
    sectionCode: 'MEK',
    testVersion: 'mek-c',
    questionNumber: 20,
    questionText: 'Trots sina ____ insikter lyckades hon inte ____ sina idéer effektivt.',
    questionType: 'multiple_choice',
    options: [
      'briljanta ... kommunicera',
      'bristfälliga ... presentera',
      'banala ... dölja',
      'ytliga ... förmedla'
    ],
    correctAnswer: 'briljanta ... kommunicera',
    explanation: 'Man kan ha briljanta insikter men ändå misslyckas med kommunikation.',
    difficulty: 'medium',
  },
];
