// Theory Hub content — Studietekniker & Provstrategier

import { HPTheoryArticle } from './hp-theory-types';

export const HP_THEORY_TECHNIQUES: HPTheoryArticle[] = [
  {
    id: 'tech-active-recall',
    category: 'study-technique',
    title: 'Active Recall',
    subtitle: 'Testa dig själv i stället för att läsa om',
    emoji: '🧠',
    color: '#8B5CF6',
    gradient: ['#8B5CF6', '#A78BFA'] as const,
    readingMinutes: 5,
    order: 1,
    source: 'local',
    blocks: [
      { type: 'paragraph', text: 'Active recall innebär att aktivt plocka fram kunskap ur minnet i stället för att passivt läsa om den. Det är den mest väldokumenterade studietekniken inom inlärningsforskningen — och den passar högskoleprovet perfekt eftersom provet i sig är ett test.' },
      { type: 'heading', text: 'Varför det fungerar' },
      { type: 'paragraph', text: 'Varje gång du tvingar hjärnan att hämta ett minne stärks minnesspåret. Att läsa om samma sida fem gånger känns produktivt men skapar bara igenkänning — inte förmågan att återkalla under press.' },
      { type: 'heading', text: 'Så använder du det för HP' },
      { type: 'list', items: [
        'ORD: dölj definitionen, säg betydelsen högt, vänd sedan kortet',
        'Matte: lös uppgiften helt innan du kollar facit — även när du är osäker',
        'Efter varje teoripass: stäng texten och skriv ner allt du minns',
        'Förklara ett begrepp (t.ex. normering) för en kompis utan att titta',
      ] },
      { type: 'tip', text: 'Appens flashcards bygger på active recall — svara alltid mentalt INNAN du vänder kortet.' },
    ],
  },
  {
    id: 'tech-spaced-repetition',
    category: 'study-technique',
    title: 'Spaced Repetition',
    subtitle: 'Repetera precis innan du glömmer',
    emoji: '📈',
    color: '#8B5CF6',
    gradient: ['#8B5CF6', '#A78BFA'] as const,
    readingMinutes: 5,
    order: 2,
    source: 'local',
    blocks: [
      { type: 'paragraph', text: 'Glömskekurvan visar att vi tappar upp till 70 % av ny information inom ett dygn — om vi inte repeterar. Spaced repetition lägger repetitionerna med växande intervall: precis när minnet börjar blekna förstärks det, och varje repetition gör minnet mer hållbart.' },
      { type: 'heading', text: 'Intervallen' },
      { type: 'list', items: [
        'Repetition 1: samma dag',
        'Repetition 2: efter 1 dag',
        'Repetition 3: efter 3 dagar',
        'Repetition 4: efter 1 vecka',
        'Repetition 5: efter 2–4 veckor',
      ] },
      { type: 'heading', text: 'För högskoleprovet' },
      { type: 'paragraph', text: 'Tekniken är oslagbar för ORD-ordförråd och engelska glosor, men fungerar också för matteformler och NOG-metodik. Det är därför du inte kan cramma ordförråd sista veckan — utan spridda repetitioner fastnar orden aldrig i långtidsminnet.' },
      { type: 'tip', text: 'Lägg 10 nya ord per dag i flashcards och lita på intervallen. 10 ord/dag i 90 dagar = 900 ord till provet.' },
    ],
  },
  {
    id: 'tech-pomodoro',
    category: 'study-technique',
    title: 'Pomodoro',
    subtitle: '25 minuters fokus i taget',
    emoji: '🍅',
    color: '#8B5CF6',
    gradient: ['#8B5CF6', '#A78BFA'] as const,
    readingMinutes: 4,
    order: 3,
    source: 'local',
    blocks: [
      { type: 'paragraph', text: 'Pomodoro-tekniken delar upp studietiden i fokuserade intervall: 25 minuter arbete, 5 minuters paus. Efter fyra rundor tar du en längre paus på 15–30 minuter. Enkelheten är poängen — det är lätt att börja när åtagandet bara är 25 minuter.' },
      { type: 'heading', text: 'Så kör du ett HP-pass' },
      { type: 'list', ordered: true, items: [
        'Välj EN uppgift: t.ex. "20 ORD-frågor" eller "ett LÄS-textblock"',
        'Mobil i ett annat rum, timer på 25 minuter',
        'Jobba tills timern ringer — inget annat',
        'Paus 5 min: res dig, sträck på dig, INTE sociala medier',
        'Upprepa. Efter 4 rundor: lång paus',
      ] },
      { type: 'paragraph', text: 'Bonus för HP: att träna hjärnan att hålla fokus i bestämda intervall är exakt vad provdagens 55-minuterspass kräver. Öka gärna till 55-minuters "provpass-pomodoros" sista månaden.' },
      { type: 'tip', text: 'Använd appens studietimer för dina pomodoros — då loggas studietiden automatiskt i statistiken.' },
    ],
  },
  {
    id: 'tech-retrieval-practice',
    category: 'study-technique',
    title: 'Retrieval Practice',
    subtitle: 'Öva som du testas — testet ÄR träningen',
    emoji: '🎯',
    color: '#8B5CF6',
    gradient: ['#8B5CF6', '#A78BFA'] as const,
    readingMinutes: 5,
    order: 4,
    source: 'local',
    blocks: [
      { type: 'paragraph', text: 'Retrieval practice är active recalls systerprincip: den mest effektiva förberedelsen inför ett test är att göra testliknande uppgifter. För HP betyder det att gamla prov och övningsfrågor inte är "utvärdering" — de är själva inlärningen.' },
      { type: 'heading', text: 'Testeffekten' },
      { type: 'paragraph', text: 'Forskning visar konsekvent att en grupp som testas på materialet minns mer än en grupp som studerat samma material dubbelt så länge. Misslyckade framplockningsförsök är också värdefulla — de markerar för hjärnan vad som är viktigt.' },
      { type: 'heading', text: 'Praktiskt för HP' },
      { type: 'list', items: [
        'Låt övningsfrågor vara 70–80 % av din totala studietid',
        'Rätta direkt efter passet medan resonemangen är färska',
        'Gör om gamla fel-frågor efter en vecka — kommer du ihåg metoden?',
        'Skriv prov i provformat: 55 minuter, ingen paus, inga hjälpmedel',
      ] },
      { type: 'tip', text: 'Känns övningsfrågorna obekväma? Bra — den ansträngningen är känslan av att hjärnan bygger starkare minnen.' },
    ],
  },
  {
    id: 'tech-interleaving',
    category: 'study-technique',
    title: 'Interleaving',
    subtitle: 'Blanda uppgiftstyper i stället för att beta av block',
    emoji: '🔀',
    color: '#8B5CF6',
    gradient: ['#8B5CF6', '#A78BFA'] as const,
    readingMinutes: 4,
    order: 5,
    source: 'local',
    blocks: [
      { type: 'paragraph', text: 'Interleaving betyder att blanda olika uppgiftstyper inom samma pass i stället för att öva en typ i taget. Det känns svårare och långsammare — men ger markant bättre resultat på testdagen.' },
      { type: 'heading', text: 'Varför det fungerar' },
      { type: 'paragraph', text: 'När du övar i block (20 procentuppgifter i rad) vet du redan vilken metod som ska användas. På provet är första utmaningen att IDENTIFIERA uppgiftstypen. Interleaving tränar just den färdigheten.' },
      { type: 'heading', text: 'Så blandar du för HP' },
      { type: 'list', items: [
        'Kvantpass: blanda XYZ, KVA och NOG i samma övningspass',
        'Verbalpass: varva ORD-frågor med MEK-meningar',
        'Full blandning sista månaden: slumpade frågor ur hela banken',
        'Undantag: när du lär dig en HELT ny metod — öva den i block först, blanda sedan',
      ] },
      { type: 'tip', text: 'Appens blandade övningsläge gör interleaving automatiskt — använd det när grunderna sitter.' },
    ],
  },
  {
    id: 'tech-error-review',
    category: 'study-technique',
    title: 'Felanalys',
    subtitle: 'Dina fel är din snabbaste väg till högre poäng',
    emoji: '🔍',
    color: '#8B5CF6',
    gradient: ['#8B5CF6', '#A78BFA'] as const,
    readingMinutes: 5,
    order: 6,
    source: 'local',
    blocks: [
      { type: 'paragraph', text: 'Skillnaden mellan de som stagnerar och de som förbättras stadigt är nästan alltid felanalysen. Ett fel du förstår är värt mer än tio rätt du redan kunde.' },
      { type: 'heading', text: 'Kategorisera varje fel' },
      { type: 'list', items: [
        'Slarvfel: du kunde, men läste/räknade fel → träna rutiner och kontroll',
        'Tidsfel: du hann inte → träna tempo och hoppa-vidare-disciplin',
        'Metodfel: du valde fel angreppssätt → studera lösningen, gör om utan facit',
        'Kunskapslucka: du saknade ordet/formeln → lägg i flashcards',
      ] },
      { type: 'heading', text: 'Felloggen' },
      { type: 'paragraph', text: 'För en enkel logg: fråga, feltyp, rätt metod i en mening. Läs igenom loggen varje söndag. Mönstren du ser där — "jag slarvar alltid på negativa tal", "jag faller för extrema LÄS-alternativ" — är din personliga studieplan.' },
      { type: 'tip', text: 'Gör om veckans fel-frågor utan facit i slutet av veckan. Rätt då = metoden sitter.' },
    ],
  },
  {
    id: 'tech-exam-simulation',
    category: 'study-technique',
    title: 'Provsimulering',
    subtitle: 'Träna hela provdagen — inte bara frågorna',
    emoji: '⏱️',
    color: '#8B5CF6',
    gradient: ['#8B5CF6', '#A78BFA'] as const,
    readingMinutes: 5,
    order: 7,
    source: 'local',
    blocks: [
      { type: 'paragraph', text: 'Högskoleprovet är åtta timmar långt. Många presterar bra på enskilda övningspass men tappar sista provpassen på riktiga provet — för att de aldrig tränat uthålligheten. Provsimulering betyder att återskapa provdagen så exakt som möjligt.' },
      { type: 'heading', text: 'Så simulerar du' },
      { type: 'list', items: [
        'Skriv ett helt gammalt prov med exakta tider: 55 min/pass, korrekta pauser',
        'Börja 08:10 som på riktigt — träna även morgonrutinen',
        'Inga hjälpmedel, ingen mobil, samma lunch du planerar på provdagen',
        'Rätta efteråt och gör full felanalys per delprov',
      ] },
      { type: 'heading', text: 'Hur ofta?' },
      { type: 'paragraph', text: 'Minst 3–4 hela simuleringar före provdagen, varav en tidigt (baslinje) och en–två under sista månaden. Mellan simuleringarna: riktad träning på svagheterna de avslöjade.' },
      { type: 'tip', text: 'Simuleringens poäng brukar ligga nära det riktiga resultatet — använd den för att kalibrera ditt mål.' },
    ],
  },
  {
    id: 'tech-time-blocking',
    category: 'study-technique',
    title: 'Time Blocking',
    subtitle: 'Schemalägg pluggpassen som möten',
    emoji: '📅',
    color: '#8B5CF6',
    gradient: ['#8B5CF6', '#A78BFA'] as const,
    readingMinutes: 4,
    order: 8,
    source: 'local',
    blocks: [
      { type: 'paragraph', text: 'Time blocking innebär att du i förväg bokar in exakt när, var och vad du ska plugga — som möten i kalendern. "Jag pluggar när jag hinner" blir i praktiken "jag pluggar aldrig".' },
      { type: 'heading', text: 'Så bygger du ditt schema' },
      { type: 'list', items: [
        'Söndag kväll: boka veckans pass i kalendern med innehåll ("tis 17–18: KVA + 10 ord")',
        'Koppla passen till befintliga rutiner: efter frukost, direkt efter skolan',
        'Korta vardagspass (30–60 min) + ett längre helgpass',
        'Skydda blocken: mobil i annat rum, säg nej till krockar',
      ] },
      { type: 'paragraph', text: 'Poängen är att flytta beslutet från stunden (när viljestyrkan är svag) till planeringen (när den är stark). Du ska aldrig behöva fråga dig "ska jag plugga nu?" — schemat har redan svarat.' },
      { type: 'tip', text: 'Missat pass? Flytta det — stryk det inte. Skillnaden avgör om schemat överlever kontakt med verkligheten.' },
    ],
  },
];

export const HP_THEORY_EXAM_STRATEGIES: HPTheoryArticle[] = [
  {
    id: 'strat-time-management',
    category: 'exam-strategy',
    title: 'Tidsstrategi under provet',
    subtitle: 'Tiden är provets verkliga motståndare',
    emoji: '⏳',
    color: '#EC4899',
    gradient: ['#EC4899', '#F472B6'] as const,
    readingMinutes: 6,
    order: 1,
    source: 'local',
    blocks: [
      { type: 'paragraph', text: 'Nästan ingen blir "klar" med högskoleprovet. Skillnaden mellan 1.0 och 1.5 handlar ofta inte om kunskap utan om hur klokt tiden fördelas. Varje fråga är värd exakt lika mycket — tidsstrategin ska spegla det.' },
      { type: 'heading', text: 'Grundprinciper' },
      { type: 'list', items: [
        'Räkna ut din tid per fråga i förväg (55 min / antal frågor) och känn tempot i kroppen',
        'Lägg lätta frågor först: skörda alla säkra poäng innan du bränner tid på svåra',
        'Sätt en personlig maxgräns per fråga (ca 90 sek på kvant) — sedan: chansa, markera, vidare',
        'Spara 2–3 minuter i slutet för att fylla i gissningar på allt obesvarat',
      ] },
      { type: 'heading', text: 'Checkpoints' },
      { type: 'paragraph', text: 'Dela in passet i tredjedelar och kontrollera klockan vid varje: efter en tredjedel av tiden bör ungefär en tredjedel av frågorna vara gjorda. Ligger du efter — höj tempot på lätta frågor, inte kvaliteten på svåra.' },
      { type: 'warning', text: 'Fastna aldrig i prestige mot en enskild fråga. Tre minuter på en omöjlig fråga = tre lätta poäng någon annanstans som aldrig hanns med.' },
    ],
  },
  {
    id: 'strat-skip-guess',
    category: 'exam-strategy',
    title: 'Hoppa och chansa rätt',
    subtitle: 'Vilka frågor du släpper avgör din poäng',
    emoji: '🎲',
    color: '#EC4899',
    gradient: ['#EC4899', '#F472B6'] as const,
    readingMinutes: 5,
    order: 2,
    source: 'local',
    blocks: [
      { type: 'heading', text: 'När ska du hoppa?' },
      { type: 'list', items: [
        'Direkt när du inser att frågan kräver en metod du inte kan',
        'När du läst frågan två gånger utan att förstå vad som efterfrågas',
        'När din lösning växer och du passerat din maxtid',
      ] },
      { type: 'paragraph', text: 'Markera överhopppade frågor tydligt och återvänd i slutet av passet. Ofta lossnar de på andra försöket när stressen släppt.' },
      { type: 'heading', text: 'Konsten att chansa' },
      { type: 'list', items: [
        'Inga minuspoäng: lämna ALDRIG en fråga tom',
        'Eliminera först: varje struket alternativ höjer chansen dramatiskt (20 % → 25 % → 33 % → 50 %)',
        'På kvant: uppskatta storleksordningen och stryk orimliga alternativ',
        'På LÄS/ELF: stryk extrema påståenden ("alltid", "aldrig") och det som saknar stöd i texten',
        'Ingen tid kvar? Välj en bokstav och fyll i samma på allt obesvarat — bättre än slumpvis hattande',
      ] },
      { type: 'tip', text: 'Öva hoppandet under träning. Disciplinen att släppa en fråga är en färdighet — inte ett misslyckande.' },
    ],
  },
  {
    id: 'strat-reading-efficiency',
    category: 'exam-strategy',
    title: 'Läs effektivt under provet',
    subtitle: 'Skumma, skanna och djupläs — vid rätt tillfällen',
    emoji: '👀',
    color: '#EC4899',
    gradient: ['#EC4899', '#F472B6'] as const,
    readingMinutes: 5,
    order: 3,
    source: 'local',
    blocks: [
      { type: 'paragraph', text: 'Provets verbala del är i praktiken ett lästempotest. Konsten är att växla mellan tre läslägen och välja rätt läge för rätt moment.' },
      { type: 'heading', text: 'De tre läslägena' },
      { type: 'list', items: [
        'Skumma (skimming): läs första meningen i varje stycke för att fånga struktur och huvudbudskap',
        'Skanna (scanning): leta efter specifika ord, namn eller siffror när en fråga pekar på en detalj',
        'Djupläs: långsam och noggrann läsning — bara av de meningar som avgör svaret',
      ] },
      { type: 'heading', text: 'Arbetsflöde för LÄS och ELF' },
      { type: 'list', ordered: true, items: [
        'Skumma frågorna (inte alternativen) — 15 sekunder',
        'Skumma texten för helheten — 1,5–2 minuter',
        'Per fråga: skanna dig till rätt del av texten, djupläs där',
        'Detaljfrågor med radhänvisning: gå direkt, läs även meningen före och efter',
      ] },
      { type: 'warning', text: 'Undvik dubbelfel: att läsa hela texten på djupet OCH sedan läsa om allt per fråga. Då tar en text dubbel tid.' },
      { type: 'tip', text: 'Träna aktiv läsning dagligen: sammanfatta varje stycke du läser i huvudet med fem ord.' },
    ],
  },
  {
    id: 'strat-pressure-focus',
    category: 'exam-strategy',
    title: 'Prestera under press',
    subtitle: 'Behåll skärpan genom åtta timmars prov',
    emoji: '🧊',
    color: '#EC4899',
    gradient: ['#EC4899', '#F472B6'] as const,
    readingMinutes: 6,
    order: 4,
    source: 'local',
    blocks: [
      { type: 'heading', text: 'När paniken kommer' },
      { type: 'list', ordered: true, items: [
        'Lägg pennan. Andas: 4 sekunder in, 6 sekunder ut, tre gånger',
        'Påminn dig: en svår fråga är värd lika lite som en lätt — släpp den',
        'Gå till nästa fråga du KAN — ett snabbt rätt återställer självförtroendet',
        'Återvänd till den svåra frågan sist, om tid finns',
      ] },
      { type: 'heading', text: 'Fokus över hela dagen' },
      { type: 'list', items: [
        'Mellan passen: res dig, gå, ät något litet — sitt inte kvar och älta',
        'Nollställ efter varje pass: det förra passets resultat är utom din kontroll',
        'Drick vatten regelbundet — mild uttorkning sänker koncentrationen mätbart',
        'Mikropauser i passet: 5 sekunder, blunda, rulla axlarna, fortsätt',
      ] },
      { type: 'heading', text: 'Tankefällor' },
      { type: 'paragraph', text: '"Alla andra bläddrar snabbare än jag" — de gissar också mer. "Det där passet sabbade allt" — normeringen jämför dig med alla andra som skrev samma svåra pass. Din enda uppgift är nästa fråga.' },
      { type: 'tip', text: 'Stresstålighet tränas bäst i förväg: ju fler tidspressade simuleringar du gjort, desto mer vardag känns provdagen.' },
    ],
  },
  {
    id: 'strat-avoid-mistakes',
    category: 'exam-strategy',
    title: 'Undvik onödiga fel',
    subtitle: 'Slarvfelen kostar mest — och är enklast att fixa',
    emoji: '🛡️',
    color: '#EC4899',
    gradient: ['#EC4899', '#F472B6'] as const,
    readingMinutes: 5,
    order: 5,
    source: 'local',
    blocks: [
      { type: 'paragraph', text: 'De flesta tappar 3–8 poäng per prov på frågor de egentligen kunde. Slarvfel går inte att plugga bort — de byggs bort med rutiner.' },
      { type: 'heading', text: 'Rutinerna som räddar poäng' },
      { type: 'list', items: [
        'Läs frågan KLART innan du tittar på alternativen — särskilt "vilket alternativ stämmer INTE"',
        'Kvant: kontrollera enheten (kr? %? cm²?) innan du väljer svar',
        'DTK: peka fysiskt på rätt stapel/rad/år innan du räknar',
        'NOG: testa alltid påståendena i strikt isolering först',
        'KVA: testa 0, 1, negativt tal och bråk innan du svarar "alltid"',
        'Rimlighetskolla: kan en cykel kosta 78 000 kr? Kan en andel vara 130 %?',
      ] },
      { type: 'heading', text: 'Svarsblanketten' },
      { type: 'paragraph', text: 'Kontrollera var femte fråga att frågenummer och raden på svarsblanketten stämmer. Ett hopp i numreringen kan annars förskjuta alla efterföljande svar.' },
      { type: 'warning', text: 'Vid tidsbrist ökar slarvfelen exponentiellt. Hellre lugnt tempo med gissningar på slutet än paniktempo med fel på frågor du kunde.' },
      { type: 'tip', text: 'Kartlägg dina personliga slarvmönster i felloggen — de flesta har 2–3 återkommande typer som står för nästan alla tappade poäng.' },
    ],
  },
];
