// Theory Hub content — Delprovsguider (one mini-course per HP section)

import { HPTheoryArticle } from './hp-theory-types';

export const HP_THEORY_SECTIONS: HPTheoryArticle[] = [
  {
    id: 'guide-ord',
    category: 'section-guide',
    sectionCode: 'ORD',
    title: 'ORD — Ordförståelse',
    subtitle: 'Bygg ordförrådet som ger snabba, säkra poäng',
    emoji: '📚',
    color: '#6366F1',
    gradient: ['#6366F1', '#8B5CF6'] as const,
    readingMinutes: 8,
    order: 1,
    source: 'local',
    blocks: [
      { type: 'heading', text: 'Vad mäter delprovet?' },
      { type: 'paragraph', text: 'ORD testar bredden och djupet i ditt svenska ordförråd: 10 uppgifter där du ska hitta ordet eller frasen som bäst motsvarar ett givet ord. Det är provets snabbaste delprov — antingen kan du ordet eller inte — vilket gör det till provets mest träningsbara poängkälla.' },
      { type: 'heading', text: 'Ordens ursprung är din genväg' },
      { type: 'paragraph', text: 'En stor del av HP-orden är lånord med latinska eller grekiska rötter. Lär du dig de vanligaste stammarna, prefixen och suffixen kan du gissa kvalificerat även på ord du aldrig sett.' },
      { type: 'list', items: [
        'bene- (lat.) = väl, bra → benägen, benefik',
        'mal- (lat.) = dålig → malplacerad, malör',
        'dys- (grek.) = svår, dålig → dysfunktion, dystopi',
        'eu- (grek.) = god, bra → eufori, eufemism',
        '-tomi (grek.) = skärning → dikotomi, anatomi',
        'ambi-/ambo- (lat.) = båda → ambivalent',
      ] },
      { type: 'heading', text: 'Strategier och minnestekniker' },
      { type: 'list', items: [
        'Lär dig 10–20 nya ord per dag med flashcards och spaced repetition',
        'Skapa bilder och associationer: "efemär" → en dagslända som lever en dag',
        'Läs kvalitetstext (DN, SvD, essäer) och slå upp varje okänt ord',
        'Öva på uteslutningsmetoden: även två eliminerade alternativ höjer gissningschansen från 20 till 33 %',
      ] },
      { type: 'heading', text: 'Typiska misstag' },
      { type: 'list', items: [
        'Att välja ett ord som "låter likt" i stället för betydelsen (falska vänner)',
        'Att lägga för mycket tid — ORD ska gå snabbt så att LÄS får mer tid',
        'Att börja plugga ord sista veckan — ordförråd kräver månader',
      ] },
      { type: 'example', title: 'Exempeluppgift', question: 'Vad betyder "eftergiven"?', options: ['Bestämd', 'Undfallande', 'Frikostig', 'Trött', 'Långsam'], answer: 'Undfallande', explanation: 'Eftergiven betyder att lätt ge efter för andras vilja — alltså undfallande. "Frikostig" är en klassisk fälla som låter positiv men betyder generös.' },
      { type: 'tip', text: 'Träna ORD dagligen i appens flashcards — 10 minuter om dagen slår 2 timmar en gång i veckan.' },
    ],
  },
  {
    id: 'guide-las',
    category: 'section-guide',
    sectionCode: 'LÄS',
    title: 'LÄS — Läsförståelse',
    subtitle: 'Läs smartare, inte långsammare',
    emoji: '📖',
    color: '#10B981',
    gradient: ['#10B981', '#059669'] as const,
    readingMinutes: 8,
    order: 2,
    source: 'local',
    blocks: [
      { type: 'heading', text: 'Vad mäter delprovet?' },
      { type: 'paragraph', text: 'LÄS testar din förmåga att förstå, tolka och dra slutsatser ur längre svenska sakprosatexter. Du får fyra texter med totalt 20 frågor. Utmaningen är sällan att förstå — det är tiden.' },
      { type: 'heading', text: 'Lässtrategin som fungerar' },
      { type: 'list', ordered: true, items: [
        'Skumma frågorna först (10–15 sek) så du vet vad du letar efter',
        'Läs texten aktivt: markera mentalt tes, argument och nyanseringar',
        'Besvara textnära frågor direkt; spara tolkningsfrågor till sist',
        'Svara ALLTID utifrån texten — inte din egen kunskap eller åsikt',
      ] },
      { type: 'heading', text: 'Så känner du igen rätt svar' },
      { type: 'list', items: [
        'Rätt svar är ofta en omformulering av texten, inte ett ordagrant citat',
        'Fel svar är ofta för extrema: "alltid", "aldrig", "helt omöjligt"',
        'Fel svar kan vara sanna i verkligheten men sakna stöd i texten',
        'Nyanserande ord som "delvis", "kan", "tycks" finns ofta i rätt svar',
      ] },
      { type: 'heading', text: 'Bygg läshastighet långsiktigt' },
      { type: 'paragraph', text: 'Läs 20–30 minuter kvalificerad sakprosa varje dag: ledare, essäer, forskningsartiklar. Läshastighet och textvana är LÄS-delens motsvarighet till ordförråd — den byggs över månader.' },
      { type: 'warning', text: 'Vanligaste misstaget: att läsa texten för noggrant första gången och få panik när tiden tar slut. Sikta på 80 % förståelse på första genomläsningen.' },
      { type: 'tip', text: 'Under övning: logga tid per text. Målet är ca 8 minuter per text inklusive frågor.' },
    ],
  },
  {
    id: 'guide-mek',
    category: 'section-guide',
    sectionCode: 'MEK',
    title: 'MEK — Meningskomplettering',
    subtitle: 'Hitta ledtrådarna som avslöjar rätt ord',
    emoji: '✏️',
    color: '#F59E0B',
    gradient: ['#F59E0B', '#D97706'] as const,
    readingMinutes: 7,
    order: 3,
    source: 'local',
    blocks: [
      { type: 'heading', text: 'Vad mäter delprovet?' },
      { type: 'paragraph', text: 'MEK testar ordförråd i kontext: meningar med en eller två luckor där du väljer det alternativ som passar bäst. Till skillnad från ORD räcker det inte att kunna orden — du måste läsa meningens logik.' },
      { type: 'heading', text: 'Signalorden styr allt' },
      { type: 'list', items: [
        'Kontrast: "trots", "men", "även om", "visserligen … men" → luckan går MOT resten',
        'Konsekvens: "därför", "följaktligen", "så att" → luckan följer logiskt',
        'Förstärkning: "dessutom", "till och med", "inte minst" → samma riktning, starkare',
        'Orsak: "eftersom", "på grund av" → luckan förklarar',
      ] },
      { type: 'heading', text: 'Strategi för dubbelluckor' },
      { type: 'paragraph', text: 'Vid två luckor: lös den lucka du är säkrast på först och eliminera alla alternativ som inte stämmer där. Ofta räcker en lucka för att stryka tre alternativ.' },
      { type: 'heading', text: 'Typiska misstag' },
      { type: 'list', items: [
        'Att välja ett ord som låter avancerat i stället för det som passar logiken',
        'Att ignorera det lilla signalordet som vänder hela meningen',
        'Att inte läsa om hela meningen med sitt val insatt — gör alltid det',
      ] },
      { type: 'example', title: 'Exempeluppgift', question: 'Kritiken var hård, ____ valde förlaget att ge ut boken.', options: ['därför', 'likväl', 'eftersom', 'följaktligen'], answer: 'likväl', explanation: '"Likväl" uttrycker kontrast: trots hård kritik gavs boken ut. Orsaks- och konsekvensorden går åt fel håll.' },
      { type: 'tip', text: 'Träna på att stryka under signalord i varje MEK-uppgift tills det blir en reflex.' },
    ],
  },
  {
    id: 'guide-elf',
    category: 'section-guide',
    sectionCode: 'ELF',
    title: 'ELF — Engelsk läsförståelse',
    subtitle: 'Samma logik som LÄS — fast på engelska',
    emoji: '🇬🇧',
    color: '#8B5CF6',
    gradient: ['#8B5CF6', '#7C3AED'] as const,
    readingMinutes: 7,
    order: 4,
    source: 'local',
    blocks: [
      { type: 'heading', text: 'Vad mäter delprovet?' },
      { type: 'paragraph', text: 'ELF testar läsförståelse på engelska med både längre texter och kortare luckuppgifter. Frågetyperna liknar LÄS: huvudbudskap, detaljer, ordbetydelse i kontext och slutsatser.' },
      { type: 'heading', text: 'Strategier' },
      { type: 'list', items: [
        'Skumma texten först för helhetsbilden — fastna inte på enskilda ord',
        'Okända ord: gissa betydelsen ur sammanhanget, gå vidare',
        '"Closest in meaning"-frågor: testa alternativen i meningen och känn vilket som bevarar betydelsen',
        'Svaret ska ha stöd i texten — precis som i LÄS',
      ] },
      { type: 'heading', text: 'Bygg engelskan långsiktigt' },
      { type: 'list', items: [
        'Konsumera engelska dagligen: podcasts, dokumentärer, artiklar (The Guardian, BBC, The Atlantic)',
        'Läs facklitteratur — HP-texterna är sakprosa, inte skönlitteratur',
        'Lär dig akademiska signalord: however, moreover, albeit, notwithstanding',
      ] },
      { type: 'warning', text: 'Vanligaste misstaget: att översätta ord för ord i huvudet. Träna på att förstå direkt på engelska — det halverar din lästid.' },
      { type: 'tip', text: 'Byt språket på mobilen och sociala medier till engelska. Gratis exponering varje dag.' },
    ],
  },
  {
    id: 'guide-xyz',
    category: 'section-guide',
    sectionCode: 'XYZ',
    title: 'XYZ — Matematisk problemlösning',
    subtitle: 'Gymnasiematte under tidspress',
    emoji: '🔣',
    color: '#EC4899',
    gradient: ['#EC4899', '#DB2777'] as const,
    readingMinutes: 8,
    order: 5,
    source: 'local',
    blocks: [
      { type: 'heading', text: 'Vad mäter delprovet?' },
      { type: 'paragraph', text: 'XYZ är klassiska matematikuppgifter: aritmetik, algebra, geometri, statistik och funktioner på grundskole- och gymnasienivå (upp till Ma2). Svårigheten ligger inte i avancerad matte utan i att lösa snabbt och säkert.' },
      { type: 'heading', text: 'Områdena du måste behärska' },
      { type: 'list', items: [
        'Procent och förändringsfaktor (störst utdelning per pluggtimme!)',
        'Ekvationer och olikheter',
        'Geometri: areor, omkrets, Pythagoras, likformighet, vinklar',
        'Bråk, potenser och prioriteringsregler',
        'Medelvärde, median och enkel sannolikhet',
        'Hastighet-sträcka-tid och proportionalitet',
      ] },
      { type: 'heading', text: 'Lösningsstrategier' },
      { type: 'list', items: [
        'Uppskatta först: en grov överslagsräkning eliminerar ofta 2–3 alternativ',
        'Testa svarsalternativen baklänges när ekvationen känns krånglig',
        'Rita! Geometri- och andelsproblem löser nästan sig själva med en figur',
        'Sätt in enkla tal (2, 10, 100) i uppgifter med variabler',
      ] },
      { type: 'example', title: 'Exempeluppgift', question: 'Ett pris höjs med 25 % och sänks sedan med 20 %. Hur förändrades priset totalt?', options: ['+5 %', '0 %', '−5 %', '+10 %'], answer: '0 %', explanation: 'Förändringsfaktorer: 1,25 × 0,80 = 1,00. Priset är oförändrat. Procentsatser adderas inte!' },
      { type: 'warning', text: 'Ingen miniräknare är tillåten. Träna alltid huvudräkning och uppställning på papper.' },
      { type: 'tip', text: 'Gör om varje fel uppgift utan facit dagen efter. Kan du lösa den då äger du metoden.' },
    ],
  },
  {
    id: 'guide-kva',
    category: 'section-guide',
    sectionCode: 'KVA',
    title: 'KVA — Kvantitativa jämförelser',
    subtitle: 'Jämför smart — räkna bara när du måste',
    emoji: '🔢',
    color: '#06B6D4',
    gradient: ['#06B6D4', '#0891B2'] as const,
    readingMinutes: 7,
    order: 6,
    source: 'local',
    blocks: [
      { type: 'heading', text: 'Vad mäter delprovet?' },
      { type: 'paragraph', text: 'KVA visar två kvantiteter, I och II, och du avgör vilken som är störst — eller om de är lika eller om informationen inte räcker. Formatet belönar logik framför räknande: ofta går uppgiften att lösa utan att räkna klart.' },
      { type: 'heading', text: 'Den avgörande frågan: "gäller det ALLTID?"' },
      { type: 'paragraph', text: 'Svaret "I är större" betyder att I är större för ALLA tillåtna värden. Hittar du ett enda motexempel är svaret i stället "informationen är otillräcklig". Detta är hela delprovets kärna.' },
      { type: 'heading', text: 'Testvärdena som avslöjar det mesta' },
      { type: 'list', items: [
        'Testa alltid: 0, 1, ett negativt tal och ett bråk mellan 0 och 1',
        'x² < x när 0 < x < 1 — klassisk fälla',
        'Negativa tal vänder olikheter vid multiplikation',
        'Om två testvärden ger olika relation → otillräcklig information',
      ] },
      { type: 'example', title: 'Exempeluppgift', question: 'x är ett tal. Kvantitet I: x². Kvantitet II: x.', options: ['I är större', 'II är större', 'Lika', 'Otillräcklig information'], answer: 'Otillräcklig information', explanation: 'x = 2 ger I > II, men x = 0,5 ger I < II. Relationen varierar — informationen räcker inte.' },
      { type: 'warning', text: 'Missa aldrig villkoren ovanför kvantiteterna (t.ex. "x > 0"). De ändrar ofta hela svaret.' },
      { type: 'tip', text: 'KVA är provets snabbaste kvantdelprov när tekniken sitter — träna tills testvärdena blir en reflex.' },
    ],
  },
  {
    id: 'guide-nog',
    category: 'section-guide',
    sectionCode: 'NOG',
    title: 'NOG — Begreppet nog',
    subtitle: 'Fråga inte vad svaret är — fråga om det GÅR att svara',
    emoji: '🔍',
    color: '#14B8A6',
    gradient: ['#14B8A6', '#0D9488'] as const,
    readingMinutes: 8,
    order: 7,
    source: 'local',
    blocks: [
      { type: 'heading', text: 'Vad mäter delprovet?' },
      { type: 'paragraph', text: 'NOG ger dig en fråga och två påståenden, (1) och (2). Din uppgift är inte att räkna ut svaret utan att avgöra vilken information som är TILLRÄCKLIG. Det är provets mest ovana format — och därför det mest träningsbara.' },
      { type: 'heading', text: 'Den systematiska metoden' },
      { type: 'list', ordered: true, items: [
        'Testa påstående (1) HELT ensamt. Räcker det? Anteckna ja/nej.',
        'Glöm (1) helt. Testa påstående (2) ensamt. Räcker det?',
        'Endast om båda var otillräckliga ensamma: testa dem tillsammans.',
        'Matcha resultatet mot svarsalternativen.',
      ] },
      { type: 'warning', text: 'Det vanligaste felet i hela provet: att låta information från (1) "läcka" när du prövar (2). Var stenhård — varje påstående testas i total isolering först.' },
      { type: 'heading', text: 'Nycklar och fällor' },
      { type: 'list', items: [
        'Du behöver inte räkna ut svaret — bara veta att det GÅR att räkna ut entydigt',
        'En ekvation med två okända räcker inte ensam',
        '"Tillräcklig" kräver ETT entydigt svar — två möjliga värden = otillräcklig',
        'Kvadratrötter: x² = 25 ger x = ±5 → inte entydigt utan fler villkor',
      ] },
      { type: 'example', title: 'Exempeluppgift', question: 'Vilket är talet n?\n(1) n är ett jämnt tal mellan 3 och 7.\n(2) n är delbart med 3.', answer: '(1) och (2) tillsammans är tillräckliga', explanation: '(1) ensamt: n kan vara 4 eller 6 — otillräckligt. (2) ensamt: oändligt många tal — otillräckligt. Tillsammans: bara 6 uppfyller båda. Tillräckligt!' },
      { type: 'tip', text: 'Skriv bokstäverna 1️⃣ och 2️⃣ i marginalen och bocka av varje steg — strukturen räddar dig under stress.' },
    ],
  },
  {
    id: 'guide-dtk',
    category: 'section-guide',
    sectionCode: 'DTK',
    title: 'DTK — Diagram, tabeller & kartor',
    subtitle: 'Läs av data snabbt och räkna rätt saker',
    emoji: '📈',
    color: '#EF4444',
    gradient: ['#EF4444', '#DC2626'] as const,
    readingMinutes: 7,
    order: 8,
    source: 'local',
    blocks: [
      { type: 'heading', text: 'Vad mäter delprovet?' },
      { type: 'paragraph', text: 'DTK testar din förmåga att tolka verklig statistik: diagram, tabeller och kartor med tillhörande frågor. Delprovet kombinerar avläsning, procenträkning och överslagsräkning — ofta under störst tidspress av alla kvantdelprov.' },
      { type: 'heading', text: 'Avläsningsrutinen (15 sekunder som räddar minuter)' },
      { type: 'list', ordered: true, items: [
        'Läs rubriken — vad visar figuren egentligen?',
        'Kolla enheterna: tusental? procent? index? per capita?',
        'Kolla axlarna och skalan — börjar y-axeln på 0?',
        'Läs eventuella fotnoter — de innehåller ofta nyckeln',
      ] },
      { type: 'heading', text: 'Räknestrategier' },
      { type: 'list', items: [
        'Överslagsräkna först — svarsalternativen ligger ofta långt isär',
        'Procentuell förändring: (nytt − gammalt) / gammalt',
        'Skilj procentenheter från procent: 10 % → 15 % är +5 procentenheter men +50 %',
        'Vid flera figurer: kontrollera vilken figur frågan faktiskt gäller',
      ] },
      { type: 'warning', text: 'Klassisk fälla: att räkna på fel år, fel land eller fel stapel. Peka fysiskt på rätt rad/stapel innan du räknar.' },
      { type: 'tip', text: 'Träna på att läsa SCB-statistik och nyhetsgrafik — samma figurer som DTK bygger på.' },
    ],
  },
];
