// Theory Hub content — Introduktion & Nå toppresultat
// Pure data rendered by generic components. New articles can be added here or
// imported from Supabase without UI changes.

import { HPTheoryArticle } from './hp-theory-types';

export const HP_THEORY_INTRO: HPTheoryArticle[] = [
  {
    id: 'intro-what-is-hp',
    category: 'intro',
    title: 'Vad är Högskoleprovet?',
    subtitle: 'Grunderna: upplägg, delar och varför provet finns',
    emoji: '🎓',
    color: '#6366F1',
    gradient: ['#6366F1', '#8B5CF6'] as const,
    readingMinutes: 5,
    order: 1,
    source: 'local',
    blocks: [
      { type: 'paragraph', text: 'Högskoleprovet (HP) är ett nationellt urvalsprov som ger dig en andra väg in till högskolan, vid sidan av dina gymnasiebetyg. Provet mäter kunskaper och färdigheter som är viktiga för högskolestudier — inte vad du pluggat i en specifik kurs.' },
      { type: 'heading', text: 'Provets uppbyggnad' },
      { type: 'paragraph', text: 'Provet består av 160 uppgifter fördelade på fem provpass under en heldag. Fyra provpass räknas — två verbala och två kvantitativa — samt ett utprövningspass som inte påverkar ditt resultat.' },
      { type: 'list', items: [
        'Verbal del (ORD, LÄS, MEK, ELF) — 80 uppgifter om språk och läsning',
        'Kvantitativ del (XYZ, KVA, NOG, DTK) — 80 uppgifter om matematik och logik',
        'Varje provpass är 55 minuter',
      ] },
      { type: 'heading', text: 'Vem får skriva provet?' },
      { type: 'paragraph', text: 'Alla som fyllt 18 år (eller går sista året på gymnasiet) kan anmäla sig. Det finns ingen övre gräns för hur många gånger du får skriva — och ditt bästa resultat är det som räknas. Resultatet är giltigt i 8 år.' },
      { type: 'tip', text: 'Eftersom bara ditt bästa resultat räknas finns det nästan ingen nackdel med att skriva provet flera gånger. Se första försöket som träning!' },
      { type: 'stat', value: '160', label: 'uppgifter på en provdag' },
    ],
  },
  {
    id: 'intro-why-take-hp',
    category: 'intro',
    title: 'Varför skriva provet?',
    subtitle: 'Din andra chans in på drömutbildningen',
    emoji: '🚪',
    color: '#6366F1',
    gradient: ['#6366F1', '#8B5CF6'] as const,
    readingMinutes: 4,
    order: 2,
    source: 'local',
    blocks: [
      { type: 'paragraph', text: 'Minst en tredjedel av platserna på varje högskoleutbildning måste tillsättas via högskoleprovsurvalet. Det betyder att du konkurrerar i en helt egen kvot — oberoende av dina betyg.' },
      { type: 'heading', text: 'Fyra starka skäl' },
      { type: 'list', items: [
        'Betygen räcker inte: populära utbildningar som läkare, jurist och psykolog kräver ofta över 21.5 i betygssnitt — men går att nå med ett bra HP-resultat.',
        'Du kan inte sänka dig: ett dåligt resultat påverkar aldrig dina chanser via betygskvoten.',
        'Flera försök: provet ges två gånger per år och bästa resultatet gäller i 8 år.',
        'Träningsbart: till skillnad från betyg som är låsta kan HP-resultatet alltid förbättras.',
      ] },
      { type: 'tip', text: 'Även om du har bra betyg är HP en gratis extrachans. Många kommer in på sitt förstahandsval via HP-kvoten trots lägre betyg än betygsantagningens gräns.' },
      { type: 'stat', value: '1/3', label: 'av platserna tillsätts via HP-kvoten' },
    ],
  },
  {
    id: 'intro-scoring',
    category: 'intro',
    title: 'Poäng och normering',
    subtitle: 'Så räknas ditt resultat ut — från råpoäng till 0.0–2.0',
    emoji: '🧮',
    color: '#6366F1',
    gradient: ['#6366F1', '#8B5CF6'] as const,
    readingMinutes: 6,
    order: 3,
    source: 'local',
    blocks: [
      { type: 'heading', text: 'Från rätta svar till normerad poäng' },
      { type: 'paragraph', text: 'Ditt antal rätta svar kallas råpoäng. Råpoängen översätts sedan till en normerad poäng på skalan 0.0 till 2.0, i steg om 0.05. Normeringen gör att resultat från olika provtillfällen kan jämföras rättvist, även om provens svårighetsgrad varierar.' },
      { type: 'heading', text: 'Hur fungerar normeringen?' },
      { type: 'paragraph', text: 'Efter varje prov analyseras hur alla deltagare presterat. Om ett prov var svårare än vanligt krävs färre rätt för samma normerade poäng — och tvärtom. Verbal och kvantitativ del normeras var för sig och slås sedan ihop till ditt slutresultat.' },
      { type: 'list', items: [
        'Ca 120–130 rätt av 160 brukar krävas för 2.0',
        'Ca 80–90 rätt ger ofta runt 1.0–1.2',
        'Genomsnittsresultatet ligger runt 0.85–0.95',
        'Inga minuspoäng — fel svar räknas som 0',
      ] },
      { type: 'warning', text: 'Exakta gränser varierar mellan provtillfällen. Sikta alltid på fler rätt än tabellerna från tidigare år visar.' },
      { type: 'tip', text: 'Eftersom det inte finns minuspoäng ska du ALLTID svara på alla frågor, även om du måste chansa.' },
      { type: 'stat', value: '0.0–2.0', label: 'normerad poängskala i steg om 0.05' },
    ],
  },
  {
    id: 'intro-when-held',
    category: 'intro',
    title: 'När hålls provet?',
    subtitle: 'Datum, anmälan och vad som händer på provdagen',
    emoji: '📅',
    color: '#6366F1',
    gradient: ['#6366F1', '#8B5CF6'] as const,
    readingMinutes: 4,
    order: 4,
    source: 'local',
    blocks: [
      { type: 'paragraph', text: 'Högskoleprovet ges två gånger per år — en gång på våren (mars/april) och en gång på hösten (oktober). Anmälan öppnar cirka två månader före provet och stänger ungefär en månad innan.' },
      { type: 'heading', text: 'Provdagen i korthet' },
      { type: 'list', items: [
        'Samling tidig morgon (oftast kl. 08:10) — kom i god tid',
        'Fem provpass à 55 minuter med pauser emellan',
        'Lunchpaus mitt på dagen',
        'Hela dagen tar cirka 8 timmar',
        'Ta med giltig legitimation och blyertspennor',
      ] },
      { type: 'paragraph', text: 'Resultatet publiceras cirka fem veckor efter provdagen. Facit släpps redan dagen efter provet, så du kan rätta dig själv tidigt.' },
      { type: 'tip', text: 'Anmäl dig tidigt! Populära provorter kan bli fulla, och du vill skriva på en plats nära dig.' },
      { type: 'stat', value: '2×', label: 'per år — vår och höst' },
    ],
  },
  {
    id: 'intro-universities',
    category: 'intro',
    title: 'Så använder högskolorna ditt resultat',
    subtitle: 'Urvalsgrupper, antagningsgränser och strategi',
    emoji: '🏛️',
    color: '#6366F1',
    gradient: ['#6366F1', '#8B5CF6'] as const,
    readingMinutes: 5,
    order: 5,
    source: 'local',
    blocks: [
      { type: 'paragraph', text: 'När du söker en utbildning prövas du automatiskt i alla urvalsgrupper du är behörig för — betygsgruppen och högskoleprovsgruppen. Du antas via den grupp där du står dig bäst.' },
      { type: 'heading', text: 'Exempel på HP-gränser (kan variera)' },
      { type: 'list', items: [
        'Läkarprogrammet: ca 1.60–1.75',
        'Juristprogrammet: ca 1.40–1.60',
        'Psykologprogrammet: ca 1.50–1.70',
        'Civilingenjör: ca 0.90–1.40 beroende på inriktning',
        'Ekonomprogrammet: ca 0.90–1.30 beroende på lärosäte',
      ] },
      { type: 'paragraph', text: 'Gränserna sätts inte i förväg — de beror på hur många som söker och vilka resultat de har. En utbildning med få platser och många sökande får högre gränser.' },
      { type: 'tip', text: 'Kolla antagningsstatistik för din drömutbildning de senaste åren. Då vet du exakt vilken poäng du ska sikta på — och kan sätta ett konkret mål i din studieplan.' },
      { type: 'stat', value: '8 år', label: 'är ditt resultat giltigt' },
    ],
  },
];

export const HP_THEORY_HIGH_SCORE: HPTheoryArticle[] = [
  {
    id: 'hs-top-performers',
    category: 'high-score',
    title: 'Så pluggar toppresterarna',
    subtitle: 'Vanorna bakom resultat över 1.7',
    emoji: '🏆',
    color: '#F59E0B',
    gradient: ['#F59E0B', '#FBBF24'] as const,
    readingMinutes: 7,
    order: 1,
    source: 'local',
    blocks: [
      { type: 'paragraph', text: 'De som når toppresultat på högskoleprovet är sällan genier — de är systematiska. Här är mönstren som återkommer hos nästan alla som skriver 1.7 eller högre.' },
      { type: 'heading', text: '1. De övar på riktiga prov' },
      { type: 'paragraph', text: 'Toppresterare lägger merparten av sin tid på gamla prov under tidspress, inte på att passivt läsa teori. Provet testar färdigheter, och färdigheter byggs genom repetition under realistiska förhållanden.' },
      { type: 'heading', text: '2. De analyserar varje fel' },
      { type: 'paragraph', text: 'Efter varje övningspass går de igenom alla fel och kategoriserar dem: slarvfel, tidsbrist eller kunskapslucka? Varje kategori har olika åtgärd. Detta är den enskilt viktigaste vanan.' },
      { type: 'heading', text: '3. De tränar sina svagheter' },
      { type: 'paragraph', text: 'Det är lockande att öva på det man redan kan. Toppresterare gör tvärtom — de identifierar sitt svagaste delprov och attackerar det tills det inte längre drar ner totalen.' },
      { type: 'heading', text: '4. De bygger ordförråd långsiktigt' },
      { type: 'paragraph', text: 'ORD går inte att cramma. De som får högt lär sig 10–20 nya ord om dagen i månader, med flashcards och spaced repetition.' },
      { type: 'list', items: [
        'Öva 4–6 pass per vecka, hellre korta och fokuserade än långa och splittrade',
        'Skriv minst 3–4 hela prov under tidspress före provdagen',
        'För statistik över varje delprov — det du mäter förbättras',
      ] },
      { type: 'tip', text: 'Studiestugans statistikvy gör felanalysen åt dig — kolla efter varje pass vilka delprov och svårighetsgrader som drar ner dig.' },
    ],
  },
  {
    id: 'hs-long-term-plan',
    category: 'high-score',
    title: 'Långsiktig förberedelse',
    subtitle: 'Vecko- och dagsplaner från 3 månader till provdagen',
    emoji: '🗓️',
    color: '#F59E0B',
    gradient: ['#F59E0B', '#FBBF24'] as const,
    readingMinutes: 8,
    order: 2,
    source: 'local',
    blocks: [
      { type: 'heading', text: 'Fas 1: Kartläggning (vecka 1)' },
      { type: 'paragraph', text: 'Skriv ett helt gammalt prov under tidspress. Resultatet är din baslinje och visar exakt vilka delprov du ska prioritera. Utan baslinje pluggar du blint.' },
      { type: 'heading', text: 'Fas 2: Grundbygge (vecka 2–8)' },
      { type: 'list', items: [
        'Måndag–fredag: 30–60 min per dag, fokus på ditt svagaste delprov',
        '10–20 nya ord varje dag med flashcards',
        'Helg: ett längre pass med blandade delprov',
        'Varje söndag: gå igenom veckans fel och notera mönster',
      ] },
      { type: 'heading', text: 'Fas 3: Provträning (sista 4 veckorna)' },
      { type: 'list', items: [
        'Ett helt prov under provdagsförhållanden varje helg',
        'Vardagar: riktad träning på det senaste provets svagheter',
        'Trappa ner nyinlärning — fokusera på repetition',
      ] },
      { type: 'heading', text: 'En bra studiedag' },
      { type: 'paragraph', text: 'Kvalitet slår kvantitet. Ett fokuserat 45-minuterspass utan mobil ger mer än tre timmars halvdistraherat pluggande. Använd Pomodoro: 25 minuter fokus, 5 minuters paus.' },
      { type: 'tip', text: 'Boka in dina studiepass i kalendern som möten. Det som inte är schemalagt blir inte gjort.' },
      { type: 'stat', value: '12 veckor', label: 'räcker för de flesta att höja sig 0.3–0.5' },
    ],
  },
  {
    id: 'hs-motivation-recovery',
    category: 'high-score',
    title: 'Motivation, sömn och stress',
    subtitle: 'Hjärnan presterar bara om kroppen får återhämtning',
    emoji: '🧘',
    color: '#F59E0B',
    gradient: ['#F59E0B', '#FBBF24'] as const,
    readingMinutes: 6,
    order: 3,
    source: 'local',
    blocks: [
      { type: 'heading', text: 'Motivation är en följd, inte en förutsättning' },
      { type: 'paragraph', text: 'Vänta inte på motivation — den kommer av att se framsteg. Sätt ett konkret poängmål kopplat till din drömutbildning, bryt ner det i veckomål och fira varje delseger. Streaks och statistik fungerar för att de gör framstegen synliga.' },
      { type: 'heading', text: 'Sömnens roll i inlärningen' },
      { type: 'paragraph', text: 'Under djupsömnen flyttas det du övat på från korttids- till långtidsminnet. Att offra sömn för att plugga mer är därför kontraproduktivt — du lär dig mindre av mer arbete.' },
      { type: 'list', items: [
        'Sikta på 7–9 timmars sömn, särskilt nätterna efter tunga pass',
        'Plugga inte nytt material sent på kvällen — repetera i stället',
        'Sista natten före provet: prioritera sömn framför sista-minuten-plugg',
      ] },
      { type: 'heading', text: 'Hantera stress' },
      { type: 'list', items: [
        'Exponering: skriv övningsprov under tidspress så ofta att provkänslan blir vardag',
        'Andning: 4 sekunder in, 6 sekunder ut sänker pulsen på under en minut',
        'Perspektiv: provet går att skriva om — ett dåligt resultat raderar inget',
      ] },
      { type: 'warning', text: 'Utbrändhet förstör fler HP-resultat än lathet. Planera in minst en helt pluggfri dag per vecka.' },
    ],
  },
  {
    id: 'hs-common-mistakes',
    category: 'high-score',
    title: 'Vanligaste misstagen',
    subtitle: 'Fällorna som sänker resultatet — och hur du undviker dem',
    emoji: '⚠️',
    color: '#F59E0B',
    gradient: ['#F59E0B', '#FBBF24'] as const,
    readingMinutes: 5,
    order: 4,
    source: 'local',
    blocks: [
      { type: 'list', ordered: true, items: [
        'Öva utan tidspress — provets största utmaning är tiden. Träna alltid med klocka.',
        'Bara läsa teori — att känna igen ett ord är inte samma sak som att kunna använda det under press.',
        'Ignorera felen — utan felanalys upprepar du samma misstag på provdagen.',
        'Bara öva favoritdelprov — totalen styrs av ditt svagaste delprov, inte ditt starkaste.',
        'Lämna frågor obesvarade — inga minuspoäng betyder att du alltid ska chansa.',
        'Fastna på svåra frågor — varje fråga är värd lika mycket. 3 minuter på en fråga = 3 lätta frågor du missar.',
        'Cramma sista veckan — ordförråd och läshastighet byggs på månader, inte dagar.',
        'Skippa provsimulering — provdagen är 8 timmar lång. Uthållighet måste också tränas.',
      ] },
      { type: 'tip', text: 'Gå igenom listan en vecka före provet och ärligt bocka av: vilka av dessa gör jag fortfarande?' },
    ],
  },
  {
    id: 'hs-exam-day',
    category: 'high-score',
    title: 'Provdagen: komplett guide',
    subtitle: 'Från kvällen innan till sista provpasset',
    emoji: '🌅',
    color: '#F59E0B',
    gradient: ['#F59E0B', '#FBBF24'] as const,
    readingMinutes: 6,
    order: 5,
    source: 'local',
    blocks: [
      { type: 'heading', text: 'Kvällen innan' },
      { type: 'list', items: [
        'Packa: legitimation, flera blyertspennor, suddgummi, vattenflaska, energirik lunch och snacks',
        'Kolla resvägen och räkna med marginal',
        'Ingen ny inlärning — max lätt repetition av ord',
        'Lägg dig i vanlig tid; en normal natts sömn slår allt',
      ] },
      { type: 'heading', text: 'På morgonen' },
      { type: 'list', items: [
        'Ät en rejäl frukost med långsamma kolhydrater och protein',
        'Var på plats minst 30 minuter före insläpp',
        'Undvik att jämföra nervositet med andra — fokusera på din rutin',
      ] },
      { type: 'heading', text: 'Under provet' },
      { type: 'list', items: [
        'Ha en tidsplan per provpass: ca 2 min 45 sek per uppgift i snitt',
        'Hoppa direkt över frågor som känns tunga — markera och återvänd',
        'Fyll ALLTID i ett svar på alla frågor innan tiden går ut',
        'Använd pauserna: ät, drick, gå en sväng — sitt inte kvar och älta',
      ] },
      { type: 'heading', text: 'Mellan passen' },
      { type: 'paragraph', text: 'Ett dåligt provpass säger ingenting om nästa. Toppresterare släpper varje pass direkt när det är slut — nollställ, ät något och fokusera framåt.' },
      { type: 'tip', text: 'Socker-dipp efter lunch är verklig. Välj lunch med protein och fullkorn i stället för snabba kolhydrater.' },
    ],
  },
];
