export interface Course {
  code: string;
  name: string;
  points: number;
  year: 1 | 2 | 3;
  mandatory: boolean;
  category: 'gymnasiegemensam' | 'programgemensam' | 'inriktning' | 'programfördjupning' | 'individuellt val';
}

export interface ProgramCourseData {
  program: string;
  courses: Course[];
}

const gymnasiegemensamma: Course[] = [
  { code: 'ENG05', name: 'Engelska 5', points: 100, year: 1, mandatory: true, category: 'gymnasiegemensam' },
  { code: 'ENG06', name: 'Engelska 6', points: 100, year: 2, mandatory: true, category: 'gymnasiegemensam' },
  { code: 'HIS01a1', name: 'Historia 1a1', points: 50, year: 1, mandatory: true, category: 'gymnasiegemensam' },
  { code: 'IDR01', name: 'Idrott och hälsa 1', points: 100, year: 1, mandatory: true, category: 'gymnasiegemensam' },
  { code: 'MAT01a', name: 'Matematik 1a', points: 100, year: 1, mandatory: true, category: 'gymnasiegemensam' },
  { code: 'NAK01a1', name: 'Naturkunskap 1a1', points: 50, year: 1, mandatory: true, category: 'gymnasiegemensam' },
  { code: 'REL01', name: 'Religionskunskap 1', points: 50, year: 1, mandatory: true, category: 'gymnasiegemensam' },
  { code: 'SAM01a1', name: 'Samhällskunskap 1a1', points: 50, year: 1, mandatory: true, category: 'gymnasiegemensam' },
  { code: 'SVE01', name: 'Svenska 1', points: 100, year: 1, mandatory: true, category: 'gymnasiegemensam' },
  { code: 'SVE02', name: 'Svenska 2', points: 100, year: 2, mandatory: true, category: 'gymnasiegemensam' },
  { code: 'SVE03', name: 'Svenska 3', points: 100, year: 3, mandatory: true, category: 'gymnasiegemensam' },
];

const gymnasiegemssammaHF: Course[] = [
  { code: 'ENG05', name: 'Engelska 5', points: 100, year: 1, mandatory: true, category: 'gymnasiegemensam' },
  { code: 'ENG06', name: 'Engelska 6', points: 100, year: 2, mandatory: true, category: 'gymnasiegemensam' },
  { code: 'HIS01b', name: 'Historia 1b', points: 100, year: 1, mandatory: true, category: 'gymnasiegemensam' },
  { code: 'IDR01', name: 'Idrott och hälsa 1', points: 100, year: 1, mandatory: true, category: 'gymnasiegemensam' },
  { code: 'NAK01b', name: 'Naturkunskap 1b', points: 100, year: 1, mandatory: true, category: 'gymnasiegemensam' },
  { code: 'REL01', name: 'Religionskunskap 1', points: 50, year: 1, mandatory: true, category: 'gymnasiegemensam' },
  { code: 'SAM01b', name: 'Samhällskunskap 1b', points: 100, year: 1, mandatory: true, category: 'gymnasiegemensam' },
  { code: 'SVE01', name: 'Svenska 1', points: 100, year: 1, mandatory: true, category: 'gymnasiegemensam' },
  { code: 'SVE02', name: 'Svenska 2', points: 100, year: 2, mandatory: true, category: 'gymnasiegemensam' },
  { code: 'SVE03', name: 'Svenska 3', points: 100, year: 3, mandatory: true, category: 'gymnasiegemensam' },
];

export const programCourses: ProgramCourseData[] = [
  {
    program: 'Naturvetenskapsprogrammet',
    courses: [
      ...gymnasiegemssammaHF,
      { code: 'MAT01c', name: 'Matematik 1c', points: 100, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'MAT02c', name: 'Matematik 2c', points: 100, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'MAT03c', name: 'Matematik 3c', points: 100, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'MAT04', name: 'Matematik 4', points: 100, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'FYS01', name: 'Fysik 1', points: 150, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'FYS02', name: 'Fysik 2', points: 100, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'KEM01', name: 'Kemi 1', points: 100, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'KEM02', name: 'Kemi 2', points: 100, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'BIO01', name: 'Biologi 1', points: 100, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'BIO02', name: 'Biologi 2', points: 100, year: 3, mandatory: false, category: 'inriktning' },
      { code: 'MAT05', name: 'Matematik 5', points: 100, year: 3, mandatory: false, category: 'programfördjupning' },
      { code: 'PRG01', name: 'Programmering 1', points: 100, year: 2, mandatory: false, category: 'programfördjupning' },
      { code: 'MOD01', name: 'Moderna språk 3', points: 100, year: 2, mandatory: false, category: 'individuellt val' },
      { code: 'PSK01', name: 'Psykologi 1', points: 50, year: 3, mandatory: false, category: 'individuellt val' },
    ],
  },
  {
    program: 'Teknikprogrammet',
    courses: [
      ...gymnasiegemssammaHF,
      { code: 'MAT01c', name: 'Matematik 1c', points: 100, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'MAT02c', name: 'Matematik 2c', points: 100, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'MAT03c', name: 'Matematik 3c', points: 100, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'MAT04', name: 'Matematik 4', points: 100, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'FYS01', name: 'Fysik 1', points: 150, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'FYS02', name: 'Fysik 2', points: 100, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'KEM01', name: 'Kemi 1', points: 100, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'TEK01', name: 'Teknik 1', points: 150, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'TEK02', name: 'Teknik 2', points: 100, year: 2, mandatory: true, category: 'inriktning' },
      { code: 'PRG01', name: 'Programmering 1', points: 100, year: 2, mandatory: true, category: 'inriktning' },
      { code: 'PRG02', name: 'Programmering 2', points: 100, year: 3, mandatory: false, category: 'programfördjupning' },
      { code: 'WEB01', name: 'Webbutveckling 1', points: 100, year: 2, mandatory: false, category: 'programfördjupning' },
      { code: 'WEB02', name: 'Webbutveckling 2', points: 100, year: 3, mandatory: false, category: 'programfördjupning' },
      { code: 'MAT05', name: 'Matematik 5', points: 100, year: 3, mandatory: false, category: 'programfördjupning' },
      { code: 'MOD01', name: 'Moderna språk 3', points: 100, year: 2, mandatory: false, category: 'individuellt val' },
    ],
  },
  {
    program: 'Samhällsvetenskapsprogrammet',
    courses: [
      ...gymnasiegemssammaHF,
      { code: 'MAT01b', name: 'Matematik 1b', points: 100, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'MAT02b', name: 'Matematik 2b', points: 100, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'SAM02', name: 'Samhällskunskap 2', points: 100, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'SAM03', name: 'Samhällskunskap 3', points: 100, year: 3, mandatory: false, category: 'inriktning' },
      { code: 'HIS02a', name: 'Historia 2a', points: 100, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'FIL01', name: 'Filosofi 1', points: 50, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'PSK01', name: 'Psykologi 1', points: 50, year: 2, mandatory: true, category: 'inriktning' },
      { code: 'PSK02a', name: 'Psykologi 2a', points: 50, year: 3, mandatory: false, category: 'inriktning' },
      { code: 'ENG07', name: 'Engelska 7', points: 100, year: 3, mandatory: false, category: 'programfördjupning' },
      { code: 'MOD01', name: 'Moderna språk 3', points: 100, year: 1, mandatory: false, category: 'programfördjupning' },
      { code: 'MOD02', name: 'Moderna språk 4', points: 100, year: 2, mandatory: false, category: 'programfördjupning' },
      { code: 'JUR01', name: 'Juridik', points: 100, year: 3, mandatory: false, category: 'individuellt val' },
    ],
  },
  {
    program: 'Ekonomiprogrammet',
    courses: [
      ...gymnasiegemssammaHF,
      { code: 'MAT01b', name: 'Matematik 1b', points: 100, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'MAT02b', name: 'Matematik 2b', points: 100, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'FÖR01', name: 'Företagsekonomi 1', points: 100, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'FÖR02', name: 'Företagsekonomi 2', points: 100, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'SAM02', name: 'Samhällskunskap 2', points: 100, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'HIS02a', name: 'Historia 2a', points: 100, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'PRI01', name: 'Privatjuridik', points: 100, year: 2, mandatory: true, category: 'inriktning' },
      { code: 'ENT01', name: 'Entreprenörskap', points: 100, year: 3, mandatory: false, category: 'inriktning' },
      { code: 'MAR01', name: 'Marknadsföring', points: 100, year: 3, mandatory: false, category: 'programfördjupning' },
      { code: 'ENG07', name: 'Engelska 7', points: 100, year: 3, mandatory: false, category: 'programfördjupning' },
      { code: 'PSK01', name: 'Psykologi 1', points: 50, year: 3, mandatory: false, category: 'individuellt val' },
    ],
  },
  {
    program: 'Estetiska programmet',
    courses: [
      ...gymnasiegemssammaHF,
      { code: 'MAT01b', name: 'Matematik 1b', points: 100, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'EST01', name: 'Estetisk kommunikation 1', points: 100, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'EST02', name: 'Estetisk kommunikation 2', points: 100, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'EST03', name: 'Estetisk kommunikation 3', points: 100, year: 3, mandatory: true, category: 'programgemensam' },
      { code: 'KOT01', name: 'Konstarterna och samhället', points: 50, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'HIS02a', name: 'Historia 2a', points: 100, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'MUS01', name: 'Musik 1', points: 100, year: 1, mandatory: false, category: 'inriktning' },
      { code: 'MUS02', name: 'Musik 2', points: 100, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'BIL01', name: 'Bild och form 1a', points: 100, year: 1, mandatory: false, category: 'inriktning' },
      { code: 'DAN01', name: 'Dansteknik 1', points: 100, year: 1, mandatory: false, category: 'inriktning' },
      { code: 'TEA01', name: 'Teater 1', points: 100, year: 1, mandatory: false, category: 'inriktning' },
      { code: 'MOD01', name: 'Moderna språk 3', points: 100, year: 2, mandatory: false, category: 'individuellt val' },
    ],
  },
  {
    program: 'Humanistiska programmet',
    courses: [
      ...gymnasiegemssammaHF,
      { code: 'MAT01b', name: 'Matematik 1b', points: 100, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'HIS02b', name: 'Historia 2b – kultur', points: 100, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'HIS03', name: 'Historia 3', points: 100, year: 3, mandatory: true, category: 'programgemensam' },
      { code: 'FIL01', name: 'Filosofi 1', points: 50, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'FIL02', name: 'Filosofi 2', points: 50, year: 3, mandatory: false, category: 'inriktning' },
      { code: 'MOD03', name: 'Moderna språk 3', points: 100, year: 1, mandatory: true, category: 'inriktning' },
      { code: 'MOD04', name: 'Moderna språk 4', points: 100, year: 2, mandatory: true, category: 'inriktning' },
      { code: 'MOD05', name: 'Moderna språk 5', points: 100, year: 3, mandatory: false, category: 'programfördjupning' },
      { code: 'LAT01', name: 'Latin – språk och kultur 1', points: 100, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'ENG07', name: 'Engelska 7', points: 100, year: 3, mandatory: false, category: 'programfördjupning' },
      { code: 'PSK01', name: 'Psykologi 1', points: 50, year: 3, mandatory: false, category: 'individuellt val' },
    ],
  },
  {
    program: 'International Baccalaureate',
    courses: [
      { code: 'IB-ENG-HL', name: 'English A HL', points: 240, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'IB-SVE-SL', name: 'Swedish A SL', points: 150, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'IB-MAT-HL', name: 'Mathematics HL', points: 240, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'IB-MAT-SL', name: 'Mathematics SL', points: 150, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'IB-BIO-HL', name: 'Biology HL', points: 240, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'IB-PHY-HL', name: 'Physics HL', points: 240, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'IB-CHE-HL', name: 'Chemistry HL', points: 240, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'IB-HIS-SL', name: 'History SL', points: 150, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'IB-ECO-SL', name: 'Economics SL', points: 150, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'IB-TOK', name: 'Theory of Knowledge', points: 100, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'IB-EE', name: 'Extended Essay', points: 100, year: 3, mandatory: true, category: 'programgemensam' },
      { code: 'IB-CAS', name: 'CAS (Creativity, Activity, Service)', points: 50, year: 1, mandatory: true, category: 'programgemensam' },
    ],
  },
  {
    program: 'Bygg- och anläggningsprogrammet',
    courses: [
      ...gymnasiegemensamma,
      { code: 'BYG01', name: 'Bygg och anläggning 1', points: 200, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'BYG02', name: 'Bygg och anläggning 2', points: 200, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'RIT01', name: 'Ritning och konstruktion', points: 100, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'HUS01', name: 'Husbyggnad 1', points: 200, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'ANL01', name: 'Anläggning 1', points: 200, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'PLÅ01', name: 'Plåtslageri 1', points: 200, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'APL01', name: 'Arbetsplatsförlagt lärande 1', points: 200, year: 3, mandatory: true, category: 'programgemensam' },
    ],
  },
  {
    program: 'Barn- och fritidsprogrammet',
    courses: [
      ...gymnasiegemensamma,
      { code: 'PED01', name: 'Pedagogiskt arbete', points: 200, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'MÄN01', name: 'Människors miljöer', points: 100, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'HÄL01', name: 'Hälsopedagogik', points: 100, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'SOS01', name: 'Social omsorg 1', points: 100, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'BAR01', name: 'Barns lärande och växande', points: 100, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'FRI01', name: 'Fritids- och friskvårdsaktiviteter', points: 100, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'APL01', name: 'Arbetsplatsförlagt lärande 1', points: 200, year: 3, mandatory: true, category: 'programgemensam' },
    ],
  },
  {
    program: 'El- och energiprogrammet',
    courses: [
      ...gymnasiegemensamma,
      { code: 'ELT01', name: 'Elektroteknik', points: 100, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'ENE01', name: 'Energiteknik 1', points: 100, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'ELI01', name: 'Elinstallationer', points: 100, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'DAT01', name: 'Dator- och kommunikationsteknik', points: 100, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'AUT01', name: 'Automation 1', points: 100, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'MAT02a', name: 'Matematik 2a', points: 100, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'APL01', name: 'Arbetsplatsförlagt lärande 1', points: 200, year: 3, mandatory: true, category: 'programgemensam' },
    ],
  },
  {
    program: 'Fordons- och transportprogrammet',
    courses: [
      ...gymnasiegemensamma,
      { code: 'FOR01', name: 'Fordonsteknik – introduktion', points: 200, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'FOR02', name: 'Fordonsteknik – grund', points: 200, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'PER01', name: 'Personbilsteknik 1', points: 200, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'LAS01', name: 'Lastbilsteknik 1', points: 200, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'TRA01', name: 'Transport och spedition', points: 100, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'APL01', name: 'Arbetsplatsförlagt lärande 1', points: 200, year: 3, mandatory: true, category: 'programgemensam' },
    ],
  },
  {
    program: 'Handels- och administrationsprogrammet',
    courses: [
      ...gymnasiegemensamma,
      { code: 'HAN01', name: 'Handel och service', points: 100, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'FÖR01', name: 'Företagsekonomi 1', points: 100, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'INF01', name: 'Information och kommunikation 1', points: 100, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'ADM01', name: 'Administrativ service', points: 100, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'MAR01', name: 'Marknadsföring', points: 100, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'APL01', name: 'Arbetsplatsförlagt lärande 1', points: 200, year: 3, mandatory: true, category: 'programgemensam' },
    ],
  },
  {
    program: 'Hantverksprogrammet',
    courses: [
      ...gymnasiegemensamma,
      { code: 'HAV01', name: 'Hantverk – introduktion', points: 200, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'HAV02', name: 'Hantverk – grund', points: 200, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'FRI01', name: 'Frisör 1', points: 200, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'FLO01', name: 'Florist 1', points: 200, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'APL01', name: 'Arbetsplatsförlagt lärande 1', points: 200, year: 3, mandatory: true, category: 'programgemensam' },
    ],
  },
  {
    program: 'Hotell- och turismprogrammet',
    courses: [
      ...gymnasiegemensamma,
      { code: 'HOT01', name: 'Hotell och konferens', points: 100, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'TUR01', name: 'Turism och resor', points: 100, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'SER01', name: 'Serveringskunskap 1', points: 100, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'EVE01', name: 'Evenemang', points: 100, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'APL01', name: 'Arbetsplatsförlagt lärande 1', points: 200, year: 3, mandatory: true, category: 'programgemensam' },
    ],
  },
  {
    program: 'Industritekniska programmet',
    courses: [
      ...gymnasiegemensamma,
      { code: 'IND01', name: 'Industritekniska processer 1', points: 200, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'IND02', name: 'Industritekniska processer 2', points: 200, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'SVE01', name: 'Svetsteknik 1', points: 100, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'CNC01', name: 'CNC-teknik 1', points: 100, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'APL01', name: 'Arbetsplatsförlagt lärande 1', points: 200, year: 3, mandatory: true, category: 'programgemensam' },
    ],
  },
  {
    program: 'Naturbruksprogrammet',
    courses: [
      ...gymnasiegemensamma,
      { code: 'NAB01', name: 'Naturbruk 1', points: 200, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'NAB02', name: 'Naturbruk 2', points: 200, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'DJU01', name: 'Djurhållning 1', points: 100, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'SKG01', name: 'Skogsskötsel 1', points: 100, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'LAN01', name: 'Lantbruksteknik 1', points: 100, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'APL01', name: 'Arbetsplatsförlagt lärande 1', points: 200, year: 3, mandatory: true, category: 'programgemensam' },
    ],
  },
  {
    program: 'Restaurang- och livsmedelsprogrammet',
    courses: [
      ...gymnasiegemensamma,
      { code: 'LIV01', name: 'Livsmedels- och näringskunskap 1', points: 100, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'MAT01k', name: 'Matlagning 1', points: 200, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'BAG01', name: 'Bageri 1', points: 200, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'KON01', name: 'Konditori 1', points: 200, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'MAT02k', name: 'Matlagning 2', points: 200, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'APL01', name: 'Arbetsplatsförlagt lärande 1', points: 200, year: 3, mandatory: true, category: 'programgemensam' },
    ],
  },
  {
    program: 'VVS- och fastighetsprogrammet',
    courses: [
      ...gymnasiegemensamma,
      { code: 'VVS01', name: 'VVS-teknik 1', points: 200, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'VVS02', name: 'VVS-teknik 2', points: 200, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'FAS01', name: 'Fastighetsförvaltning', points: 100, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'KYL01', name: 'Kyl- och värmepumpteknik 1', points: 100, year: 2, mandatory: false, category: 'inriktning' },
      { code: 'APL01', name: 'Arbetsplatsförlagt lärande 1', points: 200, year: 3, mandatory: true, category: 'programgemensam' },
    ],
  },
  {
    program: 'Vård- och omsorgsprogrammet',
    courses: [
      ...gymnasiegemensamma,
      { code: 'HÄL01', name: 'Hälsopedagogik', points: 100, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'VÅR01', name: 'Vård- och omsorgsarbete 1', points: 200, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'VÅR02', name: 'Vård- och omsorgsarbete 2', points: 200, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'MED01', name: 'Medicin 1', points: 150, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'PSY01', name: 'Psykiatri 1', points: 100, year: 3, mandatory: false, category: 'inriktning' },
      { code: 'APL01', name: 'Arbetsplatsförlagt lärande 1', points: 200, year: 3, mandatory: true, category: 'programgemensam' },
    ],
  },
  {
    program: 'Flygteknikprogrammet',
    courses: [
      ...gymnasiegemensamma,
      { code: 'FLY01', name: 'Flygteknik – introduktion', points: 200, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'FLY02', name: 'Flygteknik – grund', points: 200, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'MAT02a', name: 'Matematik 2a', points: 100, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'FYS01', name: 'Fysik 1', points: 150, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'APL01', name: 'Arbetsplatsförlagt lärande 1', points: 200, year: 3, mandatory: true, category: 'programgemensam' },
    ],
  },
  {
    program: 'Sjöfartsprogrammet',
    courses: [
      ...gymnasiegemensamma,
      { code: 'SJÖ01', name: 'Sjöfart – introduktion', points: 200, year: 1, mandatory: true, category: 'programgemensam' },
      { code: 'SJÖ02', name: 'Sjöfart – grund', points: 200, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'NAV01', name: 'Navigation och sjömanskap', points: 100, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'MAT02a', name: 'Matematik 2a', points: 100, year: 2, mandatory: true, category: 'programgemensam' },
      { code: 'APL01', name: 'Arbetsplatsförlagt lärande 1', points: 200, year: 3, mandatory: true, category: 'programgemensam' },
    ],
  },
];
