import { StyleSheet, Dimensions } from 'react-native';
import { BG, BG2, TEXT1, TEXT2, TEXT3, ACCENT, DARK_BTN, BORDER } from './shared';

const { width: SW, height: SH } = Dimensions.get('window');

export const onboardingStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: BG,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    backgroundColor: BG,
  },
  navBar: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 8,
    justifyContent: 'space-between' as const,
  },
  backBtn: {
    width: 40,
    height: 40,
    justifyContent: 'center' as const,
    alignItems: 'flex-start' as const,
  },
  stepLabel: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: TEXT2,
    textAlign: 'center' as const,
  },
  stepLabelName: {
    color: TEXT1,
  },
  skipText: {
    fontSize: 14,
    color: TEXT2,
    fontWeight: '500' as const,
    width: 80,
    textAlign: 'right' as const,
  },
  progressContainer: {
    flexDirection: 'row' as const,
    paddingHorizontal: 20,
    gap: 4,
    marginBottom: 4,
  },
  progressSegmentWrap: {
    flex: 1,
    height: 4,
    borderRadius: 2,
    backgroundColor: BG2,
    overflow: 'hidden' as const,
  },
  progressSegment: {
    flex: 1,
    backgroundColor: BG2,
    borderRadius: 2,
  },
  progressSegmentActive: {
    backgroundColor: ACCENT,
  },
  content: {
    flex: 1,
  },
  footer: {
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 8,
  },
  cta: {
    backgroundColor: DARK_BTN,
    borderRadius: 32,
    height: 56,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 8,
  },
  ctaDisabled: {
    backgroundColor: '#C7C7CC',
  },
  ctaText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '700' as const,
  },
  centered: {
    flexGrow: 1,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    padding: 24,
  },
  page: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 8,
    paddingBottom: 24,
  },
  bigPage: {
    flexGrow: 1,
    justifyContent: 'center' as const,
    paddingHorizontal: 28,
    paddingVertical: 32,
  },
  logoWrap: {
    width: 96,
    height: 96,
    borderRadius: 24,
    backgroundColor: BG2,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    marginBottom: 32,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  logoImg: {
    width: 64,
    height: 64,
  },
  welcomeTitle: {
    fontSize: 32,
    fontWeight: '800' as const,
    color: TEXT1,
    textAlign: 'center' as const,
    letterSpacing: -0.5,
    lineHeight: 40,
  },
  welcomeBody: {
    fontSize: 17,
    color: TEXT2,
    textAlign: 'center' as const,
    marginTop: 16,
    lineHeight: 24,
    paddingHorizontal: 16,
  },
  bold: {
    fontWeight: '700' as const,
    color: TEXT1,
  },
  pageTitle: {
    fontSize: 24,
    fontWeight: '800' as const,
    color: TEXT1,
    letterSpacing: -0.3,
    marginBottom: 8,
  },
  pageSubtitle: {
    fontSize: 15,
    color: TEXT2,
    lineHeight: 22,
    marginBottom: 16,
  },
  pageBody: {
    fontSize: 16,
    color: TEXT2,
    lineHeight: 24,
    marginTop: 8,
    textAlign: 'center' as const,
  },
  questionTitle: {
    fontSize: 22,
    fontWeight: '800' as const,
    color: TEXT1,
    letterSpacing: -0.3,
    marginBottom: 6,
  },
  infoCard: {
    marginTop: 24,
    backgroundColor: BG2,
    borderRadius: 16,
    padding: 18,
    gap: 10,
  },
  infoCardText: {
    fontSize: 14,
    color: TEXT2,
    lineHeight: 20,
  },
  inputGroup: {
    marginBottom: 24,
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: TEXT1,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  input: {
    backgroundColor: BG2,
    borderRadius: 14,
    padding: 16,
    fontSize: 16,
    color: TEXT1,
    borderWidth: 1,
    borderColor: BORDER,
  },
  usernameRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
  },
  atSign: {
    fontSize: 18,
    color: TEXT2,
    fontWeight: '600' as const,
    marginRight: 10,
    backgroundColor: BG2,
    paddingHorizontal: 14,
    paddingVertical: 16,
    borderRadius: 14,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    borderWidth: 1,
    borderRightWidth: 0,
    borderColor: BORDER,
  },
  usernameStatus: {
    width: 40,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  errorTxt: {
    color: '#EF4444',
    fontSize: 12,
    marginTop: 6,
  },
  hintTxt: {
    color: TEXT3,
    fontSize: 12,
    marginTop: 6,
  },
  termsRow: {
    flexDirection: 'row' as const,
    alignItems: 'flex-start' as const,
    gap: 10,
    marginTop: 4,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#C7C7CC',
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    marginTop: 1,
  },
  checkboxOn: {
    backgroundColor: ACCENT,
    borderColor: ACCENT,
  },
  termsText: {
    flex: 1,
    fontSize: 13,
    color: TEXT2,
    lineHeight: 18,
  },
  // Education cards
  eduCard: {
    backgroundColor: BG,
    borderRadius: 20,
    padding: 18,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  eduCardIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 14,
    backgroundColor: BG2,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    flexShrink: 0,
  },
  eduCardTitle: {
    fontSize: 17,
    fontWeight: '700' as const,
    color: TEXT1,
    marginBottom: 3,
  },
  eduCardSub: {
    fontSize: 13,
    color: TEXT2,
    lineHeight: 18,
  },
  levelHintCard: {
    backgroundColor: '#F2F2F7',
    borderRadius: 12,
    padding: 14,
    marginTop: 20,
  },
  levelHintText: {
    fontSize: 13,
    color: TEXT2,
    lineHeight: 18,
  },
  optionCard: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    backgroundColor: BG,
    borderRadius: 16,
    padding: 16,
    gap: 12,
    borderWidth: 1.5,
    borderColor: BORDER,
  },
  optionCardSel: {
    borderColor: ACCENT,
    backgroundColor: '#ECFDF5',
  },
  optionEmoji: {
    fontSize: 22,
    width: 32,
    textAlign: 'center' as const,
  },
  optionLabel: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600' as const,
    color: TEXT1,
  },
  optionLabelSel: {
    color: ACCENT,
  },
  optionCheck: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: ACCENT,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  // Level picker
  yearRow: {
    flexDirection: 'row' as const,
    gap: 10,
    marginTop: 8,
  },
  yearBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: BG2,
    alignItems: 'center' as const,
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  yearBtnSel: {
    backgroundColor: '#ECFDF5',
    borderColor: ACCENT,
  },
  yearBtnText: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: TEXT2,
  },
  yearBtnTextSel: {
    color: ACCENT,
  },
  // Search
  searchRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    backgroundColor: BG2,
    borderRadius: 14,
    paddingHorizontal: 14,
    marginTop: 8,
    borderWidth: 1,
    borderColor: BORDER,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 14,
    fontSize: 15,
    color: TEXT1,
    marginLeft: 8,
  },
  listItem: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    padding: 14,
    borderRadius: 12,
    marginTop: 6,
    backgroundColor: BG,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  listItemSel: {
    borderColor: ACCENT,
    backgroundColor: '#ECFDF5',
  },
  listItemTitle: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: TEXT1,
  },
  listItemSub: {
    fontSize: 13,
    color: TEXT3,
    marginTop: 2,
  },
  hChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: BG2,
    marginRight: 8,
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  hChipSel: {
    backgroundColor: '#ECFDF5',
    borderColor: ACCENT,
  },
  hChipText: {
    fontSize: 14,
    fontWeight: '500' as const,
    color: TEXT2,
  },
  hChipTextSel: {
    color: ACCENT,
    fontWeight: '600' as const,
  },
  // Course rows
  courseRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 12,
    padding: 14,
    borderRadius: 14,
    backgroundColor: BG2,
    marginBottom: 6,
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  courseRowSel: {
    backgroundColor: '#ECFDF5',
    borderColor: ACCENT,
  },
  smallCheck: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#C7C7CC',
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  smallCheckOn: {
    backgroundColor: ACCENT,
    borderColor: ACCENT,
  },
  courseTitle: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: TEXT1,
  },
  mandTag: {
    fontSize: 10,
    color: ACCENT,
    fontWeight: '700' as const,
    marginTop: 2,
  },
  recommendedTag: {
    fontSize: 11,
    color: ACCENT,
    fontWeight: '700' as const,
    marginTop: 2,
  },
  // Komvux styles
  subjectChip: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 5,
    backgroundColor: BG2,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1.5,
    borderColor: BORDER,
  },
  subjectChipEmoji: {
    fontSize: 14,
  },
  subjectChipText: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: TEXT2,
  },
  komvuxRecommendBanner: {
    backgroundColor: '#FFFBEB',
    borderRadius: 12,
    padding: 12,
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#FDE68A',
  },
  komvuxRecommendText: {
    fontSize: 13,
    color: '#92400E',
    lineHeight: 18,
  },
  komvuxCourseRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 10,
    backgroundColor: BG2,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  komvuxCourseRowSel: {
    backgroundColor: '#ECFDF5',
    borderColor: ACCENT,
  },
  komvuxCourseEmoji: {
    fontSize: 18,
    width: 24,
    textAlign: 'center' as const,
  },
  komvuxCourseMeta: {
    fontSize: 12,
    color: TEXT3,
    marginTop: 2,
  },
  komvuxSelBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#ECFDF5',
    borderWidth: 1.5,
    borderColor: ACCENT,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  // Stress
  stressCenter: {
    alignItems: 'center' as const,
    paddingVertical: 20,
  },
  stressEmoji: {
    fontSize: 64,
    marginBottom: 12,
  },
  stressLabel: {
    fontSize: 18,
    fontWeight: '600' as const,
    color: TEXT1,
    marginBottom: 32,
    textAlign: 'center' as const,
  },
  sliderTrack: {
    height: 8,
    backgroundColor: BG2,
    borderRadius: 4,
    justifyContent: 'center' as const,
    marginBottom: 12,
  },
  sliderFill: {
    position: 'absolute' as const,
    height: 8,
    backgroundColor: ACCENT,
    borderRadius: 4,
    top: 0,
    left: 0,
  },
  sliderThumb: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
    position: 'absolute' as const,
    top: -10,
  },
  sliderLabels: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
  },
  sliderLabelText: {
    fontSize: 12,
    color: TEXT3,
  },
  // Dot grid
  dotGrid: {
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    gap: 6,
    justifyContent: 'center' as const,
    marginBottom: 32,
  },
  dot: {
    fontSize: 16,
    width: 18,
    textAlign: 'center' as const,
    lineHeight: 18,
  },
  dotStressed: {
    color: '#EF4444',
  },
  dotGrey: {
    color: TEXT3,
  },
  // Big text
  bigTitle: {
    fontSize: 32,
    fontWeight: '800' as const,
    color: TEXT1,
    textAlign: 'center' as const,
    letterSpacing: -0.5,
    marginBottom: 16,
    lineHeight: 38,
  },
  bigBody: {
    fontSize: 17,
    color: TEXT2,
    textAlign: 'center' as const,
    lineHeight: 26,
    marginTop: 8,
  },
  // Check list
  checkList: {
    marginTop: 24,
    gap: 14,
  },
  checkRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 12,
  },
  checkBubble: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: ACCENT,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  checkText: {
    fontSize: 16,
    color: TEXT1,
    fontWeight: '500' as const,
  },
  wowEmoji: {
    fontSize: 80,
    textAlign: 'center' as const,
    marginBottom: 28,
  },
  // Stats
  statsRow: {
    flexDirection: 'row' as const,
    gap: 10,
    marginVertical: 16,
  },
  statBox: {
    flex: 1,
    backgroundColor: BG2,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 8,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  statValue: {
    fontSize: 17,
    fontWeight: '800' as const,
    color: TEXT1,
    marginBottom: 4,
    lineHeight: 21,
    alignSelf: 'center' as const,
  },
  statLabel: {
    fontSize: 11,
    color: TEXT3,
    fontWeight: '500' as const,
    lineHeight: 14,
    alignSelf: 'center' as const,
  },
  featureList: {
    marginTop: 24,
    gap: 12,
  },
  featureRow: {
    backgroundColor: BG2,
    borderRadius: 14,
    padding: 16,
  },
  featureText: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: TEXT1,
  },
  // Testimonials
  testimonialCard: {
    backgroundColor: BG,
    borderRadius: 20,
    padding: 24,
    marginTop: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 4,
  },
  starsRow: {
    flexDirection: 'row' as const,
    gap: 4,
    marginBottom: 12,
  },
  testimonialText: {
    fontSize: 16,
    color: TEXT1,
    fontStyle: 'italic' as const,
    lineHeight: 24,
    marginBottom: 12,
  },
  testimonialAuthor: {
    fontSize: 14,
    color: TEXT3,
    fontWeight: '500' as const,
  },
  dotsRow: {
    flexDirection: 'row' as const,
    justifyContent: 'center' as const,
    gap: 8,
    marginBottom: 24,
  },
  testimonialDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#D1D5DB',
  },
  testimonialDotActive: {
    backgroundColor: ACCENT,
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  trustRow: {
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    justifyContent: 'center' as const,
    gap: 12,
    rowGap: 8,
    marginTop: 12,
  },
  trustItem: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
  },
  trustText: {
    fontSize: 13,
    color: TEXT2,
    fontWeight: '500' as const,
  },
  // Paywall
  paywallPage: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 8,
  },
  paywallHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    marginBottom: 20,
    position: 'relative' as const,
  },
  paywallLogo: {
    width: 48,
    height: 48,
  },
  closeBtn: {
    position: 'absolute' as const,
    right: 0,
    top: 4,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: BG2,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  closeBtnText: {
    fontSize: 16,
    color: TEXT3,
    fontWeight: '600' as const,
  },
  paywallTitle: {
    fontSize: 30,
    fontWeight: '800' as const,
    color: TEXT1,
    letterSpacing: -0.5,
    lineHeight: 36,
  },
  paywallSub: {
    fontSize: 15,
    color: ACCENT,
    fontWeight: '600' as const,
    marginTop: 6,
  },
  featuresSectionTitle: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: TEXT1,
    marginTop: 20,
    marginBottom: 12,
  },
  paywallFeatureRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 12,
    paddingVertical: 8,
  },
  paywallCheck: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: ACCENT,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  paywallFeatureText: {
    fontSize: 15,
    color: TEXT1,
    fontWeight: '500' as const,
  },
  pkgCard: {
    backgroundColor: BG,
    borderRadius: 20,
    padding: 20,
    borderWidth: 2,
    borderColor: BORDER,
    position: 'relative' as const,
  },
  pkgCardSel: {
    borderColor: ACCENT,
    backgroundColor: '#ECFDF5',
  },
  pkgPopular: {
    position: 'absolute' as const,
    top: -12,
    alignSelf: 'center' as const,
    backgroundColor: ACCENT,
    paddingHorizontal: 16,
    paddingVertical: 4,
    borderRadius: 10,
  },
  pkgPopularText: {
    fontSize: 11,
    fontWeight: '700' as const,
    color: '#fff',
    letterSpacing: 0.5,
  },
  pkgRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
  },
  pkgTitle: {
    fontSize: 17,
    fontWeight: '700' as const,
    color: TEXT1,
    marginBottom: 2,
  },
  pkgSub: {
    fontSize: 13,
    color: TEXT2,
  },
  pkgPrice: {
    fontSize: 18,
    fontWeight: '800' as const,
    color: TEXT1,
    marginBottom: 4,
  },
  pkgRadio: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: '#C7C7CC',
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  pkgRadioSel: {
    borderColor: ACCENT,
  },
  pkgRadioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: ACCENT,
  },
  skipPaywallBtn: {
    alignSelf: 'center' as const,
    marginTop: 16,
    paddingVertical: 12,
  },
  skipPaywallText: {
    fontSize: 15,
    color: TEXT2,
    fontWeight: '600' as const,
  },
  trustBadges: {
    flexDirection: 'row' as const,
    justifyContent: 'center' as const,
    gap: 16,
    marginTop: 20,
    paddingBottom: 8,
  },
  trustBadge: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
  },
  trustBadgeText: {
    fontSize: 12,
    color: TEXT3,
  },
  legalLinks: {
    flexDirection: 'row' as const,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    gap: 12,
    paddingVertical: 16,
  },
  legalLink: {
    fontSize: 13,
    color: TEXT3,
    fontWeight: '500' as const,
  },
  legalSep: {
    fontSize: 13,
    color: '#D1D5DB',
  },
  scrollContainer: {
    flexGrow: 1,
  },
});
