// Lista över alla Sveriges högskolor och universitet
export const universities = [
  // Universitet
  'Uppsala universitet',
  'Lunds universitet',
  'Göteborgs universitet',
  'Stockholms universitet',
  'Umeå universitet',
  'Linköpings universitet',
  'Karolinska Institutet',
  'Kungliga Tekniska högskolan (KTH)',
  'Luleå tekniska universitet',
  'Sveriges lantbruksuniversitet (SLU)',
  'Karlstads universitet',
  'Linnéuniversitetet',
  'Örebro universitet',
  'Mittuniversitetet',
  'Malmö universitet',
  
  // Konstnärliga högskolor
  'Konstfack',
  'Kungliga Konsthögskolan',
  'Kungliga Musikhögskolan i Stockholm',
  'Stockholms konstnärliga högskola',
  'Dans och cirkushögskolan',
  'Stockholms dramatiska högskola',
  
  // Handelshögskolor
  'Handelshögskolan i Stockholm',
  'Handelshögskolan vid Göteborgs universitet',
  'Handelshögskolan vid Umeå universitet',
  'Handelshögskolan vid Örebro universitet',
  'Handelshögskolan vid Karlstads universitet',
  
  // Tekniska högskolor
  'Chalmers tekniska högskola',
  'Blekinge tekniska högskola',
  'Högskolan i Jönköping - Tekniska högskolan',
  'Mälardalens universitet',
  
  // Statliga högskolor
  'Högskolan i Borås',
  'Högskolan Dalarna',
  'Högskolan i Gävle',
  'Högskolan i Halmstad',
  'Högskolan Kristianstad',
  'Högskolan i Skövde',
  'Högskolan Väst',
  'Södertörns högskola',
  
  // Specialhögskolor
  'Försvarshögskolan',
  'Gymnastik- och idrottshögskolan (GIH)',
  'Marie Cederschiöld högskola',
  'Röda Korsets högskola',
  'Sophiahemmet högskola',
  'Högskolan i Jönköping',
  
  // Enskilda utbildningsanordnare
  'Beckmans designhögskola',
  'Gammelkroppa skogsskola',
  'Johannelunds teologiska högskola',
  'Newmaninstitutet',
  'Skandinaviens akademi för psykoterapiutveckling',
  'Stockholm School of Theology',
  'Svenska institutet för kognitiv psykoterapi',
  'Teologiska högskolan Stockholm',
  'Örebro teologiska högskola',
  'Enskilda Högskolan Stockholm',
  
  // Folkhögskolor med högskoleutbildning
  'ALT Stockholm',
  'Berghs School of Communication',
  'Hyper Island',
  'Kulturama',
  
  // Campus och filialer
  'Campus Gotland (Uppsala universitet)',
  'Campus Helsingborg (Lunds universitet)',
  'Campus Norrköping (Linköpings universitet)',
  'Campus Skellefteå (Luleå tekniska universitet)',
  'Campus Sundsvall (Mittuniversitetet)',
  'Campus Östersund (Mittuniversitetet)',
  'Campus Växjö (Linnéuniversitetet)',
  'Campus Kalmar (Linnéuniversitetet)',
  'Campus Visby (Uppsala universitet)',
  'Campus Kiruna (Luleå tekniska universitet)',
  'Campus Piteå (Luleå tekniska universitet)',
  
  // Yrkeshögskolor (större)
  'Nackademin',
  'IHM Business School',
  'Medieinstitutet',
  'Changemaker Educations',
  'Chas Academy',
  'EC Utbildning',
  'Folkuniversitetet',
  'Hermods',
  'Jensen Education',
  'KYH - Yrkeshögskolan',
  'Lernia YH',
  'Newton Yrkeshögskola',
  'Plushögskolan',
  'STI - Scandinavian Technology Institute',
  'TUC Yrkeshögskola',
  'Yrgo',
  'YrkesAkademin',
  
  // Polishögskolor
  'Polishögskolan',
  
  // Militära högskolor
  'Militärhögskolan Halmstad',
  'Militärhögskolan Karlberg',
  
  // Internationella campus
  'Stockholm School of Economics in Riga',
  'European Business School (EBS)',
  
  // Specialiserade institut
  'Karolinska Institutet - Institutionen för medicin',
  'Karolinska Institutet - Institutionen för neurovetenskap',
  'Karolinska Institutet - Institutionen för onkologi-patologi',
  'KTH - Skolan för arkitektur och samhällsbyggnad',
  'KTH - Skolan för elektroteknik och datavetenskap',
  'KTH - Skolan för industriell teknik och management',
  'KTH - Skolan för teknikvetenskap',
  'KTH - Skolan för kemi, bioteknologi och hälsa',
  
  // Forskningsinstitut med utbildning
  'IVL Svenska Miljöinstitutet',
  'RISE Research Institutes of Sweden',
  'Nordiska Afrikainstitutet',
  'Institutet för framtidsstudier',
  'Institutet för social forskning (SOFI)',
  
  // Distansutbildning och e-learning
  'Hermods Distansutbildning',
  'NTI-skolan',
  'Komvux Distans',
  
  // Privata högskolor
  'Ersta Sköndal Bräcke högskola',
  'Evidens högskola',
  'Högskolan för fotografi',
  'Musikhögskolan Ingesund',
  'Operahögskolan i Stockholm',
  'Rudolf Steinerhögskolan',
  'Stockholms Musikpedagogiska Institut (SMI)',
  'Sveriges Ridgymnasium Strömsholm',
  'Waldorfhögskolan',
  
  // Teologiska seminarier och högskolor
  'Akademi för Ledarskap och Teologi (ALT)',
  'Evangeliska Frikyrkan (EFK) - Teologiska seminariet',
  'Pingst - Teologiska seminariet',
  'Svenska Baptistsamfundet - Teologiska seminariet',
  'Svenska kyrkans utbildningsinstitut',
  
  // Regionala högskolecentrum
  'Högskolecentrum Bohuslän',
  'Högskolecentrum Sjuhärad',
  'Högskolecentrum Skaraborg',
  'Lärcentrum Falun',
  'Campus Värnamo',
  'Campus Ljungby',
  'Campus Varberg',
  'Campus Hultsfred',
  'Campus Filipstad',
  'Campus Torsby',
  'Campus Arvika',
  'Campus Säffle',
  'Campus Åmål',
  
  // Branschspecifika högskolor
  'Hotell- och restauranghögskolan (Örebro universitet)',
  'Textilhögskolan (Högskolan i Borås)',
  'Sjöfartshögskolan (Chalmers)',
  'Sjöfartshögskolan (Linnéuniversitetet)',
  'Polishögskolan Sörentorp',
  'Räddningshögskolan Sandö',
  'Trafikflyghögskolan',
  
  // Nya och mindre högskolor
  'Campus Mölndal',
  'Högskolan i Eskilstuna',
  'Högskolan i Hudiksvall',
  'Högskolan i Karlskoga',
  'Högskolan i Lidköping',
  'Högskolan i Mariestad',
  'Högskolan i Motala',
  'Högskolan i Nyköping',
  'Högskolan i Oskarshamn',
  'Högskolan i Trollhättan',
  'Högskolan i Uddevalla',
  'Högskolan i Vänersborg',
  'Högskolan i Västervik',
  'Högskolan i Ystad',
  'Högskolan i Ängelholm',
  
  // Internationella samarbeten
  'World Maritime University (Malmö)',
  'United Nations University',
  'European Spallation Source (ESS)',
  
  // Kompletterande utbildningar
  'Korta vägen (för utländska akademiker)',
  'Kompletterande pedagogisk utbildning (KPU)',
  'Kompletterande utbildning för läkare (KUL)',
  'Kompletterande utbildning för tandläkare (KUT)',
  
  // Uppdragsutbildningar
  'Executive Education (Handelshögskolan)',
  'KTH Executive School',
  'Lund University Commissioned Education',
  'Uppsala universitet - Uppdragsutbildning',
  
  // Sommaruniversitet
  'Sommaruniversitetet i Visby',
  'Sommaruniversitetet i Marstrand',
  'Sommaruniversitetet i Båstad',
].sort();

export type University = typeof universities[number];

// Kategorisering av lärosäten
export const universityCategories = {
  'Universitet': [
    'Uppsala universitet',
    'Lunds universitet',
    'Göteborgs universitet',
    'Stockholms universitet',
    'Umeå universitet',
    'Linköpings universitet',
    'Karolinska Institutet',
    'Kungliga Tekniska högskolan (KTH)',
    'Luleå tekniska universitet',
    'Sveriges lantbruksuniversitet (SLU)',
    'Karlstads universitet',
    'Linnéuniversitetet',
    'Örebro universitet',
    'Mittuniversitetet',
    'Malmö universitet',
  ],
  'Högskolor': [
    'Högskolan i Borås',
    'Högskolan Dalarna',
    'Högskolan i Gävle',
    'Högskolan i Halmstad',
    'Högskolan Kristianstad',
    'Högskolan i Skövde',
    'Högskolan Väst',
    'Södertörns högskola',
    'Högskolan i Jönköping',
    'Blekinge tekniska högskola',
    'Chalmers tekniska högskola',
    'Mälardalens universitet',
  ],
  'Konstnärliga högskolor': [
    'Konstfack',
    'Kungliga Konsthögskolan',
    'Kungliga Musikhögskolan i Stockholm',
    'Stockholms konstnärliga högskola',
    'Dans och cirkushögskolan',
    'Stockholms dramatiska högskola',
    'Beckmans designhögskola',
  ],
  'Handelshögskolor': [
    'Handelshögskolan i Stockholm',
    'Handelshögskolan vid Göteborgs universitet',
    'Handelshögskolan vid Umeå universitet',
    'Handelshögskolan vid Örebro universitet',
    'Handelshögskolan vid Karlstads universitet',
  ],
  'Specialhögskolor': [
    'Försvarshögskolan',
    'Gymnastik- och idrottshögskolan (GIH)',
    'Marie Cederschiöld högskola',
    'Röda Korsets högskola',
    'Sophiahemmet högskola',
    'Polishögskolan',
  ],
  'Yrkeshögskolor': [
    'Nackademin',
    'IHM Business School',
    'Medieinstitutet',
    'Changemaker Educations',
    'Chas Academy',
    'EC Utbildning',
    'Jensen Education',
    'KYH - Yrkeshögskolan',
    'Lernia YH',
    'Newton Yrkeshögskola',
    'Yrgo',
    'YrkesAkademin',
  ],
};

// Program som erbjuds på högskolor och universitet
export const universityPrograms = [
  // Tekniska program
  'Civilingenjör - Datateknik',
  'Civilingenjör - Elektroteknik',
  'Civilingenjör - Maskinteknik',
  'Civilingenjör - Teknisk fysik',
  'Civilingenjör - Kemiteknik',
  'Civilingenjör - Industriell ekonomi',
  'Civilingenjör - Samhällsbyggnad',
  'Civilingenjör - Bioteknik',
  'Civilingenjör - Medicinsk teknik',
  'Civilingenjör - Miljö- och vattenteknik',
  'Högskoleingenjör - Datateknik',
  'Högskoleingenjör - Elektroteknik',
  'Högskoleingenjör - Maskinteknik',
  'Högskoleingenjör - Byggingenjör',
  
  // Medicin och hälsa
  'Läkarprogrammet',
  'Tandläkarprogrammet',
  'Sjuksköterskeprogrammet',
  'Fysioterapeutprogrammet',
  'Arbetsterapeutprogrammet',
  'Biomedicinsk analytiker',
  'Apotekarprogrammet',
  'Receptarieprogrammet',
  'Psykologprogrammet',
  'Logopedprogrammet',
  'Dietistprogrammet',
  'Röntgensjuksköterskeprogrammet',
  'Barnmorskeprogrammet',
  'Tandhygienistprogrammet',
  'Tandteknikerprogrammet',
  
  // Naturvetenskap
  'Kandidatprogram i biologi',
  'Kandidatprogram i kemi',
  'Kandidatprogram i fysik',
  'Kandidatprogram i matematik',
  'Kandidatprogram i geovetenskap',
  'Kandidatprogram i miljövetenskap',
  'Kandidatprogram i molekylärbiologi',
  'Kandidatprogram i datavetenskap',
  'Kandidatprogram i statistik',
  
  // Samhällsvetenskap
  'Juristprogrammet',
  'Ekonomprogrammet',
  'Civilekonomprogrammet',
  'Socionomprogrammet',
  'Politices kandidatprogram',
  'Kriminologprogrammet',
  'Personalvetarprogrammet',
  'Samhällsplanerarprogrammet',
  'Internationella relationer',
  'Europaprogrammet',
  'Utvecklingsstudier',
  'Statsvetarprogrammet',
  'Sociologiprogrammet',
  'Psykologiprogrammet',
  
  // Humaniora
  'Kandidatprogram i historia',
  'Kandidatprogram i filosofi',
  'Kandidatprogram i litteraturvetenskap',
  'Kandidatprogram i språkvetenskap',
  'Kandidatprogram i arkeologi',
  'Kandidatprogram i konstvetenskap',
  'Kandidatprogram i religionsvetenskap',
  'Kandidatprogram i kulturvetenskap',
  'Kandidatprogram i etnologi',
  'Kandidatprogram i genusvetenskap',
  
  // Lärarutbildningar
  'Förskollärarprogrammet',
  'Grundlärarprogrammet F-3',
  'Grundlärarprogrammet 4-6',
  'Ämneslärarprogrammet 7-9',
  'Ämneslärarprogrammet gymnasiet',
  'Yrkeslärarprogrammet',
  'Specialpedagogprogrammet',
  'Speciallärarprogrammet',
  'Studie- och yrkesvägledarprogrammet',
  
  // Konstnärliga utbildningar
  'Konstnärligt kandidatprogram i musik',
  'Konstnärligt kandidatprogram i dans',
  'Konstnärligt kandidatprogram i teater',
  'Konstnärligt kandidatprogram i film',
  'Konstnärligt kandidatprogram i konst',
  'Konstnärligt kandidatprogram i design',
  'Arkitektprogrammet',
  'Landskapsarkitektprogrammet',
  'Industridesignprogrammet',
  'Grafisk design och kommunikation',
  
  // Media och kommunikation
  'Journalistprogrammet',
  'Medie- och kommunikationsvetenskap',
  'Strategisk kommunikation',
  'Digital medieproduktion',
  'Film- och TV-produktion',
  'Grafisk design',
  'Webbutveckling',
  'UX-design',
  'Spelutveckling',
  
  // Ekonomi och handel
  'Business and Economics',
  'International Business',
  'Ekonomi och hållbar utveckling',
  'Redovisning och revision',
  'Marknadsföring',
  'Företagsekonomi',
  'Nationalekonomi',
  'Finansiering',
  'Logistik och supply chain management',
  'Retail Management',
  
  // IT och data
  'Systemvetenskap',
  'Informationssystem',
  'Dataingenjör',
  'Nätverksteknik',
  'IT-säkerhet',
  'Artificiell intelligens',
  'Data Science',
  'Mjukvaruutveckling',
  'Spelutveckling',
  'Webbutveckling',
  
  // Vård och omsorg
  'Folkhälsovetenskap',
  'Hälsopromotion',
  'Idrottsvetenskap',
  'Nutrition',
  'Äldrepedagogik',
  'Funktionshinderpedagogik',
  
  // Lantbruk och djur
  'Veterinärprogrammet',
  'Djursjukskötarprogrammet',
  'Agronomprogram - ekonomi',
  'Agronomprogram - husdjur',
  'Agronomprogram - landsbygdsutveckling',
  'Agronomprogram - livsmedel',
  'Agronomprogram - mark/växt',
  'Hippolog',
  'Etologi och djurskydd',
  'Landskapsingenjör',
  'Skogsmästarprogrammet',
  'Jägmästarprogrammet',
  'Trädgårdsingenjör',
  
  // Service och turism
  'Turismprogrammet',
  'Hotell- och restaurangprogrammet',
  'Event Management',
  'Gastronomi',
  'Sommelier',
  
  // Säkerhet och försvar
  'Officersprogrammet',
  'Säkerhet och krisberedskap',
  'Brandingenjör',
  'Riskhantering',
  
  // Internationella program
  'International Relations',
  'Global Studies',
  'Peace and Conflict Studies',
  'Human Rights',
  'Development Studies',
  'European Studies',
  'Asian Studies',
  'Middle Eastern Studies',
  'African Studies',
  'American Studies',
].sort();

// Städer med högskolor/universitet
export const universityCities = [
  'Stockholm',
  'Uppsala',
  'Lund',
  'Göteborg',
  'Malmö',
  'Linköping',
  'Örebro',
  'Umeå',
  'Karlstad',
  'Växjö',
  'Kalmar',
  'Jönköping',
  'Borås',
  'Gävle',
  'Halmstad',
  'Kristianstad',
  'Skövde',
  'Trollhättan',
  'Uddevalla',
  'Falun',
  'Borlänge',
  'Sundsvall',
  'Östersund',
  'Luleå',
  'Piteå',
  'Skellefteå',
  'Visby',
  'Karlskrona',
  'Eskilstuna',
  'Västerås',
  'Norrköping',
  'Södertälje',
  'Helsingborg',
].sort();