-- Insert all Swedish Gymnasium Schools
-- Table: gymnasiums (id, name, city, type, created_at, updated_at)

-- Clear existing data (optional - comment out if you want to keep existing)
-- TRUNCATE TABLE gymnasiums CASCADE;

INSERT INTO gymnasiums (id, name, city, type, created_at, updated_at) VALUES

-- STOCKHOLM LÄN
(gen_random_uuid(), 'Stockholms Tekniska Institut', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Norra Real', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Södra Latin', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Kungsholmens gymnasium', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Östra Real', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Thorildsplans gymnasium', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'S:t Eriks gymnasium', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Bromma gymnasium', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Blackebergs gymnasium', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Enskilda gymnasiet', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Viktor Rydberg Gymnasium Odenplan', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Viktor Rydberg Gymnasium Djursholm', 'Djursholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Viktor Rydberg Gymnasium Jarlaplan', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Stockholms Idrottsgymnasium', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Kungliga Svenska Balettskolan', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Kulturama Gymnasium', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Rytmus Musikergymnasiet Stockholm', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Södra Latins gymnasium', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Globala gymnasiet', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Enskede Gårds gymnasium', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Farsta gymnasium', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Skarpnäcks gymnasium', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Tumba gymnasium', 'Tumba', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Botkyrka gymnasium', 'Tumba', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Huddinge gymnasium', 'Huddinge', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Sjödalsgymnasiet', 'Huddinge', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Nacka gymnasium', 'Nacka', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Saltsjöbadens samskola', 'Saltsjöbaden', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Danderyds gymnasium', 'Danderyd', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Täby gymnasium', 'Täby', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Åva gymnasium', 'Täby', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Tibble gymnasium', 'Täby', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'ProCivitas Privata Gymnasium Stockholm', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'NTI Gymnasiet Stockholm', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'IT-Gymnasiet Stockholm', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Praktiska gymnasiet Stockholm', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Kunskapsgymnasiet Stockholm', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Internationella Engelska Gymnasiet Stockholm', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'JENSEN gymnasium Stockholm', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Europaskolan Stockholm', 'Stockholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Fredrika Bremergymnasiet', 'Haninge', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Haninge gymnasium', 'Haninge', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Tyresö gymnasium', 'Tyresö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Värmdö gymnasium', 'Värmdö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Lidingö gymnasium', 'Lidingö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Hersby gymnasium', 'Lidingö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Sollentuna gymnasium', 'Sollentuna', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Rudbeck gymnasium', 'Sollentuna', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Sundbybergs gymnasium', 'Sundbyberg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Solna gymnasium', 'Solna', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Järfälla gymnasium', 'Järfälla', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Upplands Väsby gymnasium', 'Upplands Väsby', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Vallentuna gymnasium', 'Vallentuna', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Norrtälje gymnasium', 'Norrtälje', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Rodengymnasiet', 'Norrtälje', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Sigtuna Humanistiska', 'Sigtuna', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Arlandagymnasiet', 'Sigtuna', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Märsta gymnasium', 'Märsta', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Södertälje gymnasium', 'Södertälje', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Torekällgymnasiet', 'Södertälje', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Nynäshamns gymnasium', 'Nynäshamn', 'gymnasium', NOW(), NOW()),

-- GÖTEBORG OCH VÄSTRA GÖTALAND
(gen_random_uuid(), 'Hvitfeldtska gymnasiet', 'Göteborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Schillerska gymnasiet', 'Göteborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Polhemsgymnasiet', 'Göteborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Lindholmens gymnasium', 'Göteborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Katrinelundsgymnasiet', 'Göteborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Angeredsgymnasiet', 'Göteborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Burgårdens gymnasium', 'Göteborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Plusgymnasiet Göteborg', 'Göteborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'IT-Gymnasiet Göteborg', 'Göteborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'NTI Gymnasiet Göteborg', 'Göteborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Kunskapsgymnasiet Göteborg', 'Göteborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'JENSEN gymnasium Göteborg', 'Göteborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Internationella Engelska Gymnasiet Göteborg', 'Göteborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'ProCivitas Privata Gymnasium Göteborg', 'Göteborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Rytmus Musikergymnasiet Göteborg', 'Göteborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Donnergymnasiet', 'Göteborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Elof Lindälvs gymnasium', 'Kungsbacka', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Aranäsgymnasiet', 'Kungsbacka', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Hulebäcksgymnasiet', 'Mölnlycke', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Fässbergsgymnasiet', 'Mölndal', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Lindåsgymnasiet', 'Lindome', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Porthälla gymnasium', 'Partille', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Lerum gymnasium', 'Lerum', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Alströmergymnasiet', 'Alingsås', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Borås gymnasium', 'Borås', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Almåsgymnasiet', 'Borås', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Bäckängsgymnasiet', 'Borås', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Sven Eriksonsgymnasiet', 'Borås', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Trollhättans gymnasium', 'Trollhättan', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Magnus Åbergsgymnasiet', 'Trollhättan', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Uddevalla gymnasium', 'Uddevalla', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Östrabo gymnasium', 'Uddevalla', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Vänersborgs gymnasium', 'Vänersborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Birger Sjöberggymnasiet', 'Vänersborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Kunskapsförbundet Västs gymnasium', 'Trollhättan', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Nösnäsgymnasiet', 'Stenungsund', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Strömstads gymnasium', 'Strömstad', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Tanum Shearwater International', 'Tanumshede', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Ljungskile folkhögskola gymnasium', 'Ljungskile', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Drottning Blankas gymnasium Göteborg', 'Göteborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'LBS Kreativa Gymnasiet Göteborg', 'Göteborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Realgymnasiet Göteborg', 'Göteborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Skara gymnasium', 'Skara', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Katedralskolan Skara', 'Skara', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Lidköpings gymnasium', 'Lidköping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'De la Gardiegymnasiet', 'Lidköping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Falköpings gymnasium', 'Falköping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Ållebergsgymnasiet', 'Falköping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Skövde gymnasium', 'Skövde', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Kavelbrogymnasiet', 'Skövde', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Västerhöjdsgymnasiet', 'Skövde', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Mariestad gymnasium', 'Mariestad', 'gymnasium', NOW(), NOW()),

-- MALMÖ OCH SKÅNE
(gen_random_uuid(), 'Malmö Borgarskola', 'Malmö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Malmö Latin', 'Malmö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Heleneholms gymnasium', 'Malmö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Malmö Idrottsgymnasium', 'Malmö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Pauliskolan', 'Malmö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Frans Suellsgymnasiet', 'Malmö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Universitetsholmens gymnasium', 'Malmö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Jörgen Kocksgymnasiets', 'Malmö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Pauli gymnasium', 'Malmö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'IT-Gymnasiet Malmö', 'Malmö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'NTI Gymnasiet Malmö', 'Malmö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Kunskapsgymnasiet Malmö', 'Malmö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'JENSEN gymnasium Malmö', 'Malmö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'ProCivitas Privata Gymnasium Malmö', 'Malmö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Internationella Engelska Gymnasiet Malmö', 'Malmö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Praktiska gymnasiet Malmö', 'Malmö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Plusgymnasiet Malmö', 'Malmö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Lunds kommun gymnasium', 'Lund', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Katedralskolan Lund', 'Lund', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Polhemskolan Lund', 'Lund', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Spyken', 'Lund', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Vipan', 'Lund', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Procivitas Gymnasium Lund', 'Lund', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'NTI Gymnasiet Lund', 'Lund', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Helsingborgs gymnasium', 'Helsingborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Nicolaiskolan', 'Helsingborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Filbornaskolan', 'Helsingborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Olympiaområdets gymnasium', 'Helsingborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'IT-Gymnasiet Helsingborg', 'Helsingborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Ängelholms gymnasium', 'Ängelholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Rönnegymnasiet', 'Ängelholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Landskrona gymnasium', 'Landskrona', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Sundsgymnasierna', 'Vellinge', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Trelleborgs gymnasium', 'Trelleborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Söderslättsgymnasiet', 'Trelleborg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Eslövs gymnasium', 'Eslöv', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Ystads gymnasium', 'Ystad', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Österportgymnasiet', 'Ystad', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Kristianstad gymnasium', 'Kristianstad', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Söderportgymnasiet', 'Kristianstad', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Hässleholms gymnasium', 'Hässleholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'T4-gymnasiet', 'Hässleholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Klippans gymnasium', 'Klippan', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Perstorps gymnasium', 'Perstorp', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Höganäs gymnasium', 'Höganäs', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Kullagymnasiet', 'Höganäs', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Simrishamns gymnasium', 'Simrishamn', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Katedralskolan Växjö', 'Växjö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Staffanstorps gymnasium', 'Staffanstorp', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Lomma gymnasium', 'Lomma', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Löddeköpinge gymnasium', 'Löddeköpinge', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Burlövs gymnasium', 'Arlöv', 'gymnasium', NOW(), NOW()),

-- UPPSALA LÄN
(gen_random_uuid(), 'Katedralskolan Uppsala', 'Uppsala', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Lundellska skolan', 'Uppsala', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Rosendalsgymnasiet', 'Uppsala', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Fyrisskolan', 'Uppsala', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Bolandgymnasiet', 'Uppsala', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Celsiusskolan', 'Uppsala', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'IT-Gymnasiet Uppsala', 'Uppsala', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'NTI Gymnasiet Uppsala', 'Uppsala', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'JENSEN gymnasium Uppsala', 'Uppsala', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Kunskapsgymnasiet Uppsala', 'Uppsala', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'ProCivitas Uppsala', 'Uppsala', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Enköpings gymnasium', 'Enköping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Westerlundska gymnasiet', 'Enköping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Bålbroskolan', 'Enköping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Tierps gymnasium', 'Tierp', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Östhammars gymnasium', 'Östhammar', 'gymnasium', NOW(), NOW()),

-- LINKÖPING OCH ÖSTERGÖTLAND
(gen_random_uuid(), 'Katedralskolan Linköping', 'Linköping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Birgittaskolan', 'Linköping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Berzeliusskolan', 'Linköping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Ljungstedtska gymnasiet', 'Linköping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'IT-Gymnasiet Linköping', 'Linköping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'NTI Gymnasiet Linköping', 'Linköping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Norrköpings gymnasium', 'Norrköping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'De Geergymnasiet', 'Norrköping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Ebersteinska gymnasiet', 'Norrköping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'IT-Gymnasiet Norrköping', 'Norrköping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Motala gymnasium', 'Motala', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Platengymnasiet', 'Motala', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Mjölby gymnasium', 'Mjölby', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Dackeskolan', 'Mjölby', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Finspångs gymnasium', 'Finspång', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Söderköpings gymnasium', 'Söderköping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Vadstena gymnasium', 'Vadstena', 'gymnasium', NOW(), NOW()),

-- JÖNKÖPING LÄN
(gen_random_uuid(), 'Per Brahegymnasiet', 'Jönköping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Sandagymnasiet', 'Jönköping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Bäckadalsgymnasiet', 'Jönköping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Energigymnasiet Jönköping', 'Jönköping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'IT-Gymnasiet Jönköping', 'Jönköping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'NTI Gymnasiet Jönköping', 'Jönköping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Procivitas Jönköping', 'Jönköping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Värnamo gymnasium', 'Värnamo', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Finnvedens gymnasium', 'Värnamo', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Eksjö gymnasium', 'Eksjö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Njudungsgymnasiet', 'Vetlanda', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Nässjö gymnasium', 'Nässjö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Tranås gymnasium', 'Tranås', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Gnosjöandans gymnasium', 'Gnosjö', 'gymnasium', NOW(), NOW()),

-- KALMAR LÄN
(gen_random_uuid(), 'Lars Kaggskolan', 'Kalmar', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Stagneliusskolan', 'Kalmar', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Jenny Nyströmskolan', 'Kalmar', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'NTI Gymnasiet Kalmar', 'Kalmar', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Västerviks gymnasium', 'Västervik', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Oskarshamns gymnasium', 'Oskarshamn', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Vimmerby gymnasium', 'Vimmerby', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Hultsfreds gymnasium', 'Hultsfred', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Borgholms gymnasium', 'Borgholm', 'gymnasium', NOW(), NOW()),

-- KRONOBERG LÄN
(gen_random_uuid(), 'Katedralskolan Växjö', 'Växjö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Teknikum Växjö', 'Växjö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'NTI Gymnasiet Växjö', 'Växjö', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Ljungby gymnasium', 'Ljungby', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Sunnerbogymnasiet', 'Ljungby', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Älmhults gymnasium', 'Älmhult', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Haganässkolan', 'Älmhult', 'gymnasium', NOW(), NOW()),

-- BLEKINGE LÄN
(gen_random_uuid(), 'Chapmangymnasiet', 'Karlskrona', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Ehrensvärdska gymnasiet', 'Karlskrona', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Törnströmska gymnasiet', 'Karlskrona', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'NTI Gymnasiet Karlskrona', 'Karlskrona', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Karlshamns gymnasium', 'Karlshamn', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Väggaskolan', 'Karlshamn', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Ronneby gymnasium', 'Ronneby', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Sölvesborgs gymnasium', 'Sölvesborg', 'gymnasium', NOW(), NOW()),

-- HALLAND
(gen_random_uuid(), 'Peder Skrivares skola', 'Varberg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'NTI Gymnasiet Halmstad', 'Halmstad', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Sannarpsgymnasiet', 'Halmstad', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Kattegattgymnasiet', 'Halmstad', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Sturegymnasiet', 'Halmstad', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Falkenbergs gymnasium', 'Falkenberg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Falkenbergsskolan', 'Falkenberg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Laholms gymnasium', 'Laholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Hylte gymnasium', 'Hyltebruk', 'gymnasium', NOW(), NOW()),

-- VÄRMLAND
(gen_random_uuid(), 'Tingvallagymnasiet', 'Karlstad', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Sundsta-Älvkullegymnasiet', 'Karlstad', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'NTI Gymnasiet Karlstad', 'Karlstad', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'IT-Gymnasiet Karlstad', 'Karlstad', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'ProCivitas Karlstad', 'Karlstad', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Kristinehamns gymnasium', 'Kristinehamn', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Brogårdsgymnasiet', 'Kristinehamn', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Arvika gymnasium', 'Arvika', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Solbergagymnasiet', 'Arvika', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Säffle gymnasium', 'Säffle', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Hagfors gymnasium', 'Hagfors', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Filipstads gymnasium', 'Filipstad', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Storfors gymnasium', 'Storfors', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Sunne gymnasium', 'Sunne', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Torsby gymnasium', 'Torsby', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Forshaga gymnasium', 'Forshaga', 'gymnasium', NOW(), NOW()),

-- ÖREBRO LÄN
(gen_random_uuid(), 'Karolinska skolan', 'Örebro', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Risbergska skolan', 'Örebro', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Virginska skolan', 'Örebro', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Tullängskolan', 'Örebro', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'NTI Gymnasiet Örebro', 'Örebro', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'IT-Gymnasiet Örebro', 'Örebro', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Kunskapsgymnasiet Örebro', 'Örebro', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Karlskoga gymnasium', 'Karlskoga', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Möckelngymnasiet', 'Karlskoga', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Lindesbergs gymnasium', 'Lindesberg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Lindeskolan', 'Lindesberg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Hallsbergs gymnasium', 'Hallsberg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Askersunds gymnasium', 'Askersund', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Nora gymnasium', 'Nora', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Kumla gymnasium', 'Kumla', 'gymnasium', NOW(), NOW()),

-- VÄSTMANLAND
(gen_random_uuid(), 'Rudbeckianska gymnasiet', 'Västerås', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Carlforsska gymnasiet', 'Västerås', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Widénska gymnasiet', 'Västerås', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Hässlögymnasiet', 'Västerås', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'NTI Gymnasiet Västerås', 'Västerås', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'IT-Gymnasiet Västerås', 'Västerås', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'JENSEN gymnasium Västerås', 'Västerås', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Fagersta gymnasium', 'Fagersta', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Brinellgymnasiet', 'Fagersta', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Köpings gymnasium', 'Köping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Ullvigymnasiet', 'Köping', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Arboga gymnasium', 'Arboga', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Vasagymnasiet Arboga', 'Arboga', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Sala gymnasium', 'Sala', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Kungsänggymnasiet', 'Sala', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Norbergs gymnasium', 'Norberg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Skinnskattebergs gymnasium', 'Skinnskatteberg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Surahammars gymnasium', 'Surahammar', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Hallstahammars gymnasium', 'Hallstahammar', 'gymnasium', NOW(), NOW()),

-- DALARNA
(gen_random_uuid(), 'Falu Frigymnasium', 'Falun', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Kristinegymnasiet', 'Falun', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Lugnetgymnasiet', 'Falun', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'NTI Gymnasiet Falun', 'Falun', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Borlänge gymnasium', 'Borlänge', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Hagagymnasiet', 'Borlänge', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Soltorgsgymnasiet', 'Borlänge', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Mora gymnasium', 'Mora', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Moragymnasiet', 'Mora', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Leksands gymnasium', 'Leksand', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Rättviks gymnasium', 'Rättvik', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Ludvika gymnasium', 'Ludvika', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Polstjärneskolan', 'Ludvika', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Avesta gymnasium', 'Avesta', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Karlfeldtgymnasiet', 'Avesta', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Hedemora gymnasium', 'Hedemora', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Säters gymnasium', 'Säter', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Malung-Sälens gymnasium', 'Malung', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Älvdalens gymnasium', 'Älvdalen', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Vansbro gymnasium', 'Vansbro', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Orsa gymnasium', 'Orsa', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Gagnefs gymnasium', 'Gagnef', 'gymnasium', NOW(), NOW()),

-- GÄVLEBORG
(gen_random_uuid(), 'Polhemsskolan Gävle', 'Gävle', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Vasaskolan Gävle', 'Gävle', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Borgarskolan Gävle', 'Gävle', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'NTI Gymnasiet Gävle', 'Gävle', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Praktiska gymnasiet Gävle', 'Gävle', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Sandvikens gymnasium', 'Sandviken', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Bessemerskolan', 'Sandviken', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Söderhamns gymnasium', 'Söderhamn', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Staffangymnasiet', 'Söderhamn', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Bollnäs gymnasium', 'Bollnäs', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Torsbergsgymnasiet', 'Bollnäs', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Hudiksvalls gymnasium', 'Hudiksvall', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Bromangymnasiet', 'Hudiksvall', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Ljusdals gymnasium', 'Ljusdal', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Slottegymnasiet', 'Ljusdal', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Hofors gymnasium', 'Hofors', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Ockelbo gymnasium', 'Ockelbo', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Ovanåkers gymnasium', 'Edsbyn', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Nordanstigs gymnasium', 'Bergsjö', 'gymnasium', NOW(), NOW()),

-- VÄSTERNORRLAND
(gen_random_uuid(), 'Sundsvalls gymnasium', 'Sundsvall', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Västermalms gymnasium', 'Sundsvall', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Hedbergska skolan', 'Sundsvall', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'NTI Gymnasiet Sundsvall', 'Sundsvall', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Härnösands gymnasium', 'Härnösand', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Murbergsgymnasiet', 'Härnösand', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Örnsköldsviks gymnasium', 'Örnsköldsvik', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Nolaskolan', 'Örnsköldsvik', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Parkskolan Örnsköldsvik', 'Örnsköldsvik', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Kramfors gymnasium', 'Kramfors', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Ådalsskolan', 'Kramfors', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Sollefteå gymnasium', 'Sollefteå', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Ångermanlands gymnasium', 'Sollefteå', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Timrå gymnasium', 'Timrå', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Ånge gymnasium', 'Ånge', 'gymnasium', NOW(), NOW()),

-- JÄMTLAND
(gen_random_uuid(), 'Jämtlands gymnasium', 'Östersund', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Wargentinskolan', 'Östersund', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Fyrvallaskolan', 'Östersund', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'NTI Gymnasiet Östersund', 'Östersund', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Sveg gymnasium', 'Sveg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Härjedalens gymnasium', 'Sveg', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Bergs gymnasium', 'Svenstavik', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Åre gymnasium', 'Järpen', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Strömsunds gymnasium', 'Strömsund', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Krokoms gymnasium', 'Krokom', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Bräcke gymnasium', 'Bräcke', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Ragunda gymnasium', 'Hammarstrand', 'gymnasium', NOW(), NOW()),

-- VÄSTERBOTTEN
(gen_random_uuid(), 'Dragonskolan', 'Umeå', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Midgårdsskolan', 'Umeå', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Forslundagymnasiet', 'Umeå', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Fridhemsgymnasiet', 'Umeå', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'IT-Gymnasiet Umeå', 'Umeå', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'NTI Gymnasiet Umeå', 'Umeå', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Skellefteå gymnasium', 'Skellefteå', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Balderskolan', 'Skellefteå', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Anderstorpsskolan', 'Skellefteå', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'NTI Gymnasiet Skellefteå', 'Skellefteå', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Lycksele gymnasium', 'Lycksele', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Tannbergsskolan', 'Lycksele', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Vännäs gymnasium', 'Vännäs', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Lärcentrum Vännäs', 'Vännäs', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Vilhelmina gymnasium', 'Vilhelmina', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Malgomajskolan', 'Vilhelmina', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Storumans gymnasium', 'Storuman', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Luspengymnasiet', 'Storuman', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Dorotea gymnasium', 'Dorotea', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Åsele gymnasium', 'Åsele', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Nordmalings gymnasium', 'Nordmaling', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Robertsfors gymnasium', 'Robertsfors', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Vindeln gymnasium', 'Vindeln', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Bjurholms gymnasium', 'Bjurholm', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Sorsele gymnasium', 'Sorsele', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Malå gymnasium', 'Malå', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Norsjö gymnasium', 'Norsjö', 'gymnasium', NOW(), NOW()),

-- NORRBOTTEN
(gen_random_uuid(), 'Luleå gymnasium', 'Luleå', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Midskogsskolan', 'Luleå', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Björkskataskolan', 'Luleå', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'NTI Gymnasiet Luleå', 'Luleå', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'IT-Gymnasiet Luleå', 'Luleå', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Strömbackaskolan', 'Piteå', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Rosviks gymnasium', 'Piteå', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Framnässkolan', 'Piteå', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Bodens gymnasium', 'Boden', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Björknäsgymnasiet', 'Boden', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Tornedalsskolan', 'Haparanda', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Haparanda gymnasium', 'Haparanda', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Kalix gymnasium', 'Kalix', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Centralskolan Kalix', 'Kalix', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Älvsby gymnasium', 'Älvsbyn', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Kiruna gymnasium', 'Kiruna', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Hjalmar Lundbohmsskolan', 'Kiruna', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Gällivare gymnasium', 'Gällivare', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Dundrets gymnasium', 'Gällivare', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Arvidsjaurs gymnasium', 'Arvidsjaur', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Sandbackaskolan', 'Arvidsjaur', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Jokkmokks gymnasium', 'Jokkmokk', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Bokenskolan', 'Jokkmokk', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Överkalix gymnasium', 'Överkalix', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Övertorneå gymnasium', 'Övertorneå', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Pajala gymnasium', 'Pajala', 'gymnasium', NOW(), NOW()),
(gen_random_uuid(), 'Arjeplogs gymnasium', 'Arjeplog', 'gymnasium', NOW(), NOW())

ON CONFLICT (id) DO NOTHING;

-- Optional: Create index for faster lookups by city
CREATE INDEX IF NOT EXISTS idx_gymnasiums_city ON gymnasiums(city);
CREATE INDEX IF NOT EXISTS idx_gymnasiums_name ON gymnasiums(name);
